// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/geometry/Multipoint","require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/lang ../core/accessorSupport/decorators ./Extent ./Geometry ./Point ./support/zmUtils".split(" "),function(d,E,B,f,n,e,C,D,l,y){function z(e){return function(b,g){return null==b?g:null==g?b:e(b,g)}}d=function(d){function b(){for(var a=0;a<arguments.length;a++);a=d.call(this)||this;a.points=[];a.type="multipoint";return a}B(b,d);g=b;b.prototype.normalizeCtorArgs=
function(a,A){if(!a&&!A)return null;var c={};Array.isArray(a)?(c.points=a,c.spatialReference=A):!a||"esri.geometry.SpatialReference"!==a.declaredClass&&null==a.wkid?(a.points&&(c.points=a.points),a.spatialReference&&(c.spatialReference=a.spatialReference),a.hasZ&&(c.hasZ=a.hasZ),a.hasM&&(c.hasM=a.hasM)):c.spatialReference=a;var b=c.points&&c.points[0];b&&(void 0===c.hasZ&&void 0===c.hasM?(c.hasZ=2<b.length,c.hasM=!1):void 0===c.hasZ?c.hasZ=3<b.length:void 0===c.hasM&&(c.hasM=3<b.length));return c};
Object.defineProperty(b.prototype,"extent",{get:function(){var a=this.points;if(!a.length)return null;for(var b=new C,c=this.hasZ,e=this.hasM,g=c?3:2,k=a[0],d=z(Math.min),f=z(Math.max),p=k[0],q=k[1],r=k[0],k=k[1],t,u,v,w,x=0,n=a.length;x<n;x++){var h=a[x],m=h[0],l=h[1],p=d(p,m),q=d(q,l),r=f(r,m),k=f(k,l);c&&2<h.length&&(m=h[2],t=d(t,m),v=f(v,m));e&&h.length>g&&(h=h[g],u=d(u,h),w=f(w,h))}b.xmin=p;b.ymin=q;b.xmax=r;b.ymax=k;b.spatialReference=this.spatialReference;c?(b.zmin=t,b.zmax=v):(b.zmin=null,
b.zmax=null);e?(b.mmin=u,b.mmax=w):(b.mmin=null,b.mmax=null);return b},enumerable:!0,configurable:!0});b.prototype.writePoints=function(a,b,c,d){b.points=n.clone(this.points)};b.prototype.addPoint=function(a){this.clearCache();y.updateSupportFromPoint(this,a);Array.isArray(a)?this.points.push(a):this.points.push(a.toArray());return this};b.prototype.clone=function(){var a={points:n.clone(this.points),spatialReference:this.spatialReference};this.hasZ&&(a.hasZ=!0);this.hasM&&(a.hasM=!0);return new g(a)};
b.prototype.getPoint=function(a){if(!this._validateInputs(a))return null;a=this.points[a];var b={x:a[0],y:a[1],spatialReference:this.spatialReference},c=2;this.hasZ&&(b.z=a[2],c=3);this.hasM&&(b.m=a[c]);return new l(b)};b.prototype.removePoint=function(a){if(!this._validateInputs(a))return null;this.clearCache();return new l(this.points.splice(a,1)[0],this.spatialReference)};b.prototype.setPoint=function(a,b){if(!this._validateInputs(a))return this;this.clearCache();y.updateSupportFromPoint(b);this.points[a]=
b.toArray();return this};b.prototype.toJSON=function(a){return this.write(null,a)};b.prototype._validateInputs=function(a){return null!=a&&0<=a&&a<this.points.length};f([e.property({dependsOn:["points","hasZ","hasM","spatialReference"]})],b.prototype,"cache",void 0);f([e.property({dependsOn:["cache"]})],b.prototype,"extent",null);f([e.property({type:[[Number]],json:{write:{isRequired:!0}}})],b.prototype,"points",void 0);f([e.writer("points")],b.prototype,"writePoints",null);return b=g=f([e.subclass("esri.geometry.Multipoint")],
b);var g}(e.declared(D));d.prototype.toJSON.isDefaultToJSON=!0;return d});