// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/geometry/Point","require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/Logger ../core/accessorSupport/decorators ./Geometry ./SpatialReference ./support/spatialReferenceUtils ./support/webMercatorUtils".split(" "),function(h,y,t,k,u,e,v,w,x,m){function q(e){return e&&("esri.geometry.SpatialReference"===e.declaredClass||null!=e.wkid)}var n=[0,0],r=u.getLogger("esri.geometry.Point");h=function(h){function b(a,c,b,g,f){a=h.call(this)||
this;a.x=0;a.y=0;a.z=void 0;a.m=void 0;a.type="point";return a}t(b,h);p=b;b.copy=function(a,c){c.x=a.x;c.y=a.y;c.z=a.z;c.m=a.m;c.spatialReference=Object.isFrozen(a.spatialReference)?a.spatialReference:a.spatialReference.clone()};b.distance=function(a,c){var b=a.x-c.x,g=a.y-c.y,f=a.hasZ&&c.hasZ?a.z-c.z:0;return Math.sqrt(b*b+g*g+f*f)};b.prototype.normalizeCtorArgs=function(a,c,b,g,f){var d;if(Array.isArray(a))d=a,f=c,a=d[0],c=d[1],b=d[2],g=d[3];else if(a&&"object"===typeof a){if(d=a,a=null!=d.x?d.x:
d.longitude,c=null!=d.y?d.y:d.latitude,b=null!=d.z?d.z:d.altitude,g=d.m,(f=d.spatialReference)&&"esri.geometry.SpatialReference"!==f.declaredClass&&(f=new w(f)),null!=d.longitude||null!=d.latitude)null==d.longitude?r.warn(".longitude\x3d","Latitude was defined without longitude"):null==d.latitude?r.warn(".latitude\x3d","Longitude was defined without latitude"):!d.declaredClass&&f&&f.isWebMercator&&(c=m.lngLatToXY(d.longitude,d.latitude,n),a=c[0],c=c[1])}else q(b)?(f=b,b=null):q(g)&&(f=g,g=null);a=
{x:a,y:c};null!=f&&(a.spatialReference=f);null!=b&&(a.z=b);null!=g&&(a.m=g);return a};Object.defineProperty(b.prototype,"hasM",{get:function(){return void 0!==this.m},set:function(a){var c=this._get("hasM");a!==c&&(this._set("m",a?0:void 0),this._set("hasM",a))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasZ",{get:function(){return void 0!==this.z},set:function(a){var c=this._get("hasZ");a!==c&&(this._set("z",a?0:void 0),this._set("hasZ",a))},enumerable:!0,configurable:!0});
Object.defineProperty(b.prototype,"latitude",{get:function(){var a=this._get("spatialReference");if(a){if(a.isWebMercator)return m.xyToLngLat(this.x,this.y,n)[1];if(a.isWGS84)return this._get("y")}return null},set:function(a){var c=this._get("spatialReference");c&&(c.isWebMercator?this._set("y",m.lngLatToXY(this.x,a,n)[1]):c.isWGS84&&this._set("y",a),this._set("latitude",a))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"longitude",{get:function(){var a=this._get("spatialReference");
if(a){if(a.isWebMercator)return m.xyToLngLat(this._get("x"),this._get("y"),n)[0];if(a.isWGS84)return this._get("x")}return null},set:function(a){var c=this._get("spatialReference");c&&(c.isWebMercator?this._set("x",m.lngLatToXY(a,this._get("y"),n)[0]):c.isWGS84&&this._set("x",a),this._set("longitude",a))},enumerable:!0,configurable:!0});b.prototype.clone=function(){var a=new p;a.x=this.x;a.y=this.y;a.z=this.z;a.m=this.m;a.spatialReference=this.spatialReference;return a};b.prototype.copy=function(a){p.copy(a,
this);return this};b.prototype.equals=function(a){if(!a)return!1;var c=this.x,b=this.y,g=this.z,f=this.m,d=this.spatialReference,e=a.z,k=a.m,h=a.x,l=a.y;a=a.spatialReference;if(!d.equals(a))if(d.isWebMercator&&a.isWGS84)l=m.lngLatToXY(h,l),h=l[0],l=l[1],a=d;else if(d.isWGS84&&a.isWebMercator)l=m.xyToLngLat(h,l),h=l[0],l=l[1],a=d;else return!1;return c===h&&b===l&&g===e&&f===k&&d.wkid===a.wkid};b.prototype.offset=function(a,c,b){this.x+=a;this.y+=c;null!=b&&this.hasZ&&(this.z+=b);return this};b.prototype.normalize=
function(){if(!this.spatialReference)return this;var a=x.getInfo(this.spatialReference);if(!a)return this;var c=this.x,b=a.valid,a=b[0],e=b[1],b=2*e;c>e?(a=Math.ceil(Math.abs(c-e)/b),c-=a*b):c<a&&(a=Math.ceil(Math.abs(c-a)/b),c+=a*b);this._set("x",c);return this};b.prototype.distance=function(a){return p.distance(this,a)};b.prototype.toArray=function(){var a=this.hasZ,b=this.hasM;return a&&b?[this.x,this.y,this.z,this.m]:a?[this.x,this.y,this.z]:b?[this.x,this.y,this.m]:[this.x,this.y]};b.prototype.toJSON=
function(a){return this.write(null,a)};k([e.property({dependsOn:["x","y","z","m","spatialReference"]})],b.prototype,"cache",void 0);k([e.property({type:Boolean,dependsOn:["m"],json:{write:{enabled:!1,overridePolicy:null}}})],b.prototype,"hasM",null);k([e.property({type:Boolean,dependsOn:["z"],json:{write:{enabled:!1,overridePolicy:null}}})],b.prototype,"hasZ",null);k([e.property({type:Number,dependsOn:["y"]})],b.prototype,"latitude",null);k([e.property({type:Number,dependsOn:["x"]})],b.prototype,
"longitude",null);k([e.property({type:Number,json:{write:{isRequired:!0}}})],b.prototype,"x",void 0);k([e.property({type:Number,json:{write:!0}})],b.prototype,"y",void 0);k([e.property({type:Number,json:{write:{overridePolicy:function(){return{enabled:this.hasZ}}}}})],b.prototype,"z",void 0);k([e.property({type:Number,json:{write:{overridePolicy:function(){return{enabled:this.hasM}}}}})],b.prototype,"m",void 0);return b=p=k([e.subclass("esri.geometry.Point")],b);var p}(e.declared(v));h.prototype.toJSON.isDefaultToJSON=
!0;return h});