// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/geometry/Polyline","require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/lang ../core/accessorSupport/decorators ./Extent ./Geometry ./Point ./SpatialReference ./support/zmUtils".split(" "),function(k,N,K,l,w,e,I,L,m,M,x){function J(n){return function(b,h){return null==b?h:null==h?b:n(b,h)}}var n=J(Math.min),h=J(Math.max);k=function(k){function b(){for(var a=0;a<arguments.length;a++);a=k.call(this)||this;a.paths=[];a.type=
"polyline";return a}K(b,k);r=b;b.prototype.normalizeCtorArgs=function(a,f){var c=null,d,b,g=null;a&&!Array.isArray(a)?(c=a.paths?a.paths:null,f||(a.spatialReference?f=a.spatialReference:a.paths||(f=a)),d=a.hasZ,b=a.hasM):c=a;c=c||[];f=f||M.WGS84;c.length&&c[0]&&null!=c[0][0]&&"number"===typeof c[0][0]&&(c=[c]);if(g=c[0]&&c[0][0])void 0===d&&void 0===b?(d=2<g.length,b=!1):void 0===d?d=!b&&3<g.length:void 0===b&&(b=!d&&3<g.length);return{paths:c,spatialReference:f,hasZ:d,hasM:b}};Object.defineProperty(b.prototype,
"extent",{get:function(){var a=this.hasZ,f=this.hasM,c=this.spatialReference,d=this.paths,b=a?3:2;if(!d.length||!d[0].length)return null;for(var g=d[0][0],k=g[0],g=g[1],e=d[0][0],m=e[0],e=e[1],l=void 0,y=void 0,r=void 0,w=void 0,D=[],E=0;E<d.length;E++){for(var z=d[E],t=z[0],F=t[0],t=t[1],u=z[0],G=u[0],u=u[1],A=void 0,B=void 0,x=void 0,q=void 0,H=0;H<z.length;H++){var v=z[H],p=v[0],C=v[1],k=n(k,p),g=n(g,C),m=h(m,p),e=h(e,C),F=n(F,p),t=n(t,C),G=h(G,p),u=h(u,C);a&&2<v.length&&(p=v[2],l=n(l,p),y=h(y,
p),A=n(A,p),B=h(B,p));f&&v.length>b&&(q=v[b],r=n(l,q),w=h(y,q),x=n(A,q),q=h(B,q))}D.push(new I({xmin:F,ymin:t,zmin:A,mmin:x,xmax:G,ymax:u,zmax:B,mmax:q,spatialReference:c}))}d=new I;d.xmin=k;d.ymin=g;d.xmax=m;d.ymax=e;d.spatialReference=c;a&&(d.zmin=l,d.zmax=y);f&&(d.mmin=r,d.mmax=w);d.cache._partwise=1<D.length?D:null;return d},enumerable:!0,configurable:!0});b.prototype.writePaths=function(a,b,c,d){b.paths=w.clone(this.paths)};b.prototype.addPath=function(a){if(a){this.clearCache();var b=this.paths,
c=b.length;if(Array.isArray(a[0]))b[c]=a.concat();else{for(var d=[],e=0,g=a.length;e<g;e++)d[e]=a[e].toArray();b[c]=d}return this}};b.prototype.clone=function(){var a=new r;a.spatialReference=this.spatialReference;a.paths=w.clone(this.paths);a.hasZ=this.hasZ;a.hasM=this.hasM;return a};b.prototype.getPoint=function(a,b){if(!this._validateInputs(a,b))return null;var c=this.paths[a][b],d=this.hasZ,f=this.hasM;return d&&!f?new m(c[0],c[1],c[2],void 0,this.spatialReference):f&&!d?new m(c[0],c[1],void 0,
c[2],this.spatialReference):d&&f?new m(c[0],c[1],c[2],c[3],this.spatialReference):new m(c[0],c[1],this.spatialReference)};b.prototype.insertPoint=function(a,b,c){if(!this._validateInputs(a,b,!0))return this;this.clearCache();x.updateSupportFromPoint(this,c);Array.isArray(c)||(c=c.toArray());this.paths[a].splice(b,0,c);return this};b.prototype.removePath=function(a){if(!this._validateInputs(a,null))return null;this.clearCache();a=this.paths.splice(a,1)[0];var b=this.spatialReference;return a.map(function(a){return new m(a,
b)})};b.prototype.removePoint=function(a,b){if(!this._validateInputs(a,b))return null;this.clearCache();return new m(this.paths[a].splice(b,1)[0],this.spatialReference)};b.prototype.setPoint=function(a,b,c){if(!this._validateInputs(a,b))return this;this.clearCache();x.updateSupportFromPoint(this,c);Array.isArray(c)||(c=c.toArray());this.paths[a][b]=c;return this};b.prototype._validateInputs=function(a,b,c){void 0===c&&(c=!1);return null==a||0>a||a>=this.paths.length||null!=b&&(a=this.paths[a],c&&
(0>b||b>a.length)||!c&&(0>b||b>=a.length))?!1:!0};b.prototype.toJSON=function(a){return this.write(null,a)};l([e.property({dependsOn:["hasM","hasZ","paths"]})],b.prototype,"cache",void 0);l([e.property({dependsOn:["cache"],readOnly:!0})],b.prototype,"extent",null);l([e.property({type:[[[Number]]],json:{write:{isRequired:!0}}})],b.prototype,"paths",void 0);l([e.writer("paths")],b.prototype,"writePaths",null);return b=r=l([e.subclass("esri.geometry.Polyline")],b);var r}(e.declared(L));k.prototype.toJSON.isDefaultToJSON=
!0;return k});