// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/layers/features/processors/SymbolProcessor","require exports ../../../../../core/executeAsync ../../../../../core/MapPool ../../../../../core/promiseUtils ../../../../../core/SetPool ../../../engine/webgl/displayObjectUtils ../../../engine/webgl/TileData ../../../engine/webgl/Utils".split(" "),function(t,u,w,k,g,r,x,y,l){function v(a,c){l.isMarkerSymbol(a)||l.isLineSymbol(a)?c.add(a):l.isFillSymbol(a)&&(c.add(a),a.outline&&"none"!==a.outline.style&&c.add(a.outline))}
function z(a,c){if(!c.has(a)){c.set(a,new Set);for(var b=a.text,m=c.get(a),e=b.length,d=0;d<e;d++){var n=b.charCodeAt(d);m.add(n)}}}Object.defineProperty(u,"__esModule",{value:!0});t=function(){function a(c){this.type="symbol";this._symbolToMosaicItemMap=new Map;this._symbolToMosaicItemMap.clear();this._objectIdField=c.objectIdField;this._geometryType=c.geometryType;this._rendererInfo=c.rendererInfo;this._devicePixelRatio=c.devicePixelRatio;this._textureManager=c.textureManager}a.prototype.destroy=
function(){this._symbolToMosaicItemMap.clear()};a.prototype.getTileData=function(c,b){var a=this;return b&&b.features&&0!==b.features.length?g.when(this._getMosaicItems(b.features)).then(function(){return a._createTileData(b.features)}).then(function(b){return{tileKey:c,data:b}}):g.resolve({tileKey:c,data:null})};a.prototype._createTileData=function(c){var b=this,a=[],e={},d=0;return w(function(){var m=c[d];d++;m=x.getDisplayObject(m,b._objectIdField,b._rendererInfo,b._geometryType,b._devicePixelRatio,
b._symbolToMosaicItemMap,e);a.push(m);return d===c.length}).then(function(){return y.create(a,e)})};a.prototype._getMosaicItems=function(c){var b=r.acquire(),a=k.acquire(),e=this._rendererInfo;e.renderer.backgroundFillSymbol&&v(e.renderer.backgroundFillSymbol,b);for(var d,n=0;n<c.length;n++)d=c[n],(d=e.getSymbol(d))&&(l.isTextSymbol(d)?z(d,a):v(d,b));if(0===b.size&&0===a.size)return r.release(b),k.release(a),g.resolve();var p=k.acquire(),q=[],h=this._symbolToMosaicItemMap,f=0;b.forEach(function(a){h.has(a)||
(p.set(f,a),q.push({symbol:a.toJSON(),id:f}),f++)});a.forEach(function(a,c){if(h.has(c)){var b=h.get(c).glyphMosaicItems,d=[];a.forEach(function(a){if(b&&b.length<a||!b[a])d[a]=a});0<d.length&&(p.set(f,c),q.push({symbol:c.toJSON(),id:f,glyphIds:d}),f++)}else{p.set(f,c);var e=Array(a.size);a.forEach(function(a){return e.push(a)});q.push({symbol:c.toJSON(),id:f,glyphIds:e});f++}});if(0<q.length)return this._getMaterialItems(q).then(function(a){for(var c=0;c<a.length;c++){var b=a[c],d=p.get(b.id);if(d)if(l.isTextSymbol(d))if(h.has(d)){if(d=
h.get(d).glyphMosaicItems,b=b.mosaicItem.glyphMosaicItems)for(var e=0;e<b.length;e++)null!=b[e]&&(d[e]=b[e])}else h.set(d,b.mosaicItem);else h.set(d,b.mosaicItem)}k.release(p);return g.resolve()});r.release(b);k.release(a);return g.resolve()};a.prototype._getMaterialItems=function(a){if(!a||0===a.length)return g.resolve([]);for(var b=[],c=0;c<a.length;c++){var e=a[c];b.push(this._textureManager.rasterizeItem(e.symbol,e.glyphIds))}return g.all(b).then(function(a){return a.map(function(a,b){return{id:b,
mosaicItem:a}})})};return a}();u.SymbolProcessor=t});