// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/CIMSymbolDrawHelper","require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/decorateHelper ./GeometryUtils ./Rect".split(" "),function(k,m,p,q,r,t){Object.defineProperty(m,"__esModule",{value:!0});var n=function(){function c(a){this._t=a}c.createIdentity=function(){return new c([1,0,0,0,1,0])};c.prototype.clone=function(){return new c(this._t.slice())};c.prototype.transform=function(a){var b=this._t;return[b[0]*a[0]+
b[1]*a[1]+b[2],b[3]*a[0]+b[4]*a[1]+b[5]]};c.createScale=function(a,b){return new c([a,0,0,0,b,0])};c.prototype.scale=function(a,b){var d=this._t;d[0]*=a;d[1]*=a;d[2]*=a;d[3]*=b;d[4]*=b;d[5]*=b;return this};c.prototype.scaleRatio=function(){return Math.sqrt(this._t[0]*this._t[0]+this._t[1]*this._t[1])};c.createTranslate=function(a,b){return new c([0,0,a,0,0,b])};c.prototype.translate=function(a,b){var d=this._t;d[2]+=a;d[5]+=b;return this};c.createRotate=function(a){var b=Math.cos(a);a=Math.sin(a);
return new c([b,-a,0,a,b,0])};c.prototype.rotate=function(a){return this.multiply(c.createRotate(a))};c.prototype.multiply=function(a){var b=this._t;a=a._t;var d=b[1]*a[0]+b[4]*a[1],u=b[2]*a[0]+b[5]*a[1]+a[2],e=b[0]*a[3]+b[3]*a[4],c=b[1]*a[3]+b[4]*a[4],f=b[2]*a[3]+b[5]*a[4]+a[5];b[0]=b[0]*a[0]+b[3]*a[1];b[1]=d;b[2]=u;b[3]=e;b[4]=c;b[5]=f;return this};return c}();m.Transformation=n;k=function(){function c(a){this._transfos=[];this._sizeTransfos=[];this._transfos.push(a||n.createIdentity());this._sizeTransfos.push(a?
a.scaleRatio():1)}c.prototype.transformPt=function(a){return this._transfos[this._transfos.length-1].transform(a)};c.prototype.transformSize=function(a){return a*this._sizeTransfos[this._sizeTransfos.length-1]};c.prototype.back=function(){return this._transfos[this._transfos.length-1]};c.prototype.push=function(a){var b=a.scaleRatio();a.multiply(this.back());this._transfos.push(a);this._sizeTransfos.push(this._sizeTransfos[this._sizeTransfos.length-1]*b)};c.prototype.pop=function(){this._transfos.splice(-1,
1);this._sizeTransfos.splice(-1,1)};c.prototype.drawSolidFill=function(a,b){};c.prototype.drawSolidStroke=function(a,b,d){};c.prototype.drawSymbol=function(a,b){if(a)switch(a.type){case "CIMPointSymbol":case "CIMLineSymbol":case "CIMPolygonSymbol":this.drawMultiLayerSymbol(a,b)}};c.prototype.drawMultiLayerSymbol=function(a,b){if(a){var d=a.symbolLayers;if(d)for(var c=d.length;c--;){var e=d[c];if(e&&e.enable)switch(e.type){case "CIMSolidFill":this.drawSolidFill(b,e.color);break;case "CIMSolidStroke":this.drawSolidStroke(b,
e.color,e.width);break;case "CIMVectorMarker":this.drawVectorMarker(e,b)}}}};c.prototype.drawVectorMarker=function(a,b){if(a){var d=a.markerGraphics;if(d){var c=a.size,e=a.frame,h=e?e.ymax-e.ymin:0,h=c&&h?c/h:1,f=n.createIdentity();e&&f.translate(.5*-(e.xmax+e.xmin),.5*-(e.ymax+e.ymin));var g=a.anchorPt;if(g){var l=g.x,g=g.y;"relative"===a.anchorPtUnits&&e&&(l*=(e.xmax-e.xmin)*h,g*=c);f.translate(-l,-g)}1!==h&&f.scale(h,h);a.rotation&&f.rotate(a.rotation*r.C_DEG_TO_RAD);f.translate(a.offsetX||0,a.offsetY||
0);f.translate(b.x,b.y);this.push(f);for(c=0;c<d.length;c++)(e=d[c])&&this.drawSymbol(e.symbol,e.geometry);this.pop()}}};return c}();m.CIMSymbolDrawHelper=k;q=function(c){function a(){var a=c.call(this)||this;a._xmin=a._ymin=Infinity;a._xmax=a._ymax=-Infinity;return a}p(a,c);a.prototype.envelope=function(){return new t(this._xmin,this._ymin,this._xmax-this._xmin,this._ymax-this._ymin)};a.prototype._merge=function(a,d){a[0]-d<this._xmin&&(this._xmin=a[0]-d);a[0]+d>this._xmax&&(this._xmax=a[0]+d);a[1]-
d<this._ymin&&(this._ymin=a[1]-d);a[1]+d>this._ymax&&(this._ymax=a[1]+d)};a.prototype.drawSolidFill=function(a,d){for(var b=0,c=a.rings;b<c.length;b++){var h=c[b],f=h?h.length:0;if(2<f){this._merge(this.transformPt(h[0]),0);for(var g=1;g<f;++g)this._merge(this.transformPt(h[g]),0)}}};a.prototype.drawSolidStroke=function(a,d,c){d=.5*this.transformSize(c);c=0;for(a=a.rings||a.paths;c<a.length;c++){var b=a[c],h=b?b.length:0;if(1<h){this._merge(this.transformPt(b[0]),d);for(var f=1;f<h;++f)this._merge(this.transformPt(b[f]),
d)}}};return a}(k);m.EnvDrawHelper=q;k=function(c){function a(a,d){var b=c.call(this,d)||this;b._ctx=a;return b}p(a,c);a.prototype.drawSolidFill=function(a,c){var b=this._ctx;b.fillStyle="rgba("+Math.round(c[0])+","+Math.round(c[1])+","+Math.round(c[2])+","+c[3]/255+")";b.beginPath();for(var d=0,h=a.rings;d<h.length;d++){var f=h[d],g=f?f.length:0;if(2<g){var l=this.transformPt(f[0]);b.moveTo(l[0],l[1]);for(var k=1;k<g;++k)l=this.transformPt(f[k]),b.lineTo(l[0],l[1]);b.closePath()}}b.fill("evenodd")};
a.prototype.drawSolidStroke=function(a,c,k){var b=this._ctx;b.strokeStyle="rgba("+Math.round(c[0])+","+Math.round(c[1])+","+Math.round(c[2])+","+c[3]/255+")";b.lineWidth=this.transformSize(k)+.5;b.beginPath();c=!!a.rings;k=0;for(a=a.rings||a.paths;k<a.length;k++){var d=a[k],f=d?d.length:0;if(1<f){var g=this.transformPt(d[0]);b.moveTo(g[0],g[1]);for(var l=1;l<f;++l)g=this.transformPt(d[l]),b.lineTo(g[0],g[1]);c&&b.closePath()}}b.stroke()};return a}(k);m.CanvasDrawHelper=k});