// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/DisplayRecordStore",["require","exports","dojo/has","./FreeList"],function(l,t,u,m){function v(e){e=e.getStrides();var a={},b;for(b in e)a[n[b]]=e[b];return a}Object.defineProperty(t,"__esModule",{value:!0});var n=["FILL","LINE","MARKER","TEXT"];l=function(){function e(a,b,c){this._strides=a;this._displayList=b;this._vertexAlignments={};this._freeListsAndStorage={};for(var d in a){var e=b=!1;this._freeListsAndStorage[d]={vtxFreeList:c?new m.FreeList(c):
null,idxFreeList:c?new m.FreeList(c):null,vertexBuffers:{},indexBuffer:c?new Uint32Array(c):null};for(var f in a[d])this._freeListsAndStorage[d].vertexBuffers[f]={data:c?new Uint32Array(Math.floor(c*a[d][f]/4)):null,stride:a[d][f]},2===a[d][f]%4?b=!0:0!==a[d][f]%4&&(e=!0);this._vertexAlignments[d]=e?4:b?2:1}}e.fromTileData=function(a){var b=v(a),c=[0,0,0,0],d=[0,0,0,0],r=[];a.tileDisplayData.displayObjectRegistry.forEach(function(a){r.push(a)});for(var f=0;f<r.length;f++)for(var g=0,k=r[f].displayRecords;g<
k.length;g++){var h=k[g];c[h.geometryType]=Math.max(c[h.geometryType],h.vertexFrom+h.vertexCount);d[h.geometryType]=Math.max(d[h.geometryType],h.indexFrom+h.indexCount)}b=new e(b,a.tileDisplayData.displayList,null);for(f=0;f<a.tileBufferData.geometries.length;++f){var g=c[f],p=d[f],h=a.tileBufferData.geometries[f],k=b._storageFor(n[f]),l=a.tileBufferData.geometries[f].indexBuffer;k.indexBuffer=l;k.idxFreeList=new m.FreeList(l.length);k.idxFreeList.allocate(p);var p=void 0,q;for(q in h.vertexBuffer)h=
a.tileBufferData.geometries[f].vertexBuffer[q],k.vertexBuffers[q].data=h.data,k.vertexBuffers[q].stride=h.stride,p=4*h.data.length/h.stride;k.vtxFreeList=new m.FreeList(p);k.vtxFreeList.allocate(g)}return b};e.prototype.delete=function(a){var b=n[a.geometryType];this._freeVertices(b,a.vertexFrom,a.vertexCount);this._freeIndices(b,a.indexFrom,a.indexCount);this._displayList.removeFromList(a);a.vertexFrom=void 0;a.indexFrom=void 0};e.prototype.commit=function(a){var b=n[a.geometryType];if(!a.meshData)return!0;
var c=a.meshData.vertexCount,d=a.meshData.indexData.length,e=a.vertexFrom,f=a.indexFrom,g=0,g=0,k=!1;void 0===a.vertexFrom?(g=this._align(b,c),e=this._allocateVertices(b,g),a.meshData.vertexCount=g,-1!==e&&(a.vertexFrom=e,a.vertexCount=g)):c>a.vertexCount?(this._freeVertices(b,a.vertexFrom,a.vertexCount),g=this._align(b,c),e=this._allocateVertices(b,g),a.meshData.vertexCount=g,-1!==e&&(a.vertexFrom=e,a.vertexCount=g)):c!==a.vertexCount&&(this._freeVertices(b,a.vertexFrom+c,a.vertexCount-c),a.vertexCount=
c);void 0===a.indexFrom?(k=!0,g=d,f=this._allocateIndices(b,g),-1!==f&&(a.indexFrom=f,a.indexCount=g)):d>a.indexCount?(k=!0,this._displayList.removeFromList(a),this._freeIndices(b,a.indexFrom,a.indexCount),g=d,f=this._allocateIndices(b,g),-1!==f&&(a.indexFrom=f,a.indexCount=g)):d!==a.indexCount&&(k=!0,this._displayList.removeFromList(a),this._freeIndices(b,a.indexFrom+d,a.indexCount-d),a.indexCount=d);return-1!==e&&-1!==f?(b=this._storageFor(b),a.writeMeshDataToBuffers(a.vertexFrom,b.vertexBuffers,
a.indexFrom,b.indexBuffer),a.meshData=null,k&&this._displayList.addToList(a),!0):!1};e.prototype._allocateVertices=function(a,b){var c=this._storageFor(a),d=c.vtxFreeList.allocate(b);return-1===d||.5<c.vtxFreeList.fragmentation?-1:d};e.prototype._freeVertices=function(a,b,c){var d=this._storageFor(a);d.vtxFreeList.free(b,c);if(u("esri-feature-tiles-debug"))for(var e in d.vertexBuffers)for(var f=d.vertexBuffers[e].data,g=this._stridesFor(a,e),k=b*g/4,g=c*g/4,h=k;h<k+g;++h)f[h]=0};e.prototype._freeIndices=
function(a,b,c){a=this._storageFor(a);a.idxFreeList.free(b,c);if(u("esri-feature-tiles-debug")){a=a.indexBuffer;for(var d=b;d<b+c;++d)a[d]=0}};e.prototype._align=function(a,b){var c=b%this._vertexAlignments[a];return 0===c?b:b+(this._vertexAlignments[a]-c)};e.prototype._allocateIndices=function(a,b){var c=this._storageFor(a),d=c.idxFreeList.allocate(b);return-1===d||.5<c.idxFreeList.fragmentation?-1:d};e.prototype._storageFor=function(a){return this._freeListsAndStorage[a]};e.prototype._stridesFor=
function(a,b){return this._strides[a][b]};return e}();t.default=l});