// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/mesh","require exports dojo/has ../../../../core/screenUtils ../../../../core/libs/earcut/earcut ../../../../core/libs/libtess/libtess ./color ./enums ./lineMeshUtil ./MeshData ./number ./TileClipper ./Utils ./visualVariablesUtils".split(" "),function(L,M,oa,pa,qa,e,N,ra,qb,Ra,a,rb,Sa,sb){function Ta(p,f,c,r,l,e,q){r=c.slice(r,l);c=p.length/(q.length+1);e=qa(r,e,2);l=e.length;if(0>=l)return 0;for(var n=0;n<r.length;)p.push(a.i1616to32(r[n++],r[n++])),
p.push.apply(p,q);for(p=0;p<l;)f.push(e[p++]+c,e[p++]+c,e[p++]+c)}Object.defineProperty(M,"__esModule",{value:!0});var l=[],O=[],q,tb=function(){function a(){this._indexCounter=this._currentVertexIndex=0;this._triangleIndices=[-1,-1,-1];this.glu=new e.GluTesselator;this.glu.gluTessCallback(e.gluEnum.GLU_TESS_BEGIN,this._begincallback.bind(this));this.glu.gluTessCallback(e.gluEnum.GLU_TESS_VERTEX_DATA,this._vertexCallback.bind(this));this.glu.gluTessCallback(e.gluEnum.GLU_TESS_END,this._endcallback.bind(this));
this.glu.gluTessCallback(e.gluEnum.GLU_TESS_COMBINE,this._combinecallback.bind(this));this.glu.gluTessCallback(e.gluEnum.GLU_TESS_ERROR,this._errorcallback.bind(this));this.glu.gluTessCallback(e.gluEnum.GLU_TESS_EDGE_FLAG,this._edgeCallback.bind(this));this.glu.gluTessProperty(e.gluEnum.GLU_TESS_WINDING_RULE,e.windingRule.GLU_TESS_WINDING_ODD)}a.prototype.beginPolygon=function(a,c){this._triangleIndices[0]=-1;this._triangleIndices[1]=-1;this._triangleIndices[2]=-1;this._indexCounter=this._currentVertexIndex=
0;this.glu.gluTessBeginPolygon(a);this._indices=c};a.prototype.endPolygon=function(){this.glu.gluTessEndPolygon()};a.prototype.beginContour=function(){this.glu.gluTessBeginContour()};a.prototype.endContour=function(){this.glu.gluTessEndContour()};a.prototype.addVertex=function(a,c){this.glu.gluTessVertex(a,c)};a.prototype._vertexCallback=function(a,c){c[c.length]=a[0];c[c.length]=a[1];this._triangleIndices[this._currentVertexIndex]=-1;if(2<=this._currentVertexIndex){for(var f=0;3>f;f++)-1===this._triangleIndices[f]&&
(this._triangleIndices[f]=this._indexCounter++),this._indices[this._indices.length]=this._triangleIndices[f];this._currentVertexIndex=0}else this._currentVertexIndex++};a.prototype._begincallback=function(a){this._triangleIndices[0]=-1;this._triangleIndices[1]=-1;this._triangleIndices[2]=-1;this._currentVertexIndex=0};a.prototype._endcallback=function(){this._currentVertexIndex=0};a.prototype._errorcallback=function(a){};a.prototype._combinecallback=function(a,c,e){return[a[0],a[1],a[2]]};a.prototype._edgeCallback=
function(a){};return a}();L=oa("esri-featurelayer-webgl");var Ua="libtess"===(L&&L.tesselator||"libtess"),t;M.createTextMesh=function(a,f,c,e,l,q,t){return null};M.createMesh=function(e,f,c,r,L,M,oa,n,g){switch(L){case ra.WGLGeometryType.MARKER:var p=new Ra,P,Q,Y,Z,Va=0,Wa=0,I,A,sa,ta,aa,J=f.heatmapInfo;if(J){var Xa=Math.round(f.heatmapInfo.radius);Q=P=0;Z=Y=Xa;I=[1,1,1,1];A=[0,0,0,0];ta=sa=Xa;aa=0}else{var ba=r.spriteMosaicItem;P=Math.round(ba.rect.x/4);Q=Math.round(ba.rect.y/4);Y=P+Math.round(ba.rect.width/
4);Z=Q+Math.round(ba.rect.height/4);var Va=g.xoffset|0,Wa=g.yoffset|0,qa=g.color?g.color:[0,0,0,0];I=Sa.isPictureSymbol(g)?[255,255,255,255]:N.copyAndPremultiply(qa);sa=Math.round(pa.pt2px(g.width||g.size));ta=Math.round(pa.pt2px(g.height||g.size));g.outline?(A=null!=g.outline.color?N.copyAndPremultiply(g.outline.color):[0,0,0,0],aa=null!=g.outline.width?Math.round(pa.pt2px(g.outline.width)):0):(A=[0,0,0,0],aa=0)}var b=[],ca=a.i8888to32(I[0],I[1],I[2],I[3]),da=a.i8888to32(A[0],A[1],A[2],A[3]),ea=
a.i8888to32(sa,ta,aa,0),fa=a.numTo32(e),Ya=0,Za=0,$a=0,ab=0,R=0,S=c.vvColor||c.vvOpacity||c.vvRotation||c.vvSizeMinMaxValue||c.vvSizeScaleStops||c.vvSizeFieldStops||c.vvSizeUnitValue;if(S){var x=f.vvFields,ua=x.rotation?f.getValue(n,x.rotation):0,va=x.opacity?f.getValue(n,x.opacity):0,wa=x.color?f.getValue(n,x.color):0,T=x.size&&!c.vvSizeScaleStops?f.getValue(n,x.size):0;c.vvSizeUnitValue&&(T=sb.getVisualVariableSizeValueRepresentationRatio(T,f.vvRanges.size.unitValue.valueRepresentation));isNaN(T)&&
(T=1);isNaN(ua)&&(ua=1);isNaN(va)&&(va=1);isNaN(wa)&&(wa=1);Ya=a.toUint32(T);Za=a.toUint32(va);$a=a.toUint32(ua);ab=a.toUint32(wa)}var ga=[Ya,ab,Za,$a];J&&(R=a.toUint32(f.heatmapInfo.getIntensity(n)));var B=n.centroid||n.geometry,C;switch(M){case "esriGeometryPoint":C=[[B.x,B.y]];break;case "esriGeometryMultipoint":C=B.points;break;case "esriGeometryPolyline":C=B.paths[0];break;case "esriGeometryPolygon":C=n.centroid?[[B.x,B.y]]:B.rings[0]}for(var y=0,D,xa=0,ya=0,E=Array(4*C.length),ha=0;ha<C.length;ha++){var bb=
C[ha],cb=bb[0],db=bb[1],ia=a.i1616to32(cb+xa+Va,db+ya+Wa),xa=xa+cb,ya=ya+db;b.push(ia);b.push(a.i8888to32(-32,-32,P,Q));b.push(fa);b.push(ca);b.push(da);b.push(ea);S?b.push.apply(b,ga):J&&b.push(R);b.push(ia);b.push(a.i8888to32(32,-32,Y,Q));b.push(fa);b.push(ca);b.push(da);b.push(ea);S?b.push.apply(b,ga):J&&b.push(R);b.push(ia);b.push(a.i8888to32(-32,32,P,Z));b.push(fa);b.push(ca);b.push(da);b.push(ea);S?b.push.apply(b,ga):J&&b.push(R);b.push(ia);b.push(a.i8888to32(32,32,Y,Z));b.push(fa);b.push(ca);
b.push(da);b.push(ea);S?b.push.apply(b,ga):J&&b.push(R);D=6*ha;E[D+0]=y+0;E[D+1]=y+1;E[D+2]=y+2;E[D+3]=y+1;E[D+4]=y+3;E[D+5]=y+2;y+=4}p.update({geometry:b},y,E);return p;case ra.WGLGeometryType.FILL:var za;a:{var ja=null!=r?r.spriteMosaicItem:null,Aa=n.geometry,eb=Sa.isPictureSymbol(g),fb;fb=eb?N.premultiplyAlphaUint32(N.white):g.color?N.premultiplyAlphaUint32(g.color):0;var ub=c.vvColor||c.vvOpacity,gb=new Ra,Ba=0,Ca=0,Da=0,Ea=0;if(ja)var hb=ja.rect,ib=hb.x,jb=hb.y,vb=ja.width,wb=ja.height,Ba=ib+
1,Ca=jb+1,Da=ib+1+vb,Ea=jb+1+wb;var xb=eb&&g.width&&g.height?a.i8888to32(a.nextHighestPowerOfTwo(g.width),a.nextHighestPowerOfTwo(g.height),0,0):a.i8888to32(a.nextHighestPowerOfTwo(Da-Ba),a.nextHighestPowerOfTwo(Ea-Ca),0,0),U=[a.numTo32(e),fb,a.i1616to32(Ba,Ca),a.i1616to32(Da,Ea),xb];if(ub){var ka=f.vvFields,Fa=ka.opacity?f.getValue(n,ka.opacity):0,Ga=ka.color?f.getValue(n,ka.color):0;isNaN(Fa)&&(Fa=1);isNaN(Ga)&&(Ga=1);U.push(a.toUint32(Ga),a.toUint32(Fa))}for(var z=!1,Ha=0,kb=Aa.rings;Ha<kb.length;Ha++){var d=
kb[Ha],V=d.length;if(!(3>V)){var W=d[0][0],X=d[0][1];if(-8>W||520<W||-8>X||520<X){z=!0;break}for(var h=1;h<V;++h)if(W+=d[h][0],X+=d[h][1],-8>W||520<W||-8>X||520<X){z=!0;break}if(z)break}}var K,m,k;if(z){q||(q=new rb.TileClipper(0,0,0,1,8),q.setExtent(512));q.reset(3);for(var Ia=0,lb=Aa.rings;Ia<lb.length;Ia++)if(d=lb[Ia],V=d.length,!(3>V)){m=d[0][0];k=d[0][1];q.moveTo(m,k);for(h=1;h<V;++h)m+=d[h][0],k+=d[h][1],q.lineTo(m,k);q.close()}K={rings:q.result(!Ua)};if(!K.rings||0===K.rings.length){za=null;
break a}}else K=Aa;var F=[],la=[],u,v;if(Ua){t||(t=new tb);t.beginPolygon(l,la);for(var Ja=0,mb=K.rings;Ja<mb.length;Ja++)if(d=mb[Ja],!(3>d.length)){t.beginContour();u=v=0;z?(m=d[0].x,k=d[0].y):(Ka=d[0],m=Ka[0],k=Ka[1]);var nb=[m,k,0];t.addVertex(nb,nb);for(h=1;h<d.length-1;h++){z?(m=d[h].x,k=d[h].y):(La=d[h],u=La[0],v=La[1],m+=u,k+=v);var ob=[m,k,0];t.addVertex(ob,ob)}t.endContour()}t.endPolygon();for(var ma=0;ma<l.length;ma+=2)F.push(a.i1616to32(l[ma],l[ma+1])),F.push.apply(F,U)}else{for(var G=
0,w=0,Ma=void 0,Na=void 0,Oa=0,pb=K.rings;Oa<pb.length;Oa++){var d=pb[Oa],H=w;z?(m=d[0].x,k=d[0].y):(Pa=d[0],m=Pa[0],k=Pa[1]);l[w++]=m;l[w++]=k;var na=0;u=v=0;for(h=1;h<d.length;++h)z?(Ma=d[h].x,Na=d[h].y,u=Ma-m,v=Na-k,na-=u*(k+k+v),m=Ma,k=Na):(Qa=d[h],u=Qa[0],v=Qa[1],na-=u*(k+k+v),m+=u,k+=v),l[w++]=m,l[w++]=k;0<na?(0<H-G&&(Ta(F,la,l,G,H,O,U),G=H),O.length=0):0>na?0<H-G?O.push(.5*(H-G)):w=H:w=H}0<w-G&&Ta(F,la,l,G,w,O,U)}l.length=O.length=0;gb.update({geometry:F},F.length/(U.length+1),la);za=gb;break a;
var Ka,La,Pa,Qa}return za;case ra.WGLGeometryType.LINE:return qb.createLineMeshData(e,f,c,r,oa,n,g)}return null}});