// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/SDFHelper",["require","exports","./Geometry","./Rect"],function(E,D,G,H){function w(b){return b-Math.floor(b)}function F(b,a,c){0>b?b=0:.9999991<b&&(b=.9999991);var f=w(b*z[0]),d=w(b*z[1]),u=w(b*z[2]);b=w(b*z[3]);a[c+0]=256*(f-f*C[0]);a[c+1]=256*(d-f*C[1]);a[c+2]=256*(u-d*C[2]);a[c+3]=256*(b-u*C[3])}Object.defineProperty(D,"__esModule",{value:!0});var z=[16777216,65536,256,1],C=[0,1/256,1/256,1/256];D.packFloat=F;E=function(){function b(){}b.checkSDF=
function(a){return!0};b.prototype._extractGeometry=function(a){if(!a)return null;a=a.symbolLayers;if(!a||1!==a.length)return null;a=a[0];if(!a)return null;a=a.markerGraphics;if(!a||1!==a.length)return null;a=a[0];if(!a)return null;var c=a.geometry;if(!c||!c.rings)return null;a=[];for(var f=0,c=c.rings;f<c.length;f++){for(var d=[],u=0,k=c[f];u<k.length;u++){var b=k[u];d.push(new G.Point(b[0],b[1]))}a.push(d)}return a};b.prototype._getEnvelope=function(a){for(var c=Infinity,f=-Infinity,d=Infinity,b=
-Infinity,k=0;k<a.length;k++)for(var p=0,h=a[k];p<h.length;p++){var l=h[p];l.x<c&&(c=l.x);l.x>f&&(f=l.x);l.y<d&&(d=l.y);l.y>b&&(b=l.y)}return new H(c,d,f-c,b-d)};b.prototype.buildSDF=function(a){a=this._extractGeometry(a);if(!a)return null;var c=this._getEnvelope(a);if(0>=c.width||0>=c.height)return null;for(var f=Math.floor(31.5),d=(128-2*(f+0+1))/Math.max(c.width,c.height),b=Math.round(c.width*d),k=Math.round(c.height*d),p=b+2*f,h=k+2*f,l=0;l<a.length;l++)for(var q=0,g=a[l];q<g.length;q++){var e=
g[q];e.x-=c.x;e.y-=c.y;e.x*=d;e.y*=d;e.x+=f-.5;e.y+=f-.5}c=this._dist_map(a,p,h,f);this._sign_dist_map(a,p,h,f,c);return[this._encodeDistMap(c,f),p,h,b,k,d]};b.prototype._dist_map=function(a,c,b,d){for(var f=c*b,k=new Float32Array(f),p=d*d+1,h=0;h<f;++h)k[h]=p;for(p=0;p<a.length;p++)for(var l=a[p],q=l.length,h=1;h<q;++h){var g=l[h-1],e=l[h],r=void 0,m=void 0;g.x<e.x?(r=g.x,m=e.x):(r=e.x,m=g.x);var t=void 0,v=void 0;g.y<e.y?(t=g.y,v=e.y):(t=e.y,v=g.y);var n=Math.floor(r)-d,m=Math.floor(m)+d,t=Math.floor(t)-
d,v=Math.floor(v)+d;0>n&&(n=0);m>c&&(m=c);0>t&&(t=0);v>b&&(v=b);for(var r=e.x-g.x,w=e.y-g.y,z=r*r+w*w;n<m;n++)for(var A=t;A<v;A++){var x=(n-g.x)*r+(A-g.y)*w,y=void 0,B=void 0;0>x?(y=g.x,B=g.y):x>z?(y=e.x,B=e.y):(x/=z,y=g.x+x*r,B=g.y+x*w);x=(n-y)*(n-y)+(A-B)*(A-B);y=(b-A-1)*c+n;x<k[y]&&(k[y]=x)}}for(h=0;h<f;++h)k[h]=Math.sqrt(k[h]);return k};b.prototype._sign_dist_map=function(a,c,b,d,u){for(var f=0;f<a.length;f++)for(var p=a[f],h=p.length,l=1;l<h;++l){var q=p[l-1],g=p[l],e=void 0,r=void 0;q.x<g.x?
(e=q.x,r=g.x):(e=g.x,r=q.x);var m=void 0,t=void 0;q.y<g.y?(m=q.y,t=g.y):(m=g.y,t=q.y);e=Math.floor(e);r=Math.floor(r)+1;m=Math.floor(m);t=Math.floor(t)+1;e<d&&(e=d);r>c-d&&(r=c-d);m<d&&(m=d);for(t>b-d&&(t=b-d);m<t;++m)if(q.y>m!==g.y>m){for(var v=(b-m-1)*c,n=e;n<r;++n)n<(g.x-q.x)*(m-q.y)/(g.y-q.y)+q.x&&(u[v+n]=-u[v+n]);for(n=d;n<e;++n)u[v+n]=-u[v+n]}}};b.prototype._encodeDistMap=function(a,b){for(var c=2*b,d=a.length,u=new Uint8Array(4*d),k=0;k<d;++k)F(.5-a[k]/c,u,4*k);return u};return b}();D.SDFHelper=
E});