// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/TileClipper",["require","exports","./Geometry","./GeometryUtils"],function(v,y,n,w){Object.defineProperty(y,"__esModule",{value:!0});var x=function(){return function(d,a,b){this.ratio=d;this.x=a;this.y=b}}();v=function(){function d(a,b,e,c,k){void 0===c&&(c=8);void 0===k&&(k=8);this.lines=[];this.starts=[];this.pixelRatio=c;this.pixelMargin=k;this.tileSize=512*c;this.dz=a;this.yPos=b;this.xPos=e}d.prototype.setExtent=function(a){this.finalRatio=
this.tileSize/a*(1<<this.dz);var b=this.pixelRatio*this.pixelMargin,b=b/this.finalRatio;a>>=this.dz;b>a&&(b=a);this.margin=b;this.xmin=a*this.xPos-b;this.ymin=a*this.yPos-b;this.xmax=this.xmin+a+2*b;this.ymax=this.ymin+a+2*b};d.prototype.reset=function(a){this.type=a;this.lines=[];this.starts=[];this.line=null;this.start=0};d.prototype.moveTo=function(a,b){this._pushLine();this._prevIsIn=this._isIn(a,b);this._moveTo(a,b,this._prevIsIn);this._prevPt=new n.Point(a,b);this._firstPt=new n.Point(a,b);
this._dist=0};d.prototype.lineTo=function(a,b){var e=this._isIn(a,b),c=new n.Point(a,b),k=n.Point.distance(this._prevPt,c),g,f,l,d,m;if(e)this._prevIsIn?this._lineTo(a,b,!0):(g=this._prevPt,f=c,l=this._intersect(f,g),this.start=this._dist+k*(1-this._r),this._lineTo(l.x,l.y,!0),this._lineTo(f.x,f.y,!0));else if(this._prevIsIn)f=this._prevPt,g=c,l=this._intersect(f,g),this._lineTo(l.x,l.y,!0),this._lineTo(g.x,g.y,!1);else{var h=this._prevPt;if(!(h.x<=this.xmin&&c.x<=this.xmin||h.x>=this.xmax&&c.x>=
this.xmax||h.y<=this.ymin&&c.y<=this.ymin||h.y>=this.ymax&&c.y>=this.ymax)){g=[];if(h.x<this.xmin&&c.x>this.xmin||h.x>this.xmin&&c.x<this.xmin)f=(this.xmin-h.x)/(c.x-h.x),m=h.y+f*(c.y-h.y),m<=this.ymin?d=!1:m>=this.ymax?d=!0:g.push(new x(f,this.xmin,m));if(h.x<this.xmax&&c.x>this.xmax||h.x>this.xmax&&c.x<this.xmax)f=(this.xmax-h.x)/(c.x-h.x),m=h.y+f*(c.y-h.y),m<=this.ymin?d=!1:m>=this.ymax?d=!0:g.push(new x(f,this.xmax,m));if(h.y<this.ymin&&c.y>this.ymin||h.y>this.ymin&&c.y<this.ymin)f=(this.ymin-
h.y)/(c.y-h.y),m=h.x+f*(c.x-h.x),m<=this.xmin?l=!1:m>=this.xmax?l=!0:g.push(new x(f,m,this.ymin));if(h.y<this.ymax&&c.y>this.ymax||h.y>this.ymax&&c.y<this.ymax)f=(this.ymax-h.y)/(c.y-h.y),m=h.x+f*(c.x-h.x),m<=this.xmin?l=!1:m>=this.xmax?l=!0:g.push(new x(f,m,this.ymax));if(0===g.length)l?d?this._lineTo(this.xmax,this.ymax,!0):this._lineTo(this.xmax,this.ymin,!0):d?this._lineTo(this.xmin,this.ymax,!0):this._lineTo(this.xmin,this.ymin,!0);else if(1<g.length&&g[0].ratio>g[1].ratio)this.start=this._dist+
k*g[1].ratio,this._lineTo(g[1].x,g[1].y,!0),this._lineTo(g[0].x,g[0].y,!0);else for(this.start=this._dist+k*g[0].ratio,f=0;f<g.length;f++)this._lineTo(g[f].x,g[f].y,!0)}this._lineTo(c.x,c.y,!1)}this._dist+=k;this._prevIsIn=e;this._prevPt=c};d.prototype.close=function(){var a,b;0<this.line.length&&(a=this._firstPt,b=this._prevPt,a.x===b.x&&a.y===b.y||this.lineTo(a.x,a.y),a=this.line,b=a.length,4<=b&&(a[0].x===a[1].x&&a[0].x===a[b-2].x||a[0].y===a[1].y&&a[0].y===a[b-2].y)&&(a.pop(),a[0].x=a[b-2].x,
a[0].y=a[b-2].y))};d.prototype.result=function(a){void 0===a&&(a=!0);this._pushLine();if(0===this.lines.length)return null;3===this.type&&a&&z.simplify(this.tileSize,this.margin*this.finalRatio,this.lines);return this.lines};d.prototype.resultWithStarts=function(){if(2!==this.type)throw Error("Only valid for lines");this._pushLine();var a=this.lines,b=a.length;if(0===b)return null;for(var e=[],c=0;c<b;c++)e.push({line:a[c],start:this.starts[c]||0});return e};d.prototype._isIn=function(a,b){return a>=
this.xmin&&a<=this.xmax&&b>=this.ymin&&b<=this.ymax};d.prototype._intersect=function(a,b){var e,c,k;if(b.x>=this.xmin&&b.x<=this.xmax)c=b.y<=this.ymin?this.ymin:this.ymax,k=(c-a.y)/(b.y-a.y),e=a.x+k*(b.x-a.x);else if(b.y>=this.ymin&&b.y<=this.ymax)e=b.x<=this.xmin?this.xmin:this.xmax,k=(e-a.x)/(b.x-a.x),c=a.y+k*(b.y-a.y);else{c=b.y<=this.ymin?this.ymin:this.ymax;e=b.x<=this.xmin?this.xmin:this.xmax;var g=(e-a.x)/(b.x-a.x),f=(c-a.y)/(b.y-a.y);g<f?(k=g,c=a.y+g*(b.y-a.y)):(k=f,e=a.x+f*(b.x-a.x))}this._r=
k;return new n.Point(e,c)};d.prototype._pushLine=function(){this.line&&(1===this.type?0<this.line.length&&(this.lines.push(this.line),this.starts.push(this.start)):2===this.type?1<this.line.length&&(this.lines.push(this.line),this.starts.push(this.start)):3===this.type&&3<this.line.length&&(this.lines.push(this.line),this.starts.push(this.start)));this.line=[];this.start=0};d.prototype._moveTo=function(a,b,e){3!==this.type?e&&(a=Math.round((a-(this.xmin+this.margin))*this.finalRatio),b=Math.round((b-
(this.ymin+this.margin))*this.finalRatio),this.line.push(new n.Point(a,b))):(e||(a<this.xmin&&(a=this.xmin),a>this.xmax&&(a=this.xmax),b<this.ymin&&(b=this.ymin),b>this.ymax&&(b=this.ymax)),a=Math.round((a-(this.xmin+this.margin))*this.finalRatio),b=Math.round((b-(this.ymin+this.margin))*this.finalRatio),this.line.push(new n.Point(a,b)),this._is_v=this._is_h=!1)};d.prototype._lineTo=function(a,b,e){if(3!==this.type)if(e){a=Math.round((a-(this.xmin+this.margin))*this.finalRatio);b=Math.round((b-(this.ymin+
this.margin))*this.finalRatio);if(0<this.line.length&&(e=this.line[this.line.length-1],e.equals(a,b)))return;this.line.push(new n.Point(a,b))}else this.line&&0<this.line.length&&this._pushLine();else if(e||(a<this.xmin&&(a=this.xmin),a>this.xmax&&(a=this.xmax),b<this.ymin&&(b=this.ymin),b>this.ymax&&(b=this.ymax)),a=Math.round((a-(this.xmin+this.margin))*this.finalRatio),b=Math.round((b-(this.ymin+this.margin))*this.finalRatio),this.line&&0<this.line.length){e=this.line[this.line.length-1];var c=
e.x===a,k=e.y===b;c&&k||(this._is_h&&c?(e.x=a,e.y=b,e=this.line[this.line.length-2],this._is_h=e.x===a,this._is_v=e.y===b):this._is_v&&k?(e.x=a,e.y=b,e=this.line[this.line.length-2],this._is_h=e.x===a,this._is_v=e.y===b):(this.line.push(new n.Point(a,b)),this._is_h=c,this._is_v=k))}else this.line.push(new n.Point(a,b))};return d}();y.TileClipper=v;v=function(){function d(){}d.prototype.setExtent=function(a){this._ratio=4096===a?1:4096/a};d.prototype.reset=function(a){this.type=a;this.lines=[];this.line=
null};d.prototype.moveTo=function(a,b){this.line&&this.lines.push(this.line);this.line=[];var e=this._ratio;this.line.push(new n.Point(Math.round(a*e),Math.round(b*e)))};d.prototype.lineTo=function(a,b){var e=this._ratio;this.line.push(new n.Point(Math.round(a*e),Math.round(b*e)))};d.prototype.close=function(){var a=this.line;a&&!a[0].isEqual(a[a.length-1])&&a.push(a[0])};d.prototype.result=function(){this.line&&this.lines.push(this.line);if(0===this.lines.length)return null;3===this.type&&1!==this._ratio&&
z.simplify(4096,64,this.lines);return this.lines};return d}();y.SimpleBuilder=v;var z=function(){function d(){}d.simplify=function(a,b,e){if(e){var c=-b,k=a+b,g=-b,f=a+b;a=[];b=[];for(var l=e.length,t=0;t<l;++t){var m=e[t];if(m&&!(2>m.length))for(var h=m[0],p=void 0,n=m.length,q=1;q<n;++q)p=m[q],h.x===p.x&&(h.x<=c&&(h.y>p.y?(a.push(t),a.push(q),a.push(0),a.push(-1)):(b.push(t),b.push(q),b.push(0),b.push(-1))),h.x>=k&&(h.y<p.y?(a.push(t),a.push(q),a.push(1),a.push(-1)):(b.push(t),b.push(q),b.push(1),
b.push(-1)))),h.y===p.y&&(h.y<=g&&(h.x<p.x?(a.push(t),a.push(q),a.push(2),a.push(-1)):(b.push(t),b.push(q),b.push(2),b.push(-1))),h.y>=f&&(h.x>p.x?(a.push(t),a.push(q),a.push(3),a.push(-1)):(b.push(t),b.push(q),b.push(3),b.push(-1)))),h=p}0!==a.length&&0!==b.length&&(d.fillParent(e,b,a),d.fillParent(e,a,b),c=[],d.calcDeltas(c,b,a),d.calcDeltas(c,a,b),d.addDeltas(c,e))}};d.fillParent=function(a,b,e){for(var c=e.length,k=b.length,g=0;g<k;g+=4){for(var f=b[g],d=b[g+1],n=b[g+2],m=a[f][d-1],f=a[f][d],
d=8092,h=-1,p=0;p<c;p+=4)if(e[p+2]===n){var u=e[p],q=e[p+1],r=a[u][q-1],u=a[u][q];switch(n){case 0:case 1:w.between(m.y,r.y,u.y)&&w.between(f.y,r.y,u.y)&&(r=Math.abs(u.y-r.y),r<d&&(d=r,h=p));break;case 2:case 3:w.between(m.x,r.x,u.x)&&w.between(f.x,r.x,u.x)&&(r=Math.abs(u.x-r.x),r<d&&(d=r,h=p))}}b[g+3]=h}};d.calcDeltas=function(a,b,e){for(var c=b.length,k=0;k<c;k+=4){var g=d.calcDelta(k,b,e,[]);a.push(b[k]);a.push(b[k+1]);a.push(b[k+2]);a.push(g)}};d.calcDelta=function(a,b,e,c){a=b[a+3];if(-1===a)return 0;
var k=c.length;if(1<k&&c[k-2]===a)return 0;c.push(a);return d.calcDelta(a,e,b,c)+1};d.addDeltas=function(a,b){for(var e=a.length,c=0,d=0;d<e;d+=4){var g=a[d+3];g>c&&(c=g)}for(d=0;d<e;d+=4){var f=b[a[d]],l=a[d+1],g=c-a[d+3];switch(a[d+2]){case 0:f[l-1].x-=g;f[l].x-=g;break;case 1:f[l-1].x+=g;f[l].x+=g;break;case 2:f[l-1].y-=g;f[l].y-=g;break;case 3:f[l-1].y+=g,f[l].y+=g}}e=b.length;for(c=0;c<e;++c)f=b[c],!f||2>f.length||f[f.length-1].x!==f[0].x&&f[f.length-1].y!==f[0].y&&f.push(f[0])};return d}()});