// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/Utils","require exports ../../../../core/screenUtils ./color ./enums ./SymbolProperties".split(" "),function(m,a,p,q,b,x){function k(a){return a.map(function(a){return a.name})}function g(a){for(var c={},e=0;e<a.length;e++){var h=a[e];c[h.name]=h.strideInBytes}return c}function l(a){switch(a){case "esriSMS":return"simple-marker";case "esriPMS":return"picture-marker";case "esriSLS":return"simple-line";case "esriPLS":return"picture-line";case "esriSFS":return"simple-fill";
case "esriPFS":return"picture-fill";case "esriTS":return"text"}return a}function r(a){if(a=l(a.type)){switch(a){case "simple-marker":case "picture-marker":return!0;case "CIMPointSymbol":return!0}return!1}}function t(a){if(a=l(a.type)){switch(a){case "simple-fill":case "picture-fill":return!0;case "CIMPolygonSymbol":return!0}return!1}}function u(a){if(a=l(a.type)){switch(a){case "simple-line":case "picture-line":return!0;case "CIMLineSymbol":return!0}return!1}}function v(a){if(a=l(a.type)){switch(a){case "text":return!0;
case "CIMTextSymbol":return!0}return!1}}function n(a){return a&&a.length||0}function w(a){return"string"===typeof a}Object.defineProperty(a,"__esModule",{value:!0});a.C_HITTEST_SEARCH_SIZE=4;a.C_VBO_GEOMETRY="geometry";a.C_VBO_PERINSTANCE="per_instance";a.C_VBO_PERINSTANCE_VV="per_instance_vv";a.C_VBO_VISIBILITY="visibility";a.C_ICON_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:24,divisor:0}];a.C_ICON_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:40,divisor:0}];a.C_ICON_HEATMAP=[{name:a.C_VBO_GEOMETRY,
strideInBytes:28,divisor:0}];a.C_FILL_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:24,divisor:0}];a.C_FILL_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:32,divisor:0}];a.C_LINE_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:32,divisor:0}];a.C_LINE_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:44,divisor:0}];a.C_TEXT_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:20,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_TEXT_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:36,
divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_ICON_VERTEX_NAMES=k(a.C_ICON_VERTEX_DEF);a.C_ICON_VERTEX_NAMES_VV=k(a.C_ICON_VERTEX_DEF_VV);a.C_FILL_VERTEX_NAMES=k(a.C_FILL_VERTEX_DEF);a.C_FILL_VERTEX_NAMES_VV=k(a.C_FILL_VERTEX_DEF_VV);a.C_LINE_VERTEX_NAMES=k(a.C_LINE_VERTEX_DEF);a.C_LINE_VERTEX_NAMES_VV=k(a.C_LINE_VERTEX_DEF_VV);a.C_TEXT_VERTEX_NAMES=k(a.C_TEXT_VERTEX_DEF);a.C_TEXT_VERTEX_NAMES_VV=k(a.C_TEXT_VERTEX_DEF_VV);a.C_ICON_STRIDE_SPEC=g(a.C_ICON_VERTEX_DEF);a.C_ICON_STRIDE_SPEC_VV=
g(a.C_ICON_VERTEX_DEF_VV);a.C_ICON_STRIDE_SPEC_HEATMAP=g(a.C_ICON_HEATMAP);a.C_FILL_STRIDE_SPEC=g(a.C_FILL_VERTEX_DEF);a.C_FILL_STRIDE_SPEC_VV=g(a.C_FILL_VERTEX_DEF_VV);a.C_LINE_STRIDE_SPEC=g(a.C_LINE_VERTEX_DEF);a.C_LINE_STRIDE_SPEC_VV=g(a.C_LINE_VERTEX_DEF_VV);a.C_TEXT_STRIDE_SPEC=g(a.C_TEXT_VERTEX_DEF);a.C_TEXT_STRIDE_SPEC_VV=g(a.C_TEXT_VERTEX_DEF_VV);a.getStrides=function(c,d,e){void 0===e&&(e=!1);switch(c){case b.WGLGeometryType.MARKER:return d?a.C_ICON_STRIDE_SPEC_VV:e?a.C_ICON_STRIDE_SPEC_HEATMAP:
a.C_ICON_STRIDE_SPEC;case b.WGLGeometryType.FILL:return d?a.C_FILL_STRIDE_SPEC_VV:a.C_FILL_STRIDE_SPEC;case b.WGLGeometryType.LINE:return d?a.C_LINE_STRIDE_SPEC_VV:a.C_LINE_STRIDE_SPEC;case b.WGLGeometryType.TEXT:return d?a.C_TEXT_STRIDE_SPEC_VV:a.C_TEXT_STRIDE_SPEC}return null};a.getSymbolGeometryType=function(a){return r(a)?b.WGLGeometryType.MARKER:u(a)?b.WGLGeometryType.LINE:t(a)?b.WGLGeometryType.FILL:v(a)?b.WGLGeometryType.TEXT:b.WGLGeometryType.UNKNOWN};a.normalizeSymbolType=l;a.isMarkerSymbol=
r;a.isFillSymbol=t;a.isLineSymbol=u;a.isPictureSymbol=function(a){if(a=l(a.type))switch(a){case "picture-marker":case "picture-line":case "picture-fill":return!0}return!1};a.isTextSymbol=v;a.getTextProperties=function(a){return x.TextProperties.pool.acquire(a.color?q.copyAndPremultiply(a.color):[255,255,255,255],a.haloColor?q.copyAndPremultiply(a.haloColor):[255,255,255,255],p.pt2px(a.haloSize),p.pt2px(a.font.size),a.angle*Math.PI/180,a.xoffset/a.font.size,a.yoffset/a.font.size,"left"===a.horizontalAlignment?
0:"right"===a.horizontalAlignment?1:.5,"top"===a.verticalAlignment?0:"bottom"===a.verticalAlignment?1:.5)};a.isSameUniformValue=function(a,d){return!1};a.isSameMaterialInfo=function(a,d){if(a.materialKey!==d.materialKey||n(a.texBindingInfo)!==n(d.texBindingInfo)||n(a.materialParams)!==n(d.materialParams))return!1;for(var c=a.texBindingInfo.length,h=0;h<c;++h){var b=a.texBindingInfo[h],f=d.texBindingInfo[h];if(b.unit!==f.unit||b.pageId!==f.pageId||b.semantic!==f.semantic)return!1}c=a.materialParams.length;
for(h=0;h<c;)return!1;return!0};a.serializeString=function(a,d,e){for(var c=0,b=a.length,f=0;f<b;++f)d&&(d[e+c]=a.charCodeAt(f)),++c;d&&(d[e+c]=0);++c;return c};a.deserializeString=function(a,d,e){var c=0;a.s="";for(var b=!0;b;){var f=d[e+c];++c;0!==f?a.s+=String.fromCharCode(f):b=!1}return c};a.isDefined=function(a){return null!==a&&void 0!==a};a.isNumber=function(a){return"number"===typeof a};a.isString=w;a.isStringOrNull=function(a){return null==a||w(a)};a.lerp=function(a,d,b){return a+(d-a)*b};
m=function(){function a(){this._arr=[];this._addGeometryType=this._addGeometryType.bind(this)}a.prototype._addGeometryType=function(a,c){this._arr.push(c)};a.prototype.getKeys=function(a){this._arr.length=0;a.forEach(this._addGeometryType);return this._arr};return a}();a.KeysGetter=m;m=function(){function a(){this._arr=[];this._addGeometryType=this._addGeometryType.bind(this)}a.prototype._addGeometryType=function(a,b){this._arr.push(a)};a.prototype.getValues=function(a){this._arr.length=0;a.forEach(this._addGeometryType);
return this._arr};return a}();a.ValuesGetter=m});