// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/WGLRendererInfo","require exports ../../../../core/screenUtils ../../../../geometry/support/scaleUtils ../../../../renderers/support/utils ./color ./Utils".split(" "),function(u,v,f,q,r,t,n){function p(e,a){var g=a.length;if(e<a[0].value||1===g)return a[0].size;for(var b=1;b<g;b++)if(e<a[b].value)return a[b-1].size+(e-a[b-1].value)/(a[b].value-a[b-1].value)*(a[b].size-a[b-1].size);return a[g-1].size}return function(){function e(a){this.symbolLevels=
[];this.vvColorValues=new Float32Array(8);this.vvColors=new Float32Array(32);this.vvOpacityValues=new Float32Array(8);this.vvOpacities=new Float32Array(8);this.vvSizeMinMaxValue=new Float32Array(4);this.vvSizeFieldStopsValues=new Float32Array(6);this.vvSizeFieldStopsSizes=new Float32Array(6);this._vvMaterialParameters={vvSizeEnabled:!1,vvColorEnabled:!1,vvRotationEnabled:!1,vvRotationType:"geographic",vvOpacityEnabled:!1};this.symbolLevels.push(0)}Object.defineProperty(e.prototype,"vvMaterialParameters",
{get:function(){return this._vvMaterialParameters},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"heatmapParameters",{get:function(){return this._heatmapParameters},enumerable:!0,configurable:!0});e.prototype.updateHeatmapParameters=function(a){var g=a.blurRadius,b=Math.round(4.5*a.blurRadius),c=2*b+1;this._heatmapParameters||(this._heatmapParameters={radius:g,blurRadius:b,kernelSize:c,refreshIntensityKernel:!0,intensityKernel:null,color:null,maxPixelIntensity:a.maxPixelIntensity,
minPixelIntensity:a.minPixelIntensity});for(var d=this._heatmapParameters,e=a.colorStops,h=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],l=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],m,f=0;16>f;f++){var k=e[Math.min(f,e.length-1)];h[f]=k.ratio;m=4*f;l[m+0]=k.color[0]/255;l[m+1]=k.color[1]/255;l[m+2]=k.color[2]/255;l[m+3]=1<k.color[3]?k.color[3]/255:k.color[3];t.premultiplyAlpha(l,m,!0)}d.color={values:h,colors:l,refreshColorRamp:!0};
1E-6<Math.abs(d.radius-a.radius)&&(d.radius=g,d.blurRadius=b,d.kernelSize=c,d.refreshIntensityKernel=!0);d.maxPixelIntensity=a.maxPixelIntensity;d.minPixelIntensity=a.minPixelIntensity};e.prototype.updateVisualVariables=function(a,e){var b=this._vvMaterialParameters;b.vvOpacityEnabled=!1;b.vvSizeEnabled=!1;b.vvColorEnabled=!1;b.vvRotationEnabled=!1;if(a){var c=a.size;if(c){b.vvSizeEnabled=!0;if(c.minMaxValue){var d=c.minMaxValue,g=void 0,h=void 0;n.isDefined(d.minSize)&&n.isDefined(d.maxSize)&&(n.isNumber(d.minSize)&&
n.isNumber(d.maxSize)?(g=f.pt2px(d.minSize),h=f.pt2px(d.maxSize)):(h=e.scale,g=f.pt2px(p(h,d.minSize.stops)),h=f.pt2px(p(h,d.maxSize.stops))));this.vvSizeMinMaxValue.set([d.minDataValue,d.maxDataValue,g,h])}c.scaleStops&&(this.vvSizeScaleStopsValue=f.pt2px(p(e.scale,c.scaleStops.stops)));c.unitValue&&(this.vvSizeUnitValueToPixelsRatio=q.getMetersPerUnitForSR(e.spatialReference)/r.meterIn[c.unitValue.unit]/e.resolution);c.fieldStops&&(this.vvSizeFieldStopsValues.set(c.fieldStops.values),this.vvSizeFieldStopsSizes.set(c.fieldStops.sizes))}if(c=
a.color)b.vvColorEnabled=!0,this.vvColorValues.set(c.values),this.vvColors.set(c.colors);if(c=a.opacity)b.vvOpacityEnabled=!0,this.vvOpacityValues.set(c.values),this.vvOpacities.set(c.opacities);if(c=a.rotation)b.vvRotationEnabled=!0,b.vvRotationType=c.type}};return e}()});