// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/WGLTile","require exports ../../../../core/tsSupport/extendsHelper ../../../../core/libs/gl-matrix/mat4 ../../../../core/libs/gl-matrix/vec2 ../DisplayObject ./DisplayRecordStore ./enums ./WGLBuffers ./WGLDisplayList ./WGLDisplayObject ./WGLDisplayRecord ../../tiling/TileKey".split(" "),function(B,C,t,u,v,w,p,a,q,x,y,r,z){function A(a,b){return a.sortKey-b.sortKey}var m=new Set;return function(k){function b(c,b){var d=k.call(this)||this;d.tileStatus=
a.TileStatus.INITIALIZED;d._data=null;d.hlDisplayList=null;d._wglBuffers=null;d.coords=[0,0];d.bounds=[0,0,0,0];d.tileTransform={transform:Float32Array[16],displayCoord:Float32Array[2]};d._hasVisualVariables=!1;d.tileTransform.transform=u.create();d.tileTransform.displayCoord=v.create();d.key=z.pool.acquire(c);d.coords[0]=b[0];d.coords[1]=b[3];d.bounds=b;return d}t(b,k);Object.defineProperty(b.prototype,"iconGeometry",{get:function(){return this.getGeometry(a.WGLGeometryType.MARKER)},enumerable:!0,
configurable:!0});Object.defineProperty(b.prototype,"textGeometry",{get:function(){return this.getGeometry(a.WGLGeometryType.TEXT)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"fillGeometry",{get:function(){return this.getGeometry(a.WGLGeometryType.FILL)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"lineGeometry",{get:function(){return this.getGeometry(a.WGLGeometryType.LINE)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"canDisplay",
{get:function(){return!!this.attached&&!!this._data},enumerable:!0,configurable:!0});b.prototype.getGeometry=function(c){return this._wglBuffers&&this._wglBuffers.has(c)?this._wglBuffers.get(c):null};b.prototype.getDisplayList=function(c){switch(c){case a.WGLDrawPhase.HIGHLIGHT:return this.hlDisplayList;default:return this._data&&this._data.tileDisplayData.displayList}};Object.defineProperty(b.prototype,"data",{get:function(){return this._data},enumerable:!0,configurable:!0});b.prototype.setData=
function(c,b,d){d?(this.clear(),this.tileStatus=a.TileStatus.INVALID):c&&c.tileDisplayData?(this._dispRecStore=p.default.fromTileData(c),this._hasVisualVariables=b,this._geometryTypes=[a.WGLGeometryType.FILL,a.WGLGeometryType.LINE,a.WGLGeometryType.MARKER,a.WGLGeometryType.TEXT],this._data=c,this.tileStatus=this.tileStatus===a.TileStatus.READY||this.tileStatus===a.TileStatus.NO_DATA||this.tileStatus===a.TileStatus.INVALID?a.TileStatus.MODIFIED:a.TileStatus.READY):(this.clear(),this.tileStatus=a.TileStatus.NO_DATA)};
b.prototype.patchData=function(c){this._data&&(this.tileStatus=a.TileStatus.MODIFIED,this._patchData(c)||(this._data.reshuffle(),this._dispRecStore=p.default.fromTileData(this._data)),this.requestRender())};b.prototype.commitChanges=function(c){this._data&&this.tileStatus===a.TileStatus.MODIFIED&&(this._wglBuffers&&(35048!==this._wglBuffers.usage&&(this._wglBuffers.dispose(),this._wglBuffers=new q.default(35048)),this._wglBuffers.ensureBuffers(c.context,this._geometryTypes,this._hasVisualVariables),
this._wglBuffers.upload(this._data.tileBufferData,this._geometryTypes,["geometry","visibility"],!0)),this.tileStatus=a.TileStatus.READY)};b.prototype.setVisibility=function(c){if(this._data){m.clear();for(var b=0;b<c.length;b++){var d=c[b],a=this._data.tileDisplayData.displayObjectRegistry.get(d.id);if(a)for(var g=0,a=a.displayRecords;g<a.length;g++){var f=a[g];m.add(f.geometryType);var e=this._data.tileBufferData.geometries[f.geometryType];if(e.vertexBuffer.visibility)for(var e=e.vertexBuffer.visibility,
h=0;h<f.vertexCount;++h)e.data[(f.vertexFrom+h)*e.stride/4]=d.visibility?4294967295:0}}if(this._wglBuffers){var l=[];m.forEach(function(c){l.push(c)});this._wglBuffers.upload(this._data.tileBufferData,l,["visibility"],!1);this.requestRender()}}};b.prototype.clear=function(){this._data=null;this._wglBuffers&&(this._wglBuffers.dispose(),this._wglBuffers=null);this.hlDisplayList&&(this.hlDisplayList=null)};b.prototype.dispose=function(){this.clear()};b.prototype.attach=function(c){if(this.attached||
this.tileStatus===a.TileStatus.INVALID)return!0;if(this.tileStatus===a.TileStatus.INITIALIZED)return!1;this._wglBuffers||(this._wglBuffers=new q.default(35044));this._data&&(this._wglBuffers.ensureBuffers(c.context,this._geometryTypes,this._hasVisualVariables),this._wglBuffers.upload(this._data.tileBufferData,this._geometryTypes,["geometry","visibility"],!0));return!0};b.prototype.detach=function(c){k.prototype.detach.call(this,c)};b.prototype.doRender=function(c){var b=this;this.commitChanges(c);
c.context.setStencilTestEnabled(!0);c.context.setStencilFunction(514,this.stencilRef,255);c.painter.getBrushes(c.drawPhase).forEach(function(d){return d.draw(c,b)})};b.prototype.buildHLList=function(c){var b=this;this.hlDisplayList=new x;c.forEach(function(c){b._addToHLDisplayList(b.hlDisplayList,c)})};b.prototype._addToHLDisplayList=function(c,b){if(this._data){var d=this._data.tileDisplayData.displayObjectRegistry.get(b);if(d){for(var a=[],g=0,d=d.displayRecords;g<d.length;g++){var f=d[g],e=new r;
e.id=f.id;e.geometryType=f.geometryType;e.vertexFrom=f.vertexFrom;e.vertexCount=f.vertexCount;e.indexFrom=f.indexFrom;e.indexCount=f.indexCount;e.materialInfo=f.materialInfo;e.meshData=null;e.symbolLevel=0;e.zOrder=0;a.push(e)}a.sort(A);c.addToList(a)}}};b.prototype._patchData=function(c){for(var b=!0,d=0,a=c.remove||[];d<a.length;d++){var g=a[d],f=this._data.tileDisplayData.displayObjectRegistry.get(g);if(f){this._data.tileDisplayData.displayList.removeFromList(f.displayRecords);m.clear();for(var e=
0,f=f.displayRecords;e<f.length;e++){var h=f[e];m.add(h.geometryType);this._dispRecStore.delete(h)}this._data.tileDisplayData.displayObjectRegistry.delete(g)}}var l=[];c.addOrUpdate.tileDisplayData.displayObjectRegistry.forEach(function(a){l.push(a)});for(d=0;d<l.length;d++){a=l[d];if(f=this._data.tileDisplayData.displayObjectRegistry.get(a.id)){for(g=0;g<f.displayRecords.length;++g)if(e=f.displayRecords[g],h=a.displayRecords[g],g>=a.displayRecords.length||e.geometryType!==h.geometryType||e.symbolLevel!==
h.symbolLevel||e.zOrder!==h.zOrder||e.materialInfo.materialKey!==h.materialInfo.materialKey)this._dispRecStore.delete(f.displayRecords[g]),g<a.displayRecords.length&&(f.displayRecords[g]=void 0);f.displayRecords.length=a.displayRecords.length}else f=new y(a.id),this._data.tileDisplayData.displayObjectRegistry.set(a.id,f);for(g=0;g<a.displayRecords.length;++g){var h=a.displayRecords[g],e=f.displayRecords[g],k=h.geometryType;h.readMeshDataFromBuffers(c.addOrUpdate.tileBufferData.geometries[k].vertexBuffer,
c.addOrUpdate.tileBufferData.geometries[k].indexBuffer);if(e)e.meshData=h.meshData,e.materialInfo=h.materialInfo;else{var e=new r,n;for(n in h)e[n]=h[n];e.vertexFrom=void 0;e.indexFrom=void 0;f.displayRecords[g]=e}b=b&&this._dispRecStore.commit(e)}}return b};return b}(w)});