// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/core/Collection","require exports ./tsSupport/declareExtendsHelper ./tsSupport/decorateHelper dojo/aspect ./Accessor ./ArrayPool ./Evented ./lang ./ObjectPool ./scheduling ./accessorSupport/decorators ./accessorSupport/ensureType".split(" "),function(E,R,I,z,J,K,x,L,M,N,O,q,F){function y(d){return d?d.isInstanceOf&&d.isInstanceOf(G)?!0:!1:!1}function A(d){return d?y(d)?d.toArray():d.length?Array.prototype.slice.apply(d):[]:[]}function B(d){if(d&&d.length)return d[0]}
function H(d,b,l,a){b&&b.forEach(function(c,g,b){d.push(c);H(d,l.call(a,c,g,b),l,a)})}E=function(){function d(){this.target=null;this.defaultPrevented=this.cancellable=!1}d.prototype.preventDefault=function(){this.cancellable&&(this.defaultPrevented=!0)};d.prototype.reset=function(b){this.defaultPrevented=!1;this.item=b};return d}();var P=function(){},l=new N(E,!0,function(d){d.item=null;d.target=null}),p=new Set,t=new Set,u=new Set,C=new Map,Q=0,G=function(d){function b(a){a=d.call(this,a)||this;
a._boundDispatch=a._dispatchColChange.bind(a);a._chgListeners=[];a._notifications=null;a._timer=null;a.length=0;a._items=[];Object.defineProperty(a,"uid",{value:Q++});return a}I(b,d);r=b;b.ofType=function(a){if(!a)return r;if(C.has(a))return C.get(a);var c;if("function"===typeof a)c=a.prototype.declaredClass;else if(a.base)c=a.base.prototype.declaredClass;else for(var g in a.typeMap){var b=a.typeMap[g].prototype.declaredClass;c=c?c+(" | "+b):b}c=r.createSubclass({declaredClass:"esri.core.Collection\x3c"+
c+"\x3e"});g={Type:a,ensureType:"function"===typeof a?F.ensureType(a):F.ensureOneOfType(a)};Object.defineProperty(c.prototype,"itemType",{value:g});C.set(a,c);return c};b.prototype.normalizeCtorArgs=function(a){return a?Array.isArray(a)||y(a)?{items:a}:a:{}};Object.defineProperty(b.prototype,"items",{get:function(){return this._items},set:function(a){this._emitBeforeChanges()||(this._splice.apply(this,[0,this.length].concat(A(a))),this._emitAfterChanges())},enumerable:!0,configurable:!0});b.prototype.on=
function(a,c){var g;Array.isArray(a)?g=a:-1<a.indexOf(",")&&(g=a.split(/\s*,\s*/));if(g){for(var b=[],e=0;e<g.length;e++)b.push(this.on(g[e],c));b.remove=function(){for(var a=0;a<b.length;a++)b[a].remove()};return b}if("change"===a){var h=this._chgListeners,d={removed:!1,callback:c};h.push(d);this._notifications&&this._notifications.push({listeners:h.slice(),items:this._items.slice(),changes:[]});return{remove:function(){this.remove=P;d.removed=!0;h.splice(h.indexOf(d),1)}}}return J.after(this,"on"+
a,c,!0)};b.prototype.hasEventListener=function(a){return"change"===a?0<this._chgListeners.length:this.inherited(arguments)};b.prototype.add=function(a,c){if(this._emitBeforeChanges())return this;var g=this.getNextIndex(c);this._splice(g,0,a);this._emitAfterChanges();return this};b.prototype.addMany=function(a,c){void 0===c&&(c=this._items.length);if(!a||!a.length||this._emitBeforeChanges())return this;var g=this.getNextIndex(c);this._splice.apply(this,[g,0].concat(A(a)));this._emitAfterChanges();
return this};b.prototype.removeAll=function(){if(!this.length||this._emitBeforeChanges())return[];var a=this._splice(0,this.length)||[];this._emitAfterChanges();return a};b.prototype.clone=function(){return this._createNewInstance({items:this._items.map(M.clone)})};b.prototype.concat=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];a=a.map(A);return this._createNewInstance({items:(g=this._items).concat.apply(g,a)});var g};b.prototype.drain=function(a,c){if(this.length&&!this._emitBeforeChanges()){for(var g=
this._splice(0,this.length),b=g.length,e=0;e<b;e++)a.call(c,g[e],e,g);this._emitAfterChanges()}};b.prototype.every=function(a,c){return this._items.every(a,c)};b.prototype.filter=function(a,c){var g;g=2===arguments.length?this._items.filter(a,c):this._items.filter(a);return this._createNewInstance({items:g})};b.prototype.find=function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var g=this._items,b=g.length,e=0;e<b;e++){var h=g[e];if(a.call(c,h,e,g))return h}};b.prototype.findIndex=
function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,w=b.length,e=0;e<w;e++)if(a.call(c,b[e],e,b))return e;return-1};b.prototype.flatten=function(a,c){var b=[];H(b,this,a,c);return new r(b)};b.prototype.forEach=function(a,c){for(var b=this._items,w=b.length,e=0;e<w;e++)a.call(c,b[e],e,b)};b.prototype.getItemAt=function(a){return this._items[a]};b.prototype.getNextIndex=function(a){var c=this.length;a=null==a?c:a;0>a?a=0:a>c&&(a=c);return a};b.prototype.includes=
function(a,c){void 0===c&&(c=0);return arguments.length?-1!==this._items.indexOf(a,c):!1};b.prototype.indexOf=function(a,c){void 0===c&&(c=0);return this._items.indexOf(a,c)};b.prototype.join=function(a){void 0===a&&(a=",");return this._items.join(a)};b.prototype.lastIndexOf=function(a,c){void 0===c&&(c=this.length-1);return this._items.lastIndexOf(a,c)};b.prototype.map=function(a,c){var b=this._items.map(a,c);return new r({items:b})};b.prototype.reorder=function(a,c){void 0===c&&(c=this.length-1);
var b=this.indexOf(a);if(-1!==b){0>c?c=0:c>=this.length&&(c=this.length-1);if(b!==c){if(this._emitBeforeChanges())return a;this._splice(b,1);this._splice(c,0,a);this._emitAfterChanges()}return a}};b.prototype.pop=function(){if(this.length&&!this._emitBeforeChanges()){var a=B(this._splice(this.length-1,1));this._emitAfterChanges();return a}};b.prototype.push=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];if(this._emitBeforeChanges())return this.length;this._splice.apply(this,
[this.length,0].concat(a));this._emitAfterChanges();return this.length};b.prototype.reduce=function(a,c){var b=this._items;return 2===arguments.length?b.reduce(a,c):b.reduce(a)};b.prototype.reduceRight=function(a,c){var b=this._items;return 2===arguments.length?b.reduceRight(a,c):b.reduceRight(a)};b.prototype.remove=function(a){return this.removeAt(this.indexOf(a))};b.prototype.removeAt=function(a){if(!(0>a||a>=this.length||this._emitBeforeChanges()))return a=B(this._splice(a,1)),this._emitAfterChanges(),
a};b.prototype.removeMany=function(a){if(!a||!a.length||this._emitBeforeChanges())return[];a=y(a)?a.toArray():a;for(var c=this._items,b=[],w=a.length,e=0;e<w;e++){var h=c.indexOf(a[e]);if(-1<h){for(var d=e+1,m=h+1,f=Math.min(a.length-d,c.length-m),k=0;k<f&&a[d+k]===c[m+k];)k++;d=1+k;(h=this._splice(h,d))&&0<h.length&&b.push.apply(b,h);e+=d-1}}this._emitAfterChanges();return b};b.prototype.reverse=function(){if(this._emitBeforeChanges())return this;var a=this._splice(0,this.length);a&&(a.reverse(),
this._splice.apply(this,[0,0].concat(a)));this._emitAfterChanges();return this};b.prototype.shift=function(){if(this.length&&!this._emitBeforeChanges()){var a=B(this._splice(0,1));this._emitAfterChanges();return a}};b.prototype.slice=function(a,c){void 0===a&&(a=0);void 0===c&&(c=this.length);return this._createNewInstance({items:this._items.slice(a,c)})};b.prototype.some=function(a,c){return this._items.some(a,c)};b.prototype.sort=function(a){if(!this.length||this._emitBeforeChanges())return this;
var c=this._splice(0,this.length);arguments.length?c.sort(a):c.sort();this._splice.apply(this,[0,0].concat(c));return this};b.prototype.splice=function(a,c){for(var b=[],d=2;d<arguments.length;d++)b[d-2]=arguments[d];if(this._emitBeforeChanges())return[];b=this._splice.apply(this,[a,c].concat(b))||[];this._emitAfterChanges();return b};b.prototype.toArray=function(){return this._items.slice()};b.prototype.toJSON=function(){return this.toArray()};b.prototype.toLocaleString=function(){return this._items.toLocaleString()};
b.prototype.toString=function(){return this._items.toString()};b.prototype.unshift=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];if(this._emitBeforeChanges())return this.length;this._splice.apply(this,[0,0].concat(a));this._emitAfterChanges();return this.length};b.prototype._createNewInstance=function(a){return new this.constructor(a)};b.prototype._splice=function(a,c){for(var b=[],d=2;d<arguments.length;d++)b[d-2]=arguments[d];var d=this._items,e=this.constructor.prototype.itemType,
h,v;!this._notifications&&this.hasEventListener("change")&&(this._notifications=[{listeners:this._chgListeners.slice(),items:this._items.slice(),changes:[]}],this._timer&&this._timer.remove(),this._timer=O.schedule(this._boundDispatch));if(c){v=d.splice(a,c);if(this.hasEventListener("before-remove")){var m=l.acquire();m.target=this;m.cancellable=!0;for(var f=0,k=v.length;f<k;f++)h=v[f],m.reset(h),this.emit("before-remove",m),m.defaultPrevented&&(v.splice(f,1),d.splice(a,0,h),a+=1,--f,--k);l.release(m)}this.length=
this._items.length;if(this.hasEventListener("after-remove")){h=l.acquire();h.target=this;h.cancellable=!1;k=v.length;for(f=0;f<k;f++)h.reset(v[f]),this.emit("after-remove",h);l.release(h)}this._notifyChangeEvent(null,v)}if(b&&b.length){if(e){f=[];for(k=0;k<b.length;k++)h=b[k],m=e.ensureType(h),null==m&&null!=h||f.push(m);b=f}e=this.hasEventListener("before-add");f=this.hasEventListener("after-add");k=a===this.length;if(e||f){h=l.acquire();h.target=this;h.cancellable=!0;m=l.acquire();m.target=this;
m.cancellable=!1;for(var D=0,p=b;D<p.length;D++){var n=p[D];e?(h.reset(n),this.emit("before-add",h),h.defaultPrevented||(k?d.push(n):d.splice(a++,0,n),this._set("length",d.length),f&&(m.reset(n),this.emit("after-add",m)))):(k?d.push(n):d.splice(a++,0,n),this._set("length",d.length),m.reset(n),this.emit("after-add",m))}l.release(h)}else k?d.push.apply(d,b):d.splice.apply(d,[a,0].concat(b)),this._set("length",d.length);this._notifyChangeEvent(b,null)}return v};b.prototype._emitBeforeChanges=function(){var a=
!1;if(this.hasEventListener("before-changes")){var b=l.acquire();b.target=this;b.cancellable=!0;this.emit("before-changes",b);a=b.defaultPrevented;l.release(b)}return a};b.prototype._emitAfterChanges=function(){if(this.hasEventListener("after-changes")){var a=l.acquire();a.target=this;a.cancellable=!1;this.emit("after-changes",a);l.release(a)}};b.prototype._notifyChangeEvent=function(a,b){this.hasEventListener("change")&&this._notifications[this._notifications.length-1].changes.push({added:a,removed:b})};
b.prototype._dispatchColChange=function(){this._timer&&(this._timer.remove(),this._timer=null);if(this._notifications){var a=this._notifications;this._notifications=null;for(var b=function(a){var b=a.changes;p.clear();t.clear();u.clear();for(var c=0;c<b.length;c++){var e=b[c],f=e.added,e=e.removed;if(f)if(0===u.size&&0===t.size)for(var k=0,g=f;k<g.length;k++)f=g[k],p.add(f);else for(k=0,g=f;k<g.length;k++)f=g[k],t.has(f)?(u.add(f),t.delete(f)):u.has(f)||p.add(f);if(e)if(0===u.size&&0===p.size)for(k=
0;k<e.length;k++)f=e[k],t.add(f);else for(k=0;k<e.length;k++)f=e[k],p.has(f)?p.delete(f):(u.delete(f),t.add(f))}var l=x.acquire();p.forEach(function(a){l.push(a)});var n=x.acquire();t.forEach(function(a){n.push(a)});var r=d._items,w=a.items,q=x.acquire();u.forEach(function(a){w.indexOf(a)!==r.indexOf(a)&&q.push(a)});if(a.listeners&&(l.length||n.length||q.length))for(b={target:d,added:l,removed:n,moved:q},c=a.listeners.length,f=0;f<c;f++)e=a.listeners[f],e.removed||e.callback.call(d,b);x.release(l);
x.release(n);x.release(q)},d=this,l=0;l<a.length;l++)b(a[l]);p.clear();t.clear();u.clear()}};b.isCollection=y;z([q.property()],b.prototype,"length",void 0);z([q.property()],b.prototype,"items",null);return b=r=z([q.subclass("esri.core.Collection")],b);var r}(q.declared(K,L));return G});