// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/core/urlUtils",["require","exports","esri/urlUtils","dojo/_base/url"],function(t,e,m,u){function n(a){return m.normalize(a)}function v(a){return"data:"===a.slice(0,5)}function g(a){return r(a)||w.test(a)}function r(a){return a&&"/"===a[0]&&"/"===a[1]}function x(a){return m.urlToObject(a)}function y(a){if("string"===typeof a)return new u(p(a));a.scheme||(a.scheme=e.appUrl.scheme);return a}function z(a){if(v(a))return null;var b=a.indexOf("://");if(-1===b&&r(a))b=2;else if(-1!==
b)b+=3;else return null;b=a.indexOf("/",b);return-1===b?a:a.slice(0,b)}function p(a,b,c){void 0===b&&(b=e.appBaseUrl);if(r(a))return c&&c.preserveProtocolRelative?a:"http"===e.appUrl.scheme&&e.appUrl.authority===z(a).slice(2)?"http:"+a:"https:"+a;if(w.test(a))return a;c=A;if("/"===a[0]){var d=b.indexOf("//"),d=b.indexOf("/",d+2);b=-1===d?b:b.slice(0,d)}return c(b,a)}function B(a,b,c){void 0===c&&(c=!1);a=y(a);b=y(b);return c||a.scheme===b.scheme?a.host.toLowerCase()===b.host.toLowerCase()&&a.port===
b.port:!1}function A(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];if(a&&a.length){b=[];if(g(a[0])){var c=a[0],d=c.indexOf("//");b.push(c.slice(0,d+1));D.test(a[0])&&(b[0]+="/");a[0]=c.slice(d+2)}else"/"===a[0][0]&&b.push("");a=a.reduce(function(a,b){return a.concat(b.split("/"))},[]);for(c=0;c<a.length;c++)d=a[c],".."===d&&0<b.length?b.pop():!d||"."===d&&0!==b.length||b.push(d);return b.join("/")}}function q(a,b,c){if(!(b&&c&&a&&g(a)))return a;var d=a.indexOf("//"),e=a.indexOf("/",
d+2),k=a.indexOf(":",d+2),e=Math.min(0>e?a.length:e,0>k?a.length:k);if(a.slice(d+2,e).toLowerCase()!==b.toLowerCase())return a;b=a.slice(0,d+2);a=a.slice(e);return""+b+c+a}function C(a,b,c){void 0===b&&(b=e.appBaseUrl);if(!g(a))return a;var d=n(a),f=d.toLowerCase();b=n(b).toLowerCase().replace(/\/+$/,"");if((c=c?n(c).toLowerCase().replace(/\/+$/,""):null)&&0!==b.indexOf(c))return a;for(var k=function(a,b,c){c=a.indexOf(b,c);return-1===c?a.length:c},h=k(f,"/",f.indexOf("//")+2),l=-1;f.slice(0,h+1)===
b.slice(0,h)+"/";){l=h+1;if(h===f.length)break;h=k(f,"/",h+1)}if(-1===l||c&&l<c.length)return a;a=d.slice(l);d=b.slice(l-1).replace(/[^/]+/g,"").length;if(0<d)for(f=0;f<d;f++)a="../"+a;else a="./"+a;return a}Object.defineProperty(e,"__esModule",{value:!0});e.normalize=n;e.canUseXhr=function(a){return m.canUseXhr(a)};t=Function("return this")();e.appUrl=new u(t.location);e.appBaseUrl=function(){var a=e.appUrl.path,a=a.substring(0,a.lastIndexOf(a.split("/")[a.split("/").length-1]));return""+(e.appUrl.scheme+
"://"+e.appUrl.host+(null!=e.appUrl.port?":"+e.appUrl.port:""))+a}();var D=/^\s*file:/i,w=/^\s*[a-z][a-z0-9-+.]*:[^0-9]/i;e.isDataProtocol=v;e.isAbsolute=g;e.urlToObject=x;e.getOrigin=z;e.makeAbsolute=p;e.hasSameOrigin=B;e.join=A;e.removeFile=function(a){var b=0;if(g(a)){var c=a.indexOf("//");-1!==c&&(b=c+2)}c=a.lastIndexOf("/");return c<b?a:a.slice(0,c+1)};e.addProxy=function(a){return m.addProxy(a)};e.makeData=function(a){return a.isBase64?"data:"+a.mediaType+";base64,"+a.data:"data:"+a.mediaType+
","+a.data};var E=/^data:(.*?)(;base64)?,(.*)$/;e.dataComponents=function(a){return(a=a.match(E))?{mediaType:a[1],isBase64:!!a[2],data:a[3]}:null};e.changeDomain=q;e.read=function(a,b){var c=b&&b.url&&b.url.path;a&&c&&(a=p(a,c,{preserveProtocolRelative:!0}));var c=a,d=b&&b.portal;if(d&&!d.isPortal&&d.urlKey&&d.customBaseUrl)var f=d.urlKey+"."+d.customBaseUrl,c=B(e.appUrl,e.appUrl.scheme+"://"+f)?q(c,d.portalHostname,f):q(c,f,d.portalHostname);return c};e.write=function(a,b){if(!a)return a;!g(a)&&
b&&b.blockedRelativeUrls&&b.blockedRelativeUrls.push(a);var c=p(a);if(b){var d=b.verifyItemRelativeUrls&&b.verifyItemRelativeUrls.rootPath||b.url&&b.url.path;d&&(c=C(c,d,d),c!==a&&b.verifyItemRelativeUrls&&b.verifyItemRelativeUrls.writtenUrls.push(c))}c=(d=b&&b.portal)&&!d.isPortal&&d.urlKey&&d.customBaseUrl?q(c,d.urlKey+"."+d.customBaseUrl,d.portalHostname):c;return c};e.makeRelative=C;e.removeQueryParameters=function(a){a=x(a);Object.keys(a.query||{});return a.path}});