// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/LineBucket","require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper ../2d/engine/webgl/LineTess ./Bucket ./style/StyleLayer".split(" "),function(u,v,q,w,f,r,t){var k=new f.Tessellator({distanceAlongCorrection:!0});return function(p){function e(a,b,d,c){b=p.call(this,a,b)||this;b.extrudeVectorsDoubleBuffer=[f.allocExtrudeVectors(),f.allocExtrudeVectors()];b.firstExtrudeVectors=f.allocExtrudeVectors();b.recycledTriangleBridge=
f.allocTriangles(20);b.recycledTrianglePie=f.allocTriangles(20);if(a.hasDataDrivenLine!==d.isDataDriven())throw Error("incompatible line buffer");b._lineVertexBuffer=d;b._lineIndexBuffer=c;return b}q(e,p);Object.defineProperty(e.prototype,"lineIndexStart",{get:function(){return this._lineIndexStart},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"lineIndexCount",{get:function(){return this._lineIndexCount},enumerable:!0,configurable:!0});e.prototype.assignBufferInfo=function(a){a._lineIndexStart=
this._lineIndexStart;a._lineIndexCount=this._lineIndexCount};e.prototype.processFeatures=function(a,b){this._lineIndexStart=this._lineIndexBuffer.index;this._lineIndexCount=0;var d=this.layer,c=this.zoom,h=d.hasDataDrivenLine;a&&a.setExtent(this.layerExtent);for(var l=d.getPaintValue("line-pattern",c),g=0,n=this._features;g<n.length;g++){var f=n[g],m=new t.LineLayout(d,c,f),e=void 0;if(h&&(e={color:l?[1,1,1,1]:d.getPaintValue("line-color",c,f),opacity:d.getPaintValue("line-opacity",c,f),size:Math.max(Math.min(d.getPaintValue("line-width",
c,f),256),0)},0>=e.size||0>=e.opacity||0>=e.color[3]))continue;f=f.getGeometry(a);this._processFeature(m,f,e)}};e.prototype._processFeature=function(a,b,d){if(b)for(var c=b.length,h=0;h<c;h++)this._processGeometry(b[h],a,d)};e.prototype._processGeometry=function(a,b,d){if(!(2>a.length)){for(var c=a[0],h=a[a.length-1],l=h.x-c.x,h=h.y-c.y,c=1E-6>l*l+h*h,g=a[0],n=1;n<a.length;)l=a[n].x-g.x,h=a[n].y-g.y,1E-6>l*l+h*h?a.splice(n,1):(g=a[n],++n);if(!(2>a.length)){this.vertices=a;this.verticesLen=a.length;
this.isClosed=c;this.cap=b.cap;this.join=b.join;this.almostParallelRads=.05;this.veryShallowRads=.1;this.miterSafeRads=f.MITER_SAFE_RADS;this.miterLimitMag=Math.min(b.miterLimit,f.SYSTEM_MAG_LIMIT);this.roundLimitRads=Math.min(b.roundLimit,.5);this.newRoundJoinsSafeRads=2.3;b=this._lineIndexBuffer.index;for(var l=0,e=void 0,h=this.verticesLen,g=0;g<h;++g){var n=a[g],m=a[(g+h-1)%h],k=c&&this._isClipEdge(m,n),m=e===this.extrudeVectorsDoubleBuffer[g%2]?this.extrudeVectorsDoubleBuffer[(g+1)%2]:this.extrudeVectorsDoubleBuffer[g%
2];g<h-1||!c||this.hasPattern?(this._computeExtrudeVectors(m,g),this._writeGPUVertices(n.x,n.y,l,m,d),!m.capCenter||c&&g===h-1||this._writeGPUPieElements(m,k),c&&0===g&&!this.hasPattern&&f.copyExtrudeVectors(this.firstExtrudeVectors,m)):f.copyExtrudeVectors(m,this.firstExtrudeVectors);e&&this._writeGPUBridgeElements(e,m,k);g<h-1&&(e=a[g+1],n=f.length([e.x-n.x,e.y-n.y]),l+=n);e=m}this._lineIndexCount+=3*(this._lineIndexBuffer.index-b)}}};e.prototype._computeExtrudeVectors=function(a,b){var d=this.vertices,
c=this.verticesLen,h=this.isClosed,l=d[b],g=[void 0,void 0],e=[void 0,void 0];if(0<b&&b<c-1){var k=d[(b+c-1)%c],m=d[(b+1)%c];f.normalize(g,[l.x-k.x,l.y-k.y]);f.normalize(e,[m.x-l.x,m.y-l.y])}else if(0===b)m=d[(b+1)%c],f.normalize(e,[m.x-l.x,m.y-l.y]),h?(d=d[c-2],f.normalize(g,[l.x-d.x,l.y-d.y])):g=e;else if(b===c-1)k=d[(b+c-1)%c],f.normalize(g,[l.x-k.x,l.y-k.y]),h?(d=d[1],f.normalize(e,[d.x-l.x,d.y-l.y])):e=g;else{console.error("Vertex index 'i' out of range.");return}h||0!==b?h||b!==c-1?this._computeJoinExtrudeVectors(a,
g,e):this._computeCapExtrudeVectors(a,g,e,f.CapPosition.END):this._computeCapExtrudeVectors(a,g,e,f.CapPosition.START)};e.prototype._computeCapExtrudeVectors=function(a,b,d,c){0===this.cap?k.buttCap(a,b,d):1===this.cap?k.roundCap(a,b,d,c,f.getNumberOfSlices(Math.PI),c===f.CapPosition.START?-1:1):2===this.cap?k.squareCap(a,b,d,c):k.buttCap(a,b,d)};e.prototype._computeJoinExtrudeVectors=function(a,b,d){var c=f.getRads(b,d);if(c>Math.PI-this.almostParallelRads)k.rectJoin(a,b,d);else if(0===this.join&&
c>=this.veryShallowRads)k.bevelJoin(a,b,d,1);else if(1===this.join&&c>=this.veryShallowRads){var e=f.getNumberOfSlices(c);c<this.newRoundJoinsSafeRads?2>e||c<this.roundLimitRads?k.bevelJoin(a,b,d,1):k.roundJoin(a,b,d,e):k.unitRoundJoin(a,b,d,e)}else c<this.almostParallelRads?k.fastMiterJoin(a,b,d):c<this.miterSafeRads?k.miterJoin(a,b,d):k.bevelJoin(a,b,d,this.miterLimitMag)};e.prototype._writeGPUVertices=function(a,b,d,c,e){for(var f=0;f<c.vectors.count;++f){var g=c.vectors.items[f].vector[0],h=c.vectors.items[f].vector[1],
k=c.vectors.items[f].texCoords[0],m=c.vectors.items[f].texCoords[1];c.vectors.items[f].base=this._lineVertexBuffer.index;this._lineVertexBuffer.add(a,b,g,h,k,m,d,e)}};e.prototype._writeGPUBridgeElements=function(a,b,d){k.bridge(this.recycledTriangleBridge,a,b);if(!d)for(a=0;a<this.recycledTriangleBridge.count;++a)b=this.recycledTriangleBridge.items[a],this._lineIndexBuffer.add(b.v1.base,b.v2.base,b.v3.base)};e.prototype._writeGPUPieElements=function(a,b){k.pie(this.recycledTrianglePie,a);if(!b)for(var d=
0;d<this.recycledTrianglePie.count;++d){var c=this.recycledTrianglePie.items[d];this._lineIndexBuffer.add(c.v1.base,c.v2.base,c.v3.base)}};e.prototype._isClipEdge=function(a,b){return a.x===b.x?-64>=a.x||4160<=a.x:a.y===b.y?-64>=a.y||4160<=a.y:!1};return e}(r)});