// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/SpriteMosaic","require exports ./GeometryUtils ./Rect ./RectangleBinPack ../webgl/Texture".split(" "),function(u,v,q,r,l,t){return function(){function e(b,c,a){void 0===a&&(a=0);this._size=[];this._mosaicsData=[];this._textures=[];this._dirties=[];this._pageHeight=this._pageWidth=this._currentPage=this._maxItemSize=0;this._mosaicRects={};this.pixelRatio=1;(0>=b||0>=c)&&console.error("Sprites mosaic defaultWidth and defaultHeight must be greater than zero!");
this._pageWidth=b;this._pageHeight=c;0<a&&(this._maxItemSize=a);this._binPack=new l(b-4,c-4)}e.prototype.getWidth=function(b){return b>=this._size.length?-1:this._size[b][0]};e.prototype.getHeight=function(b){return b>=this._size.length?-1:this._size[b][1]};e.prototype.setSpriteSource=function(b){this.dispose();this.pixelRatio=b.devicePixelRatio;if(0===this._mosaicsData.length){this._binPack=new l(this._pageWidth-4,this._pageHeight-4);var c=new Uint32Array(Math.floor(this._pageWidth)*Math.floor(this._pageHeight));
this._mosaicsData[0]=c;this._dirties.push(!0);this._size.push([this._pageWidth,this._pageHeight]);this._textures.push(void 0)}this._sprites=b};e.prototype.getSpriteItem=function(b,c){void 0===c&&(c=!1);var a=this._mosaicRects[b];if(a)return a;if(!this._sprites||"loaded"!==this._sprites.loadStatus)return null;a=this._sprites.getSpriteInfo(b);if(!a||!a.width||!a.height||0>a.width||0>a.height)return null;var d=a.width,e=a.height,h=this._allocateImage(d,e),g=h[0],f=h[1];if(0>=g.width)return null;this._copy(g,
a,f,h[2],c);a={rect:g,width:d,height:e,anchorX:0,anchorY:0,sdf:a.sdf,pixelRatio:a.pixelRatio,page:f};return this._mosaicRects[b]=a};e.prototype.preloadSpriteItems=function(){for(var b=0,c=this._sprites.spriteNames;b<c.length;b++)this.getSpriteItem(c[b],!0)};e.prototype.getSpriteItems=function(b){for(var c={},a=0;a<b.length;a++){var d=b[a];c[d]=this.getSpriteItem(d)}return c};e.prototype.getMosaicItemPosition=function(b,c){var a=this.getSpriteItem(b,c),d=a&&a.rect;if(!d)return null;d.width=a.width;
d.height=a.height;return{size:[a.width,a.height],tl:[(d.x+2)/this._size[a.page][0],(d.y+2)/this._size[a.page][1]],br:[(d.x+2+a.width)/this._size[a.page][0],(d.y+2+a.height)/this._size[a.page][1]],page:a.page}};e.prototype.bind=function(b,c,a,d){void 0===a&&(a=0);void 0===d&&(d=0);this._textures[a]||(this._textures[a]=new t(b,{pixelFormat:6408,dataType:5121,width:this._size[a][0],height:this._size[a][1]},new Uint8Array(this._mosaicsData[a].buffer)));var e=this._textures[a];e.setSamplingMode(c);this._dirties[a]&&
e.setData(new Uint8Array(this._mosaicsData[a].buffer));b.bindTexture(e,d);this._dirties[a]=!1};e._copyBits=function(b,c,a,d,e,h,g,f,m,n,k){var p=d*c+a;g=f*h+g;if(k)for(g-=h,k=-1;k<=n;k++,p=((k+n)%n+d)*c+a,g+=h)for(f=-1;f<=m;f++)e[g+f]=b[p+(f+m)%m];else for(k=0;k<n;k++){for(f=0;f<m;f++)e[g+f]=b[p+f];p+=c;g+=h}};e.prototype._copy=function(b,c,a,d,l,h){if(this._sprites&&"loaded"===this._sprites.loadStatus&&!(a>=this._mosaicsData.length)){var g=new Uint32Array(h?h.buffer:this._sprites.image.buffer),f=
this._mosaicsData[a];f&&g||console.error("Source or target images are uninitialized!");e._copyBits(g,h?c.width:this._sprites.width,c.x,c.y,f,d[0],b.x+2,b.y+2,c.width,c.height,l);this._dirties[a]=!0}};e.prototype._allocateImage=function(b,c){b+=2;c+=2;var a=Math.max(b,c);if(this._maxItemSize&&this._maxItemSize<a){var a=Math.pow(2,Math.ceil(q.log2(b))),d=Math.pow(2,Math.ceil(q.log2(c))),e=new r(0,0,b,c);this._mosaicsData.push(new Uint32Array(a*d));this._dirties.push(!0);this._size.push([a,d]);this._textures.push(void 0);
return[e,this._mosaicsData.length-1,[a,d]]}a=b%4?4-b%4:4;d=c%4?4-c%4:4;1===a&&(a=5);1===d&&(d=5);a=this._binPack.allocate(b+a,c+d);return 0>=a.width?(this._dirties[this._currentPage]||(this._mosaicsData[this._currentPage]=null),this._currentPage=this._mosaicsData.length,this._mosaicsData.push(new Uint32Array(this._pageWidth*this._pageHeight)),this._dirties.push(!0),this._size.push([this._pageWidth,this._pageHeight]),this._textures.push(void 0),this._binPack=new l(this._pageWidth-4,this._pageHeight-
4),this._allocateImage(b,c)):[a,this._currentPage,[this._pageWidth,this._pageHeight]]};e.prototype.dispose=function(){this._binPack=null;this._mosaicRects={};for(var b=0,c=this._textures;b<c.length;b++){var a=c[b];a&&a.dispose()}this._textures.length=0};return e}()});