// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/TileHandler","require exports dojo/Deferred dojo/has dojo/promise/all ../../request ../../core/LRUCache ../../core/promiseUtils ../../core/requireUtils ../../core/workers ../2d/tiling/TileKey ./GeometryUtils ./GlyphMosaic ./GlyphSource ./SpriteMosaic ./SpriteSource ./TileIndex ./VectorTileDisplayObject module".split(" "),function(u,G,v,w,q,r,x,f,y,z,l,t,A,B,C,D,m,E,F){var n=new x(10),k=new Map;return function(){function b(a,c,e,d,b){void 0===d&&(d=
!1);this.devicePixelRatio=e;this.allowUpdates=d;this._tileIndex=this._connection=this._glyphMosaic=this._spriteMosaic=null;this._updateQueue=new Map;this._ongoingRequests=new Map;this._vectorTileLayer=a;this._styleRepository=a.styleRepository;this._requestUpdate=c}b.prototype.destroy=function(){this.stop();this._vectorTileLayer=this._requestUpdate=this._styleRepository=null;this._spriteMosaic&&(this._spriteMosaic.dispose(),this._spriteMosaic=null);this._glyphMosaic&&(this._glyphMosaic.dispose(),this._glyphMosaic=
null)};Object.defineProperty(b.prototype,"initialized",{get:function(){return this._broadcastPromise&&this._broadcastPromise.isFulfilled()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"spriteMosaic",{get:function(){return this._spriteMosaic},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"glyphMosaic",{get:function(){return this._glyphMosaic},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"ongoingRequestCount",{get:function(){return this._ongoingRequests.size},
enumerable:!0,configurable:!0});b.prototype.start=function(){var a=this;this.stop();var c=this._styleRepository,e=new D(c.sprite,this.devicePixelRatio);e.devicePixelRatio=this.devicePixelRatio;var d=e.load().then(function(){a._spriteMosaic=new C(1024,1024,250);a._spriteMosaic.setSpriteSource(e);w("stable-symbol-rendering")&&a._spriteMosaic.preloadSpriteItems()}),b=new B(c.glyphs);this._glyphMosaic=new A(1024,1024,b);var g=this._fetchTileMap(this._vectorTileLayer.tileIndexUrl),p=z.open(y.getAbsMid("./WorkerTileHandler",
u,F),{client:this}).then(function(c){a._connection=c}),f=new v(function(a){d.isFulfilled()||d.cancel();g.isFulfilled()||g.cancel();p.isFulfilled()||p.cancel()});q([d,g,p]).then(function(d){q(a._connection.broadcast("setLayers",c.styleJSON)).then(function(){f.resolve()})});return this._broadcastPromise=f.promise};b.prototype.stop=function(){this._broadcastPromise&&!this._broadcastPromise.isFulfilled()&&this._broadcastPromise.cancel();this._updateQueue.forEach(function(a){return a.cancel()});this._ongoingRequests.forEach(function(a){return a.cancel()});
this._connection&&(this._connection.close(),this._connection=null)};b.prototype.updateTile=function(a,c){var b=this;if(!this.allowUpdates)return f.resolve(null);if(!this._broadcastPromise.isFulfilled()||!this._connection)return f.reject(Error("no connection"));var d=Math.round(t.degToByte(c.state.rotation));if(a.rotation===d)return f.resolve(null);var h,g=a.key;this._updateQueue.has(g.id)&&(h=this._updateQueue.get(g.id),h.cancel());a.rotation=d;h=this._connection.invoke("update",{key:a.id,rotation:d},
null,{client:a.client}).then(function(c){a.updateSymbolData(c);return c}).always(function(){b._updateQueue["delete"](g.id)});this._updateQueue.set(a.id,h);return h};b.prototype.getVectorTileWithLRC=function(a,c,b,d){var e=this;void 0===d&&(d=0);var g=new l(a,c,b,0);return this.getRefKey(g).then(function(a){var c=new E(g,a,e._vectorTileLayer.tileInfo,e._styleRepository,0);if(a)return e.getTileData(c.key,0).then(function(a){c.setData(a.tileData,a.client);return c});c.setData(null,null);return c})};
b.prototype.getTileData=function(a,c){var b=this;return this._broadcastPromise.isFulfilled()&&this._connection?this.getRefKey(a).then(function(d){if(!d)return f.resolve(null);var e=Math.round(t.degToByte(c));return b._getTileData(b._connection,a,d,e).then(function(a){return a&&a.tileData?{tileData:a.tileData,client:a.client}:f.reject("No data")})}):f.reject(Error("no connection"))};b.prototype.getRefKey=function(a){return this._tileIndex?this._tileIndex.dataKey(a):f.resolve(a)};b.prototype.fetchTileData=
function(a){a=l.pool.acquire(a);var c=this._vectorTileLayer.getTileUrl(a.level,a.row,a.col);l.pool.release(a);return r(c,{callbackParamName:"callback",responseType:"array-buffer"}).then(function(a){return{result:a.data,transferList:[a.data]}})};b.prototype.getSprites=function(a){return this._spriteMosaic.getSpriteItems(a)};b.prototype.getGlyphs=function(a){return this._glyphMosaic.getGlyphItems(a.tileID,a.font,a.codePoints)};b.prototype.getStyleRepository=function(){return this._styleRepository};
b.prototype.getTileIndex=function(){return this._tileIndex};b.prototype._getTileData=function(a,c,b,d){var e=this,g={client:null};if(a=this._ongoingRequests.get(c.id))return a;a=this._connection.invoke("getTile",{key:c.id,refKey:b.id,rotation:d,cacheTile:this.allowUpdates},null,g).then(function(a){e._ongoingRequests["delete"](c.id);return{tileData:a,client:g.client}}).catch(function(a){e._ongoingRequests["delete"](c.id);e._connection.invoke("destructTileData",c.id,null,g);return f.reject(a)});this._ongoingRequests.set(c.id,
a);return a};b.prototype._fetchTileMap=function(a){var c=this;if(this._vectorTileLayer.capabilities.supportsTileMapIndexing&&this._vectorTileLayer.tilemapCache)return this._tileIndex=new m(this._vectorTileLayer.tilemapCache),f.resolve();if(!a)return f.resolve();if(n.has(a))return this._tileIndex=n.use(a),f.resolve();if(k.has(a))return k.get(a).then(function(a){c._tileIndex=new m(a.data)});var b=r(a,{callbackParamName:"callback",responseType:"json"});b.then(function(b){c._tileIndex=new m(b.data);k["delete"](a);
n.insert(a,c._tileIndex)});k.set(a,b);return b};return b}()});