// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("../core/declare ../core/lang ../core/kebabDictionary ../core/Error ../core/Logger ../core/accessorSupport/ensureType dojo/_base/lang ../support/arcadeUtils ../symbols/Symbol ../symbols/PolygonSymbol3D ../symbols/support/jsonUtils ../symbols/support/typeUtils ./Renderer ./support/LegendOptions ./support/ClassBreakInfo".split(" "),function(r,l,t,u,v,n,w,k,x,y,e,f,z,m,h){var A=v.getLogger("esri.renderers.ClassBreaksRenderer");m=m.LegendOptions;h=h.ClassBreakInfo;var p=t({esriNormalizeByLog:"log",
esriNormalizeByPercentOfTotal:"percent-of-total",esriNormalizeByField:"field"}),B=n.ensureType(h),q=r(z,{declaredClass:"esri.renderers.ClassBreaksRenderer",properties:{backgroundFillSymbol:{types:{base:x,key:"type",typeMap:{"simple-fill":f.types.typeMap["simple-fill"],"picture-fill":f.types.typeMap["picture-fill"],"polygon-3d":f.types.typeMap["polygon-3d"]}},value:null,json:{origins:{"web-scene":{read:e.read,write:{target:{backgroundFillSymbol:{type:y}},writer:e.writeTarget}}},read:e.read,write:e.writeTarget}},
classBreakInfos:{type:[h],json:{read:function(a,b,c){if(Array.isArray(a)){var d=b.minValue;return a.map(function(a){var b=new h;b.read(a,c);null==b.minValue&&(b.minValue=d);null==b.maxValue&&(b.maxValue=b.minValue);d=b.maxValue;return b})}},write:function(a,b,c,d){a=a.map(function(a){return a.write({},d)});this._areClassBreaksConsecutive()&&a.forEach(function(a){delete a.classMinValue});b[c]=a}}},minValue:{type:Number,readOnly:!0,dependsOn:["classBreakInfos"],get:function(){return this.classBreakInfos[0]&&
this.classBreakInfos[0].minValue||0},json:{read:!1,write:{overridePolicy:function(){return 0!==this.classBreakInfos.length&&this._areClassBreaksConsecutive()?{enabled:!0}:{enabled:!1}}}}},defaultLabel:{type:String,value:null,json:{write:!0}},defaultSymbol:{types:f.rendererTypes,value:null,json:{origins:{"web-scene":{read:e.read,write:{target:{defaultSymbol:{types:f.rendererTypes3D}},writer:e.writeTarget}}},read:e.read,write:e.writeTarget}},valueExpression:{type:String,value:null,json:{write:!0}},
valueExpressionTitle:{type:String,value:null,json:{write:!0}},compiledFunc:{dependsOn:["valueExpression"],get:function(){return k.createFunction(this.valueExpression)}},legendOptions:{type:m,value:null,json:{write:!0}},field:{value:null,cast:function(a){return null==a?a:"function"===typeof a?a:n.ensureString(a)},json:{type:String,write:function(a,b,c,d){"string"===typeof a?b[c]=a:d&&d.messages?d.messages.push(new u("property:unsupported","ClassBreaksRenderer.field set to a function cannot be written to JSON")):
A.error(".field: cannot write field to JSON since it's not a string value")}}},isMaxInclusive:!0,normalizationField:{type:String,value:null,json:{write:!0}},normalizationTotal:{type:Number,value:null,json:{write:!0}},normalizationType:{type:String,value:null,dependsOn:["normalizationField","normalizationTotal"],get:function(){var a=this._get("normalizationType"),b=!!this.normalizationField,c=null!=this.normalizationTotal;if(b||c)a=b&&"field"||c&&"percent-of-total",b&&c&&console.warn("warning: both normalizationField and normalizationTotal are set!");
else if("field"===a||"percent-of-total"===a)a=null;return a},json:{read:p.fromJSON,write:function(a,b){var c=p.toJSON(a);c&&(b.normalizationType=c)}}},requiredFields:{dependsOn:["field","normalizationField","valueExpression"]},type:{value:"class-breaks",json:{write:function(a,b){b.type="classBreaks"}}}},constructor:function(){this.classBreakInfos=[]},addClassBreakInfo:function(a,b,c){a="number"===typeof a?new h({minValue:a,maxValue:b,symbol:c}):B(l.clone(a));this.classBreakInfos.push(a);1===this.classBreakInfos.length&&
this.notifyChange("minValue")},removeClassBreakInfo:function(a,b){var c,d,e=this.classBreakInfos.length;for(d=0;d<e;d++)if(c=[this.classBreakInfos[d].minValue,this.classBreakInfos[d].maxValue],c[0]==a&&c[1]==b){this.classBreakInfos.splice(d,1);break}},getBreakIndex:function(a,b){var c=this.field,d=a.attributes,e=this.classBreakInfos.length,g,h=this.isMaxInclusive;if(this.valueExpression)c=k.executeFunction(this.compiledFunc,k.createExecContext(a,k.getViewInfo(b)));else if(w.isFunction(c))c=c(a);else{c=
parseFloat(d[c]);g=this.normalizationType;var f;if(g)if(f=parseFloat(this.normalizationTotal),d=parseFloat(d[this.normalizationField]),"log"===g)c=Math.log(c)*Math.LOG10E;else if("percent-of-total"===g&&!isNaN(f))c=c/f*100;else if("field"===g&&!isNaN(d)){if(isNaN(c)||isNaN(d))return-1;c/=d}}if(null!=c&&!isNaN(c)&&"number"===typeof c)for(d=0;d<e;d++)if(g=[this.classBreakInfos[d].minValue,this.classBreakInfos[d].maxValue],g[0]<=c&&(h?c<=g[1]:c<g[1]))return d;return-1},getClassBreakInfo:function(a,b){var c=
this.getBreakIndex(a,b);return-1!==c?this.classBreakInfos[c]:null},getSymbol:function(a,b){var c=this.getBreakIndex(a,b);return-1<c?this.classBreakInfos[c].symbol:this.defaultSymbol},getSymbols:function(){var a=[];this.classBreakInfos.forEach(function(b){b.symbol&&a.push(b.symbol)});this.defaultSymbol&&a.push(this.defaultSymbol);return a},clone:function(){return new q({field:this.field,backgroundFillSymbol:this.backgroundFillSymbol&&this.backgroundFillSymbol.clone(),defaultLabel:this.defaultLabel,
defaultSymbol:this.defaultSymbol&&this.defaultSymbol.clone(),valueExpression:this.valueExpression,valueExpressionTitle:this.valueExpressionTitle,classBreakInfos:l.clone(this.classBreakInfos),isMaxInclusive:this.isMaxInclusive,normalizationField:this.normalizationField,normalizationTotal:this.normalizationTotal,normalizationType:this.normalizationType,visualVariables:l.clone(this.visualVariables),legendOptions:l.clone(this.legendOptions),authoringInfo:this.authoringInfo&&this.authoringInfo.clone()})},
collectRequiredFields:function(a){this.inherited(arguments);[this.field,this.normalizationField].forEach(function(b){b&&(a[b]=!0)});this.valueExpression&&k.extractFieldNames(this.valueExpression).forEach(function(b){a[b]=!0})},_areClassBreaksConsecutive:function(){for(var a=this.classBreakInfos,b=1;b<a.length;b++)if(a[b-1].maxValue!==a[b].minValue)return!1;return!0}});return q});