// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/tooltips/ChartTooltip","dojo/_base/declare dojo/_base/lang dojo/_base/window dojo/_base/connect dojo/sniff dojo/dom-class dojo/dom-construct dojo/dom-geometry dijit/Tooltip dojox/charting/action2d/Tooltip dojox/lang/functional dojox/gfx/matrix ./_BuilderUtil ./_ColumnBarChartTooltipBuilder ./_GaugeChartTooltipBuilder ./_LineChartTooltipBuilder ./_PieDonutRingChartTooltipBuilder ../chartUtils/ChartTypes ../../supportClasses/conditionalStyling/ConditionalStyleLegendBuilder esri/dijit/geoenrichment/utils/DomUtil dojo/i18n!../../../../../../nls/jsapi".split(" "),
function(u,v,w,x,y,q,h,z,l,A,m,B,r,C,D,E,F,e,G,H,p){p=p.geoenrichment.dijit.ReportPlayer.ChartTooltip;var n=Math.PI/4,I=Math.PI/2,t={_nodeInLayoutCheckHandle:null,_rawNode:null,_node:null,show:function(a,b,d,e){b&&(this.hide(b),l.show(a,b,d),this._setClasses(!0),this._setListeners(b,e))},hide:function(a){l.hide(a);this._setClasses(!1);this._setListeners(null,null)},_setClasses:function(a){l._masterTT&&(q[a?"add":"remove"](l._masterTT.domNode,"esriGEChartContainer_chartTooltip_masterTooltip"),q[a?
"add":"remove"](l._masterTT.containerNode,"esriGEChartContainer_chartTooltip_containerNode"))},_setListeners:function(a,b){var d=this;clearInterval(this._nodeInLayoutCheckHandle);b&&(this._node=a,this._rawNode=b,this._nodeInLayoutCheckHandle=setInterval(function(){H.isNodeInLayout(d._rawNode)||d.hide(d._node)},500))}};return u(A,{showStatistics:!0,_chartType:null,constructor:function(){var a=this,b=this.text;this.text=function(d,e){var c;c=d.run&&d.run.data&&d.run.data[d.index];c=c.tooltip&&"object"===
typeof c.tooltip?a._renderTooltip(c.tooltip):void 0;return c||b(d,e)}},process:function(a){function b(){v.mixin(c,d())}function d(){var b=a.shape.rawNode.getBoundingClientRect(),c=z.position(h.chart.node,!0);return{x:b.left-c.x,y:b.top-c.y,w:b.width,h:b.height}}var h=this;if("onplotreset"===a.type||"onmouseout"===a.type)t.hide(this.aroundRect),this.aroundRect=null,"onplotreset"===a.type&&delete this.angles;else if(!(!a.shape||this.mouseOver&&"onmouseover"!==a.type||!this.mouseOver&&"onclick"!==a.type)){var c=
{type:"rect"},k=["after-centered","before-centered"];if(e.isPictureLike(this._chartType))b();else{switch(a.element){case "marker":case "circle":case "spider_circle":case "spider_plot":case "candlestick":b();break;case "column":k=["above-centered","below-centered"];case "bar":b();break;default:if(!this.angles){var f="number"===typeof a.run.data[0]?m.map(a.run.data,"x ? Math.max(x, 0) : 0"):m.map(a.run.data,"x ? Math.max(x.y, 0) : 0");this.angles=m.map(m.scanl(f,"+",0),"* 2 * Math.PI / this",m.foldl(f,
"+",0))}var f=B._degToRad(a.plot.opt.startAngle),g=(this.angles[a.index]+this.angles[a.index+1])/2+f;b();f&&(0>g||g>2*Math.PI)&&(g=Math.abs(2*Math.PI-Math.abs(g)));g<n||(g<I+n?k=["below-centered","above-centered"]:g<Math.PI+n?k=["before-centered","after-centered"]:g<2*Math.PI-n&&(k=["above-centered","below-centered"]))}y("dojo-bidi")&&this._recheckPosition(a,c,k)}f=this.chart.getCoords();c.x+=f.x;c.y+=f.y;c.x=Math.round(c.x);c.y=Math.round(c.y);c.w=Math.ceil(c.w);c.h=Math.ceil(c.h);this.aroundRect=
c;(f=this.text(a,this.plot))&&t.show(this._format(f),this.aroundRect,k,a.shape.rawNode);this.mouseOver||(this._handle=x.connect(w.doc,"onclick",this,"onClick"))}},setChartType:function(a){this._chartType=a},_renderTooltip:function(a){var b=h.create("div",{"class":"esriGEChartContainer_chartTooltip"},document.body);if(this.showStatistics)this._chartType===e.PIE||this._chartType===e.DONUT||this._chartType===e.RING?F.buildPieDonutRingChartTooltip(a,b):this._chartType===e.GAUGE?D.buildGaugeChartTooltip(a,
b):e.isColumnBarLike(this._chartType)?C.buildColumnChartTooltip(a,b):this._chartType===e.LINE&&E.buildLineChartTooltip(a,b);else{r.addTitle(b,a.label,a.color);var d=h.create("div",{"class":"chartTooltip_row esriGERowHigh"},b);a.fieldInfo&&r.addValue((a.fieldInfo.script?a.fieldInfo.script.alias:a.fieldInfo.alias)||"",d)}a.conditionalStyling&&(this.showStatistics||h.create("div",{"class":"chartTooltip_row",style:"margin-top:30px;margin-left:10px;",innerHTML:p.colorOfBackWillDependOnValue},b),h.place(G.createLegendNode(a.conditionalStyling,
"chart",a.value),b));a=b.outerHTML;h.destroy(b);return a}})});