// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/tiling/TileInfoView","require exports ./LODInfo ./TileCoverage ./TileKey ./TileSpan".split(" "),function(z,A,w,x,n,u){var y=function(){function d(a,c,b,e,r,h,t,g){this.x=a;this.ymin=c;this.ymax=b;this.invM=e;this.leftAdjust=r;this.rightAdjust=h;this.leftBound=t;this.rightBound=g}d.create=function(a,c){a[1]>c[1]&&(b=[c,a],a=b[0],c=b[1]);var b=a[0],e=a[1],r=c[0],h=c[1],t=r-b,g=h-e,g=0!==g?t/g:0,k=(Math.ceil(e)-e)*g,l=(Math.floor(e)-e)*g;return new d(b,Math.floor(e),
Math.ceil(h),g,0>t?k:l,0>t?l:k,0>t?r:b,0>t?b:r);var b};d.prototype.incrRow=function(){this.x+=this.invM};d.prototype.getLeftCol=function(){return Math.max(this.x+this.leftAdjust,this.leftBound)};d.prototype.getRightCol=function(){return Math.min(this.x+this.rightAdjust,this.rightBound)};return d}(),l=[[0,0],[0,0],[0,0],[0,0]];return function(){function d(a,c){var b=this;this.tileInfo=a;this.fullExtent=c;this.scales=[];this._lodInfos=null;this._infoByScale={};this._infoByLevel={};var e=a.lods.slice();
e.sort(function(b,a){return a.scale-b.scale});var r=this._lodInfos=e.map(function(b){return w.create(a,b,c)});e.forEach(function(a,c){b._infoByLevel[a.level]=r[c];b._infoByScale[a.scale]=r[c];b.scales[c]=a.scale},this);this._wrap=a.isWrappable}d.prototype.getTileBounds=function(a,c){var b=this._infoByLevel[c.level];return b?b.getTileBounds(a,c):a};d.prototype.getTileCoords=function(a,c){var b=this._infoByLevel[c.level];return b?b.getTileCoords(a,c):a};d.prototype.getTileCoverage=function(a,c){void 0===
c&&(c=192);var b=this.getClosestInfoForScale(a.scale),e=x.pool.acquire(b),r=this._wrap,h;h=Infinity;var d=-Infinity,g,k,n=e.spans;l[0][0]=l[0][1]=l[1][1]=l[3][0]=-c;l[1][0]=l[2][0]=a.size[0]+c;l[2][1]=l[3][1]=a.size[1]+c;for(var q=0;q<l.length;q++){var f=l[q];a.toMap(f,f);f[0]=b.getColumnForX(f[0]);f[1]=b.getRowForY(f[1])}for(var q=[],p=3,f=0;4>f;f++){if(l[f][1]!==l[p][1]){var m=y.create(l[f],l[p]);h=Math.min(m.ymin,h);d=Math.max(m.ymax,d);void 0===q[m.ymin]&&(q[m.ymin]=[]);q[m.ymin].push(m)}p=f}if(null==
h||null==d||100<d-h)return null;for(p=[];h<d;){null!=q[h]&&(p=p.concat(q[h]));g=Infinity;k=-Infinity;for(f=p.length-1;0<=f;f--)m=p[f],g=Math.min(g,m.getLeftCol()),k=Math.max(k,m.getRightCol());g=Math.floor(g);k=Math.floor(k);if(h>=b.first[1]&&h<=b.last[1])if(r)if(b.size[0]<b.worldSize[0])for(m=Math.floor(k/b.worldSize[0]),f=Math.floor(g/b.worldSize[0]);f<=m;f++)n.push(new u(h,Math.max(b.getFirstColumnForWorld(f),g),Math.min(b.getLastColumnForWorld(f),k)));else n.push(new u(h,g,k));else g>b.last[0]||
k<b.first[0]||(g=Math.max(g,b.first[0]),k=Math.min(k,b.last[0]),n.push(new u(h,g,k)));h+=1;for(f=p.length-1;0<=f;f--)m=p[f],m.ymax>=h?m.incrRow():p.splice(f,1)}return e};d.prototype.getTileIdAtParent=function(a,c){var b=n.pool.acquire(c),e=this._infoByLevel[b.level];if(a.resolution<e.resolution)throw Error("Cannot calculate parent tile. destination LOD's resolution "+a.resolution+" is not a parent resolution of "+e.resolution);return a.resolution===e.resolution?b.id:n.getId(a.level,Math.floor(b.row*
e.resolution/a.resolution+.01),Math.floor(b.col*e.resolution/a.resolution+.01),b.world)};d.prototype.getTileParentId=function(a){a=n.pool.acquire(a);var c=this._lodInfos.indexOf(this._infoByLevel[a.level])-1;if(0>c)return n.pool.release(a),null;c=this.getTileIdAtParent(this._lodInfos[c],a);n.pool.release(a);return c};d.prototype.getTileResolution=function(a){return(a=this._infoByLevel[a.level])?a.resolution:-1};d.prototype.getTileScale=function(a){return(a=this._infoByLevel[a.level])?a.scale:-1};
d.prototype.intersects=function(a,c){var b=n.pool.acquire(c),e=this._infoByLevel[b.level],d=a.lodInfo;if(d.resolution>e.resolution){var h=n.pool.acquire(this.getTileIdAtParent(d,b)),l=d.denormalizeCol(h.col,h.world),g=a.spans.some(function(a){return a.row===h.row&&a.colFrom<=l&&a.colTo>=l});n.pool.release(b);n.pool.release(h);return g}if(d.resolution<e.resolution){var k=a.spans.reduce(function(a,b){a[0]=Math.min(a[0],b.row);a[1]=Math.max(a[1],b.row);a[2]=Math.min(a[2],b.colFrom);a[3]=Math.max(a[3],
b.colTo);return a},[Infinity,-Infinity,Infinity,-Infinity]),g=k[0],u=k[1],q=k[2],k=k[3],f=e.denormalizeCol(b.col,b.world),p=d.getColumnForX(e.getXForColumn(f)),m=d.getRowForY(e.getYForRow(b.row)),f=d.getColumnForX(e.getXForColumn(f+1))-1,e=d.getRowForY(e.getYForRow(b.row+1))-1;n.pool.release(b);return!(p>k||f<q||m>u||e<g)}var v=d.denormalizeCol(b.col,b.world),g=a.spans.some(function(a){return a.row===b.row&&a.colFrom<=v&&a.colTo>=v});n.pool.release(b);return g};d.prototype.getClosestInfoForScale=
function(a){var c=this.scales;this._infoByScale[a]||(a=c.reduce(function(b,c,d,h){return Math.abs(c-a)<Math.abs(b-a)?c:b},c[0]));return this._infoByScale[a]};return d}()});