// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/themes/ThemeUtil",["dojo/_base/lang","esri/dijit/geoenrichment/utils/ColorUtil","esri/dijit/geoenrichment/utils/ObjectUtil"],function(l,d,p){function q(a){var b=d.isLightColor(a);return d.transform(a,{dv:b?-7:7}).toHex()}var r={getPanelTitleColor:function(a){var b=d.isLightColor(a);return d.transform(a,{dv:b?-50:50}).toHex()},getChartElementBackgroundColor:function(a){var b=d.isLightColor(a);return d.transform(a,{dv:b?-13:13}).toHex()}},u={getThemeColors:function(a){return[a.document.backgroundColor,
a.infographic.staticInfographic.icon.backgroundColor,a.infographic.staticInfographic.highlightedIcon.backgroundColor]},_generateChartColors:function(a,b){var c=[b,d.transform(b,{dv:-20}).toHex(),d.transform(b,{dv:-40}).toHex(),d.transform(b,{dv:-50}).toHex(),d.transform(b,{dv:-55}).toHex(),d.transform(b,{dv:-60}).toHex(),d.transform(b,{dv:-65}).toHex(),d.transform(b,{dv:-70}).toHex()];a!==b&&c.unshift(a);return c},applyThemeColorsToTheme:function(a,b,c,t){var e=b[0],g=b[1];b=b[2];var f=d.getContrastColor(e).toHex(),
m="#FFFFFF"===e.toUpperCase()?"#4C4C4C":f,h=d.isLightColor(e),n=r.getChartElementBackgroundColor(e),k=r.getPanelTitleColor(e),l={overrideStyles:{Default:{color:m,backgroundColor:"transparent"},ReportTitle:{color:b,backgroundColor:"transparent"},TableHeader:{color:d.getContrastColor(g,void 0,void 0,200).toHex(),backgroundColor:g},GreyText:{color:d.transform(e,{dv:h?-33:33}).toHex(),backgroundColor:"transparent"},BlueText:{color:"#56A5D8",backgroundColor:"transparent"},AlternatingRow:{color:m,backgroundColor:d.transform(e,
{dv:h?-7:7}).toHex()}}},v={lineColor:f,gridLinesColor:f,gridStripesColor:q(e),gridStripesColorAlt:"transparent",axisStyle:{color:f},titleStyle:{color:f}},w={lineColor:f,gridLinesColor:f,gridStripesColor:q(e),gridStripesColorAlt:"transparent",baseLineColor:f,axisStyle:{color:f},titleStyle:{color:f}},x=d.isLightColor(e),e={document:{color:m,backgroundColor:e},table:l,chart:{backgroundColor:"transparent",titleStyle:{color:k},dataLabelsStyle:{color:f},xAxis:v,yAxis:w,legendStyle:{color:f,backgroundColor:e},
minMaxLegend:{titleStyle:{color:f}},ring:{ringBackground:{backgroundColor:n}},gauge:{dataLabelStyle:{color:g},othersColor:n,arrowIndicator:{lineColor:k,backgroundColor:k}},icon:{backgroundColor:g},columnBarBackground:{backgroundColor:n},comparisonInfo:{lineColor:x?"#666666":"#BBBBBB"}},infographic:{backgroundColor:"transparent",agePyramid:{theme:h?"light":"common",male:{backgroundColor:g},female:{backgroundColor:b}},staticInfographic:{backgroundColor:"transparent",icon:{backgroundColor:g},highlightedIcon:{backgroundColor:b},
iconBarBackground:{},titleLine:{color:d.transform(e,{dv:h?-40:40}).toHex()},titleStyle:{color:k},variableLabelStyle:{color:g},variableLabelStyleHighlighted:{color:b},variableLabelStyleContrast:{color:e},variableDescriptionStyle:{color:d.transform(e,{dv:h?-50:50}).toHex()}}}};t&&t(e);p.populateObject(a,e,!0);a&&a.chart&&(a.chart.colors=c&&c.length?c:u._generateChartColors(g,b))},applyTextStyleToTheme:function(a,b){function c(a){var c=l.mixin({},b);a&&delete c.color;return c}var d={document:c(),table:{overrideStyles:{Default:{color:b.color},
ReportTitle:{color:b.color},TableHeader:{color:b.color},AlternatingRow:{color:b.color}}},chart:{titleStyle:c(),dataLabelsStyle:c(),xAxis:{axisStyle:c(),titleStyle:c()},yAxis:{axisStyle:c(),titleStyle:c()},legendStyle:c(),minMaxLegend:{titleStyle:c(),minVariableLabelStyle:c(!0),maxVariableLabelStyle:c(!0)}},infographic:{staticInfographic:{titleStyle:c(),variableLabelStyle:c(),variableDescriptionStyle:c(),variableLabelStyleHighlighted:c(),variableLabelStyleContrast:c()}}};p.populateObject(a,d,!0)},
removeBackgroundFromThemeElements:function(a,b){if(a&&(a.chart.backgroundColor="transparent",a.infographic.backgroundColor="transparent",a.infographic.staticInfographic=a.infographic.staticInfographic||{},a.infographic.staticInfographic.backgroundColor="transparent",b))for(var c in a.table.overrideStyles)a.table.overrideStyles[c].backgroundColor="transparent"}};return u});