// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/ChartJsonUtil","dojo/_base/lang ./ThemeCalculator ./ChartTypes ./ChartDataLabelsTypes ../legends/ChartLegendPlacements ../legends/ChartLegendTypes ./_ChartJsonCleaner ./_ChartJsonClassicReportSupports esri/dijit/geoenrichment/utils/ObjectUtil ./plots/supportClasses/GaugeLabelPlacement".split(" "),function(a,c,k,l,f,m,n,p,g,q){var h={getDefaultChartSettings:function(b){b=b||{};var d=a.mixin({},b.font),e=a.mixin({},b.font);delete e.fontSize;
return{isChart:!0,type:b.chartType||k.COLUMN,isMultiFeatureChart:!!b.isMultiFeatureChart,seriesItems:[],visualProperties:{width:b.width||400,height:b.height||300,barBorders:!1,view3D:!1,origin:0,backgroundColor:void 0,backgroundImageData:void 0,panelBackgroundColor:void 0,title:{text:"",align:"center",style:a.mixin({},d)},xAxis:{show:!0,showTicks:!0,ticksInside:!1,showLine:!0,title:"",titleStyle:a.mixin({},d),style:a.mixin({},d),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,
gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,placement:void 0},yAxis:{show:!0,showTicks:!0,ticksInside:!1,showLine:!0,title:"",titleStyle:a.mixin({},d),style:a.mixin({},d),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,baseLine:!0,baseLineColor:void 0,
baseLineOpacity:1,baseLineThickness:.5,baseLineStyle:void 0,baseLineValue:0,showPercentIndicator:!1,showValuesAsWeightsInSeries:!1,placement:void 0},legend:{type:m.SERIES,series:{placement:f.RIGHT,placementOffset:10,hasBorder:!0,labelParts:"Label",style:a.mixin({},d)},minMax:{placement:f.RIGHT,placementOffset:3,titleStyle:a.mixin({},e),minVariableLabelStyle:a.mixin({},e),maxVariableLabelStyle:a.mixin({},e)}},isStacked:!1,columnThickness:c.DEFAULT_COLUMN_THICKNESS,showColumnBarBackground:!1,columnBarBackgroundColor:void 0,
renderColumnBarsInOppositeDirections:!1,columnBarGap:void 0,lineThickness:c.DEFAULT_LINE_THICKNESS,fillLineArea:!1,donutHolePercent:c.DEFAULT_DONUT_HOLE_PERCENT,donutGap:c.DEFAULT_DONUT_GAP,donutArcPercent:c.DEFAULT_DONUT_ARC_PERCENT,gaugeHolePercent:c.DEFAULT_GAUGE_HOLE_PERCENT,gaugeRangeMin:void 0,gaugeRangeMax:void 0,gaugeGap:c.DEFAULT_GAUGE_GAP,gaugeStartAngle:c.DEFAULT_GAUGE_ANGLE,gaugeArcPercent:c.DEFAULT_GAUGE_ARC_PERCENT,gaugeLabelPlacement:q.INSIDE,gaugeLabelStyle:a.mixin({},e),gaugeShowArrow:!1,
gaugeArrowLineColor:void 0,gaugeArrowFillColor:void 0,ringBackgroundColor:void 0,showWholePictures:!1,dataLabels:l.NONE,dataLabelsStyle:a.mixin({},d),dataLabelsDecimals:0,dataLabelsInside:!1,dataLabelsStackedInColumns:!1,dataLabelsHorizontalAlign:void 0,chartIcons:void 0,floatingIcons:void 0,showAxisIcons:!1,showChartIcons:!1,floatingTexts:void 0,sorting:void 0,conditionalStyling:void 0},comparisonInfo:void 0}},provideDefaultValueForMissing:function(b,a){var d=h.getDefaultChartSettings(a);g.populateObject(b,
d);return b},cleanUpJson:function(b,a){n.cleanUpJson(b,a)},filterChartJsonForClassicReport:function(b){return g.filterByPattern(b,p)},createChartPoint:function(b,a,c,f,g){return{color:c||"",label:a||b&&b.alias,fieldInfo:b,iconFieldInfo:f,captionFieldInfo:g}}};return h});