// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/MapBuilder","dojo/_base/Color dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/Evented dojo/when dojo/dom-construct dojo/dom-style dojo/dom-geometry esri/graphic esri/layers/GraphicsLayer esri/arcgis/utils esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleFillSymbol esri/symbols/SimpleLineSymbol esri/graphicsUtils ./WebMapsUtil ../../../dataProvider/supportClasses/AreaDataUtil esri/dijit/geoenrichment/utils/ImageUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),
function(l,c,v,m,w,x,p,g,y,z,A,B,q,C,n,D,r,E,F,G){var H=c(w,{_mapImageInfo:null,_mapImage:null,loaded:!1,error:!1,constructor:function(b,a){this._mapImageInfo=b;this._mapImage=p.create("img",{"class":"esriGEAbsoluteStretched"},a);g.set(this._mapImage,{width:g.get(a,"width")+"px",height:g.get(a,"height")+"px"});g.set(a,"position","relative")},load:function(){function b(b){a.error=!0;b&&console.log(b);a.destroy();e.resolve()}var a=this,e=new m;if(!this._mapImageInfo.url)return b(Error("No URL specified.")),
e.promise;this._mapImage.onload=function(){a.loaded=!0;e.resolve()};this._mapImage.onerror=b;this._mapImage.src=this._mapImageInfo.url;return e.promise},destroy:function(){p.destroy(this._mapImage)}});c=c(null,{_mapDivs:null,_mapDivId:0,_mapImageInfos:null,renderMapsFromCalculators:!1,constructor:function(b){v.mixin(this,b);this.reset()},setArcgisUrl:function(b){b&&(B.arcgisUrl=G.combine(b,"/sharing/rest/content/items"))},reset:function(){this._mapDivs={};this._mapImageInfos=null},collectAreaMaps:function(b){var a=
[];b=b||0;var e=this._mapDivs[b],c;for(c in e){var f=e[c];if(f.parentNode){var h=y.position(f);a.push({areaIndex:b,node:f,x:h.x,y:h.y,position:-1,map:f._map,itemId:f._itemId})}}a.sort(function(a,b){return a.x-b.x});a.sort(function(a,b){return a.y-b.y});a.forEach(function(a,b){a.position=b});return a},collectAllAreasMaps:function(){var b=[],a;for(a in this._mapDivs)b=b.concat(this.collectAreaMaps(a));return b},setFallbackMapImageInfos:function(b){b?(this._mapImageInfos={},b.forEach(function(a){var b=
a.areaIndex||0;(this._mapImageInfos[b]=this._mapImageInfos[b]||{})[a.itemId]=a},this)):this._mapImageInfos=null},createMap:function(b,a){function e(d){return r.createMap(d,b,{extent:D.graphicsExtent(a.features).expand(a.expandFactor||1.5),sliderPosition:!1===a.sliderPosition?"none":a.sliderPosition||"top-right",defaultBasemapId:a.defaultBasemapId}).then(function(a){return a&&a.map?c(a.map):(new m).reject(Error("Can't create a map."))})}function c(d){var t=new A;d.addLayer(t);a.features.forEach(function(a){var b=
a.getLayer(),d=b&&b.renderer&&b.renderer.getSymbol(a)||a.symbol,c=a.geometry;d||("point"===a.geometry.type?d=new q(q.STYLE_CIRCLE,20,new n(n.STYLE_SOLID,new l([255,255,255,.7]),2),new l([255,0,0,.7])):(d=new C,d.setOutline(new n(n.STYLE_SOLID,new l([255,0,0,1]),2)),d.setColor(new l([100,100,100,.25]))));c=new z(c,d,a.attributes);c.setInfoTemplate(b&&b.infoTemplate||a.infoTemplate);t.add(c)});void 0===b.__mapDivId&&(b.__mapDivId=k._mapDivId++);b._map=d;b._itemId=a.webMapId;(k._mapDivs[h]=k._mapDivs[h]||
{})[b.__mapDivId]=b;return d}function f(a){var c=a&&new H(a,b);return c&&c.load().then(function(){return c.loaded?c:null})}a=a||{};var h=a.areaIndex||0,k=this;if(this.renderMapsFromCalculators&&a.calculatorFieldName){var g=E.getAreaDataValue(a.calculatorFieldName,a.fieldData);if(g)return f({url:F.base64DataToDataURL(g)})}return x(r.getItem(a.webMapId),function(a){if(!a)return(new m).reject(Error("Can't load an item or the item is incorrect."));var b=new m;try{e(a).then(b.resolve,b.reject)}catch(u){b.reject(u),
console.log(u)}return b.promise}).otherwise(function(){return f(k._mapImageInfos&&k._mapImageInfos[h]&&k._mapImageInfos[h][a.webMapId])})}});c.EXPAND_FACTOR=1.5;return c});