// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/plots/Donut","dojo/_base/Color dojo/_base/declare dojo/_base/lang dojox/charting/plot2d/Base dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx dojox/gfx/matrix dojox/lang/functional dojox/lang/utils dojo/has ./animation/_DonutAnimation ./labelsRendering/LabelOverlapFixer ./labelsRendering/LabelsUtil".split(" "),function(W,G,H,I,J,R,X,K,w,y,N,S,T,U){var V={createPath:function(a,c,e,b,d,f,g,n,r,p,h,k){var u=
function(d,l,k){c=void 0!==l?l:c;l=z.getEndAngle(c,d,f,g,r,h,k);1===d&&(l=Number(Math.floor(1E5*l)/1E5));d=e*n;k=l-c;var q=b.cx+e*Math.cos(c),m=b.cy+e*Math.sin(c),t=b.cx+e*Math.cos(l),u=b.cy+e*Math.sin(l);if(d){var v=b.cx+d*Math.cos(c),w=b.cy+d*Math.sin(c),B=b.cx+d*Math.cos(l),C=b.cy+d*Math.sin(l);shape=a.createPath().moveTo(v,w).lineTo(q,m).arcTo(e,e,0,k>Math.PI,!0,t,u).lineTo(B,C).arcTo(d,d,0,k>Math.PI,!1,v,w).closePath().setStroke(p.series.stroke)}else shape=a.createPath().moveTo(b.cx,b.cy).lineTo(q,
m).arcTo(e,e,0,k>Math.PI,!0,t,u).lineTo(b.cx,b.cy).closePath().setStroke(p.series.stroke);specialFill=p.series.fill;shape.setFill(specialFill);return{shape:shape,end:l,donutGap:g}};k.push({isSlice:!0,sliceIndex:d,func:u});return u}},z={getStartAngle:function(a,c){return a.series.donutArcPercent&&100!==a.series.donutArcPercent?-270+(100-a.series.donutArcPercent)/100*360/2:(a.series.startAngle||0)+c},getEndAngle:function(a,c,e,b,d,f,g){a=a+2*c*Math.PI-b;e&&(e=f+2*Math.PI-b,a=g||d.series.donutArcPercent&&
100!==d.series.donutArcPercent?Math.min(a+b,e):e);return a}};return G([I,J,S],{enableHole:!0,enableGap:!0,startAngleOffset:0,_animationInfos:null,_dataLabels:null,_labelBoxes:null,defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelStyle:"outside",htmlLabels:!0,radGrad:"native",fanSize:5,startAngle:0,animate:null},optionalParams:{radius:0,omitLabels:!1,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},constructor:function(a,c){this.opt=H.clone(this.defaultParams);
y.updateWithObject(this.opt,c);y.updateWithPattern(this.opt,c,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);this.dyn=[];this.run=null;return this},setAxis:function(a){return this},addSeries:function(a){this.run=a;return this},getSeriesStats:function(){return H.delegate(R.defaultStats)},getRequiredColors:function(){return this.run?this.run.data.length:0},getRenderResults:function(){return this._lastRenderResults},render:function(a,
c){if(!this.dirty)return this;this.resetEvents();this._eventSeries={};this.cleanGroup();var e=this.group,b=this.chart.theme;if(!this.run||!this.run.data.length)return this;var d=(a.width-c.l-c.r)/2,f=(a.height-c.t-c.b)/2/this._getRYMultiplier(b),g=Math.min(d,f),n,r=K._degToRad(this._getStartAngle(b)),p=r,h,k,u,t,l,y=this.events(),q=this.run.data.map(function(b,a){"number"!==typeof b&&b.hidden&&(this.runFilter.push(a),b.hidden=!1);return this.runFilter.some(function(b){return b===a})?"number"===typeof b?
0:{y:0,text:b.text}:b},this);this.dyn=[];"radius"in this.opt&&(l=g=this.opt.radius);var m={cx:c.l+d,cy:c.t+f,r:g},O;h=w.map(q,"x ? Math.max(x.y, 0) : 0");if(w.every(h,"\x3c\x3d 0"))return e.createCircle(m).setStroke(b.series.stroke),this.dyn=h.map(function(){return{}}),this;k=w.map(h,"/this",w.foldl(h,"+",0));this.opt.labels&&(u=k.map(function(a,d){return U.getLabelInfo(this,q[d],b)},this));var A=this.enableHole?(b.series.donutHolePercent||0)/100:0,v=this.enableGap?K._degToRad(b.series.donutGap||
0):0;k=this._fixSlices(k,v);this._lastRenderResults={};this._animationInfos=[];this._labelBoxes=[];var P=w.map(q,function(a,d){var c=[this.opt,this.run];null!=a&&"number"!==typeof a&&c.push(a);this.opt.styleFunc&&c.push(this.opt.styleFunc(a));return b.next("slice",c,!0)},this);h=this._preprocessParams(q,b,g,d,f,m,k);m=h.circle;g=h.r;if(this.opt.labels)switch(t=n=0,u.forEach(function(b,a){n=Math.max(n,b.box.h);t=Math.max(t,b.box.w)}),this.opt.labelStyle){case "outside":h=g;g=Math.min(d-t,f-n)-5;l=
g+t/2;g=Math.max(g,h/2);break;case "inside":l=Math.abs((g-g*A)/2+g*A+(g-t/2))/2;break;case "columns":l=g=Math.min(d-t-20,f-2*n)}var B=Array(k.length);k.some(function(a,d){a=this._getSliceValueAt(k,d,b);var c=q[d],f=P[d];O=g*A;var n=V.createPath(e,p,g,m,d,d+1===k.length,v,A,b,f,r,this._animationInfos)(a),h=n.end;shape=n.shape;this.dyn.push({fill:void 0,stroke:f.series.stroke});y&&(c={element:"slice",index:d,run:this.run,shape:shape,x:d,y:"number"===typeof c?c:c.y,cx:m.cx,cy:m.cy,cr:g},this._connectEvents(c),
B[d]=c);p=h+v;return!1},this);if(this.opt.labels){var C=N("dojo-bidi")&&this.chart.isRightToLeft();if("outside"===this.opt.labelStyle||"inside"===this.opt.labelStyle)p=r,k.some(function(d,c){d=this._getSliceValueAt(k,c,b);var e=u[c];if(0>=d)return!1;if(1<=d)return this._labelBoxes.push({x:m.cx-e.box.w/2,y:m.cy+n/2,w:e.box.w,h:e.box.h,text:e.text}),!0;var f=z.getEndAngle(p,d,c+1===k.length,v,b,r);if(this.opt.omitLabels&&.001>f-p)return!1;var g=(p+f)/2,h=l;"outside"===this.opt.labelStyle&&(h=1.15*l+
(n-t/2-.15*l)*Math.abs(Math.sin(g)));var q=m.cx+h*Math.cos(g);this._labelBoxes.push({x:(C?a.width-q:q)-e.box.w/2,y:m.cy+h*Math.sin(g)+n/2-(2===e.numRows?e.box.h/2:0),w:e.box.w,h:e.box.h,text:e.text});p=f+v;return!1},this);else if("columns"===this.opt.labelStyle){var p=r,G=this.opt.omitLabels,D=[];k.forEach(function(d,a){d=this._getSliceValueAt(k,a,b);var c=z.getEndAngle(p,d,a+1===k.length,v,b,r),e=(p+c)/2;D.push({angle:e,left:0>Math.cos(e),theme:P[a],index:a,omit:G?.001>c-p:!1});p=c+v},this);this._getProperLabelRadius(D,
u[0].box.h,1.1*l);for(f=0;f<D.length;f++){h=D[f];var E=u[f];if(!h.omit){var x=m.cx-d,F=m.cx+d,L=E.box.w,I=m.cx+h.labelR*Math.cos(h.angle),M=m.cy+h.labelR*Math.sin(h.angle),F=h.left?x+L:F-L,x=h.left?x:F,Q=e.createPath().moveTo(m.cx+l*Math.cos(h.angle),m.cy+l*Math.sin(h.angle));Q.lineTo(I,M);Q.lineTo(F,M).setStroke(h.theme.series.labelWiring);this._labelBoxes.push({x:C?a.width-L-x:x,y:M,w:E.box.w,h:E.box.h,text:E.text})}}}}this._renderLabels(e,b,a,c);var J=0;this._eventSeries[this.run.name]=w.map(q,
function(a){return 0>=a?null:B[J++]});N("dojo-bidi")&&this._checkOrientation(this.group,a,c);this.dirty=!1;this._lastRenderResults=H.mixin(this._lastRenderResults,{labels:this.opt.labels,radiusInner:O,radiusOuter:g});this._renderAdditionalElements(q,b,g,e,m,k);this.opt.animate&&this._renderAnimation(q,b,g,e,m,k);return this},_renderLabels:function(a,c,e,b){this._dataLabels=[];T.fixLabelsOverlap(this._labelBoxes,e,b,this._getFixLabelsParams(),a);this._labelBoxes.forEach(function(b){b.hidden||this._dataLabels.push(this.renderLabel(a,
b.x,b.y,b.text,c,!0,"left"))},this)},_getFixLabelsParams:function(){return{allowXShift:!0,allowYShift:!0,xGap:3,yGap:3,xTolerance:0,yTolerance:0}},_getStartAngle:function(a){return z.getStartAngle(a,this.startAngleOffset)},_fixSlices:function(a,c){var e=[],b=0,d=[],f=c/(2*Math.PI)+.001;a.forEach(function(a,c){if(a<f){var g=f-a;a=f;b+=g;d.push(c);e[c]=a}});var g=b/(a.length-d.length);a.forEach(function(a,b){-1===d.indexOf(b)&&(a-=g,e[b]=a)});return e},_getSliceValueAt:function(a,c,e){return Math.max(0,
a[c])*(e.series.donutArcPercent?e.series.donutArcPercent/100:1)},_preprocessParams:function(a,c,e,b,d,f,g){return{circle:f,r:e}},_getRYMultiplier:function(a){return Math.max(.625,a.series.donutArcPercent&&100!==a.series.donutArcPercent?(1+Math.cos(K._degToRad(360*(100-a.series.donutArcPercent)/100/2.1)))/2:1)},_renderAdditionalElements:function(a,c,e,b,d,f){},_getProperLabelRadius:function(a,c,e){var b,d,f=1,g=1;if(1===a.length)a[0].labelR=e;else{for(var n=0;n<a.length;n++){var r=Math.abs(Math.sin(a[n].angle));
a[n].left?f>=r&&(f=r,b=a[n]):g>=r&&(g=r,d=a[n])}b.labelR=d.labelR=e;this._calculateLabelR(b,a,c);this._calculateLabelR(d,a,c)}},_calculateLabelR:function(a,c,e){for(var b=a.index,d=c.length,f=a.labelR;!(c[b%d].left^c[(b+1)%d].left);)c[(b+1)%d].omit||(f=(Math.sin(c[b%d].angle)*f+(c[b%d].left?-e:e))/Math.sin(c[(b+1)%d].angle),f=f<a.labelR?a.labelR:f,c[(b+1)%d].labelR=f),b++;b=a.index;for(d=0===b?d-1:b-1;!(c[b].left^c[d].left);)c[d].omit||(f=(Math.sin(c[b].angle)*f+(c[b].left?e:-e))/Math.sin(c[d].angle),
f=f<a.labelR?a.labelR:f,c[d].labelR=f),b--,d--,b=0>b?b+c.length:b,d=0>d?d+c.length:d}})});