// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/supportClasses/SectionLayoutManager",["dojo/_base/declare","dojo/dom-style","./SectionContentFitModes","esri/dijit/geoenrichment/utils/FitUtil"],function(g,d,f,n){g=g(null,{section:null,constructor:function(a){this.section=a},getWidth:function(){return d.get(this.section.domNode,"width")},_widthInitializedFlag:!1,setWidth:function(a,b){b=b||{};var c=this._widthInitializedFlag?d.get(this.section.domNode,"width"):0;b&&b.previousDim&&(c=b.previousDim.w,
this._widthInitializedFlag=!0);d.set(this.section.domNode,"width",a+"px");this._widthInitializedFlag=this._widthInitializedFlag||1<a;this.section.hasFixedLayout?this.section.getTables().forEach(function(c){(c.getMaxWidth()!==a||b.forceResize)&&c.setMaxWidth(a,{resizeToFitAllowedWidth:b.resizeContentToFit,preserveRightOffset:b.preserveRightOffset})}):this._widthInitializedFlag&&b&&b.resizeContentProportionally&&c&&a&&c!==a&&this.scaleFloatingContentProportionally({xScale:a/c,yScale:1})},getHeight:function(a){if(!this.section.hasFixedLayout)return 0;
var b=0;this.section._stackElements.forEach(function(c){switch(c.stackId){case "table":b+=c.getHeight(a);c.isLocatorTable()&&(b+=c.getLocatorTablePreviewExtraHeight());break;case "hr":b+=d.get(c,"height");break;case "pageBreak":b+=d.get(c,"height")}});return b},getResizedHeight:function(){return this.section.hasFixedLayout?this.getHeight(!0):d.get(this.section.domNode,"height")},_resizedHeightInitializedFlag:!1,_setResizedHeight:function(a,b){if(this.section.hasFixedLayout){var c=this.section.getLastTable();
c&&c.setSpaceAfter(a-this.getHeight())}c=this._resizedHeightInitializedFlag?d.get(this.section.domNode,"height"):0;b&&b.previousDim&&(c=b.previousDim.h,this._resizedHeightInitializedFlag=!0);d.set(this.section.domNode,"height",a+"px");this._resizedHeightInitializedFlag=this._resizedHeightInitializedFlag||1<a;!this.section.hasFixedLayout&&b&&b.resizeContentProportionally&&c&&a&&c!==a&&this.scaleFloatingContentProportionally({xScale:1,yScale:a/c})},setResizedHeight:function(a,b){this._setResizedHeight(a,
b);if(this.section.hasFixedLayout){var c=this;this.section.getTables().forEach(function(a){a.needScaleToFitHeight()&&c._scaleFixedTableToFitHeight(a)})}},updateHeightAfterContentChange:function(){this.section.hasFixedLayout&&this._setResizedHeight(this.getResizedHeight())},scaleFloatingContentProportionally:function(a){this.section.hasFixedLayout||1===a.xScale&&1===a.yScale||this.section._stackElements.forEach(function(b){switch(b.stackId){case "table":b.scaleProportionallyWithinParent(a);break;case "img":b.scaleProportionallyWithinParent(a)}})},
getFloatingContentBox:function(){var a,b,c,e;function d(d){a=Math.min(a,d.l);b=Math.min(b,d.t);c=Math.max(c,d.l+d.w);e=Math.max(e,d.t+d.h)}b=a=Infinity;e=c=0;this.section._stackElements.forEach(function(a){switch(a.stackId){case "table":d(a.getTableBox());break;case "img":d(a.getImageBox(!1))}});return{l:a,t:b,w:c-a,h:e-b}},fitContentNicely:function(a,b){a=a||{};this.section.hasFixedLayout?this._fitFixedTablesNicely(a,b):this._fitFloatingContentNicely(a,b)},_fitFixedTablesNicely:function(a,b){if(a.fitMode!==
f.NONE){a.fitMode===f.ALL&&delete a.fitMode;var c=this;(b||this.section.getTables()).forEach(function(b){"table"===b.stackId&&(a.fitMode!==f.WIDTH&&a.fitMode||b.resizeToFitAllowedWidth(),a.fitMode!==f.HEIGHT&&a.fitMode||c._scaleFixedTableToFitHeight(b))});this.section._notifyContentChanged()}},_scaleFixedTableToFitHeight:function(a){a.resizeToFitHeight(this.section.getResizedHeight());a.setSpaceAfter(0)},_fitFloatingContentNicely:function(a,b){var c=a.fitMode;if(c!==f.NONE){var e=this.getFloatingContentBox();
b=b||this.section._stackElements;if(b.length){var g,l;if(1!==b.length||"img"!==b[0].stackId||b[0].isMapImage()){c===f.SINGLE_ALL_COMPLEX_WIDTH&&(c=1<b.length?f.WIDTH:f.ALL);var h=0;1<b.length?h=5:this.section.hasInfographic()?h=this.section.viewModel.getStaticInfographicDefaultStyles(this.section.theme).padding||0:this.section.getTables()[0]&&this.section.isImageTable(this.section.getTables()[0])?h=0:this.section.hasChart()||this.section.hasInfographic()||(h=this.section.viewModel.getCurrentTheme(this.section.theme).table.dataTablePadding||
0);var p=this.section.getWidth()-2*h,m=d.get(this.section.domNode,"height")-2*h;1<b.length&&e.h>m&&(c=f.ALL);var k={xScale:c===f.HEIGHT?1:p/e.w,yScale:c===f.WIDTH?1:m/e.h};g=h-e.l*k.xScale;l=h-e.t*k.yScale}else c=n.fitBox(e,{w:this.section.getWidth()-0,h:d.get(this.section.domNode,"height")-0},{hAlign:"center",vAlign:"middle"}),k={xScale:c.ratio,yScale:c.ratio},g=0+c.x-e.l*k.xScale,l=0+c.y-e.t*k.yScale;b.forEach(function(a){switch(a.stackId){case "table":a.scaleProportionallyWithinParent(k);a.setGridPosition(g+
a.getLeft(),l+a.getTop());break;case "img":a.scaleProportionallyWithinParent(k),d.set(a.domNode,{left:g+d.get(a.domNode,"left")+"px",top:l+d.get(a.domNode,"top")+"px"})}})}}},getPreferredHeight:function(){var a=this.section.getInfographicWithTable();if(!a||!a.infographic.getPreferredHeight)return 0;var b=a.table.getTableBox(),c=b.t,b=this.getResizedHeight()-b.t-b.h,a=a.infographic.getPreferredHeight()||0;return c+b+a}});g.IMAGE_FIT_PRETTY_OFFSET=0;return g});