// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/tasks/FeatureSet","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../lang ../graphic ../SpatialReference ../graphicsUtils ../geometry/Polygon ../geometry/jsonUtils ../symbols/jsonUtils".split(" "),function(e,q,r,w,x,y,t,m,z,A,c,B){e=e(null,{declaredClass:"esri.tasks.FeatureSet",constructor:function(a,b){if(a){q.mixin(this,a);var u=this.features,d=a.spatialReference,d=this.spatialReference=c.createInstance(m.simpleConstructor,d),n=c.getGeometryType(a.geometryType);
this.geometryType=a.geometryType;a.fields&&(this.fields=a.fields);var g=c.supportsLazyUnquantization(this.geometryType),e=c.unquantizeFunction(this.geometryType,this.transform),h=!!(b&&g&&e),f=n&&(h?n.accessorConstructor:n.simpleConstructor);r.forEach(u,function(a,b){var l=c.createInstance(t.simpleConstructor),p=a.geometry;if(n&&p){var k=l.geometry=c.createInstance(f,h?null:p);k.setSpatialReference(p.spatialReference?c.createInstance(m.simpleConstructor,p.spatialReference):d);h&&k.setupLazyUnquantization(e,
p)}l.symbol=a.symbol?B.fromJson(a.symbol):null;l.attributes=a.attributes;u[b]=l});h||this._hydrate()}else this.features=[]},displayFieldName:null,geometryType:null,spatialReference:null,fieldAliases:null,toJson:function(a){var b={};this.displayFieldName&&(b.displayFieldName=this.displayFieldName);this.fields&&(b.fields=this.fields);this.spatialReference?b.spatialReference=this.spatialReference.toJson():this.features[0]&&this.features[0].geometry&&(b.spatialReference=this.features[0].geometry.spatialReference.toJson());
this.features[0]&&(this.features[0].geometry&&(b.geometryType=c.getJsonType(this.features[0].geometry)),b.features=z._encodeGraphics(this.features,a));b.geometryType=b.geometryType||this.geometryType;b.exceededTransferLimit=this.exceededTransferLimit;b.transform=this.transform;return y.fixJson(b)},_hydrate:function(){c.unquantize(this.features,this.geometryType,this.transform);this.transform=null},quantize:function(a){if(!this.geometryType)return this.transform=null,this;var b=a.translate[0],c=a.translate[1],
d=a.scale[0],e=a.scale[1],g=this.features,m=function(a,b,c){var k,l,d,e,f,h,g=[];k=0;for(l=a.length;k<l;k++)if(d=a[k],0<k){if(h=b(d[0]),d=c(d[1]),h!==e||d!==f)g.push([h-e,d-f]),e=h,f=d}else e=b(d[0]),f=c(d[1]),g.push([e,f]);return 0<g.length?g:null},h=function(a,b,d){if("esriGeometryPoint"===a)return function(a){a.x=b(a.x);a.y=d(a.y);return a};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){var c,e,f,h,g;f=a.rings||a.paths;g=[];c=0;for(e=f.length;c<e;c++)h=f[c],(h=m(h,
b,d))&&g.push(h);return 0<g.length?(a.rings?a.rings=g:a.paths=g,a):null};if("esriGeometryMultipoint"===a)return function(a){var c;c=m(a.points,b,d);return 0<c.length?(a.points=c,a):null};if("esriGeometryEnvelope"===a)return function(a){return a}}(this.geometryType,function(a){return Math.round((a-b)/d)},function(a){return Math.round((c-a)/e)}),f,v;f=0;for(v=g.length;f<v;f++)g[f].geometry&&(h(g[f].geometry)||g[f].setGeometry(null));this.transform=a;return this}});e.createGraphics=function(a){var b=
a.geometryType,e=c.createInstance(m.simpleConstructor,a.spatialReference),d=c.getGeometryType(b).accessorConstructor,n=c.unquantizeFunction(b,a.transform);return r.map(a.features,function(a,b){var h=c.createInstance(t.simpleConstructor),f=a.geometry;if(f){var g=h.geometry=c.createInstance(d);g.setSpatialReference(e);g.setupLazyUnquantization(n,f)}h.attributes=a.attributes;return h})};e.createPolygon=function(a,b,e){var d;a&&(d=c.createInstance(A.accessorConstructor),d.setSpatialReference(b),b=c.unquantizeFunction("esriGeometryPolygon",
e),d.setupLazyUnquantization(b,a));return d};w("extend-esri")&&q.setObject("tasks.FeatureSet",e,x);return e});