// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/GraphicsLayer","require dojo/_base/declare dojo/_base/Deferred dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/_base/window dojo/dom-attr dojo/dom-construct dojo/dom-style dojo/dom dojox/gfx dojox/gfx/matrix ./gfxSniff!esri-svg?dojox/gfx/filters ./layer ./support/webglUtils ./support/WebGLSurface ../kernel ../lang ../sniff ../Color ../domUtils ../symbols/MarkerSymbol ../symbols/SimpleMarkerSymbol ../symbols/utils ../geometry/Point ../geometry/ScreenPoint ../geometry/Extent ../geometry/mathUtils ../geometry/screenUtils ../PluginTarget ./gfxSniff!esri-svg?dojox/gfx/svgext".split(" "),
function(ga,G,ha,q,u,r,X,S,N,w,ia,H,J,E,P,T,ja,z,Y,A,ka,O,oa,F,Z,aa,U,K,ba,V,la){var L=-1!==H.renderer.toLowerCase().indexOf("svg"),M=-1!==H.renderer.toLowerCase().indexOf("canvas"),W=M?"canvas-2d":H.renderer,x=9>A("ie");X=10===A("ie");var ca=void 0===A("ie")&&7==A("trident"),ma=X||ca,da=A("esri-touch"),ea=!!A("chrome"),Q=T.isWebGLEnabled(),I=Q||M;T=G(null,{declaredClass:"esri.layers._GraphicsContainer",_setMap:function(a,b){var c,d=this._connects=[];this._map=a;this._useWillChange="css-transforms"===
a.navigationMode&&L&&A("esri-will-change");I?(c=N.create("div",{style:{position:"absolute",overflow:"visible"}},b),this._surface={getEventSource:function(){return c}},M&&(d.push(q.connect(c,"onmousedown",this,this._canvasDownHandler)),d.push(q.connect(c,"onmouseup",this,this._canvasUpHandler)),d.push(q.connect(c,"onclick",this,this._canvasClickHandler))),Q&&(this._webglSurface=new ja({map:a,node:c}))):(c=(this._surface=H.createSurface(b,a.width,a.height)).getEventSource(),this._useWillChange&&w.set(c,
"will-change","transform"),w.set(c=x?c.parentNode:c,{overflow:"visible",position:"absolute"}));d.push(q.connect(a,"onResize",this,"_onResizeHandler"));this._useWillChange&&(d.push(q.connect(a,"onPan",this,"_onPanHandler")),d.push(q.connect(a,"onPanEnd",this,"_onPanEndHandler")),d.push(q.connect(a,"onExtentChange",this,"_onExtentChangeHandler")));return c},_reorderLayer:function(a,b,c){b=b.getEventSource();I&&"svg"===a.surfaceType&&(b=b.parentNode);N.place(b,this._surface.getEventSource(),c)},_onPanHandler:function(a,
b){var c=this._map.__visibleRect,d=c.x+b.x,c=c.y+b.y;this._panDx=d;this._panDy=c;I||w.set(this._surface.getEventSource(),z._css.names.transform,z._css.translate(d,c))},_onPanEndHandler:function(a,b){var c=this._map.__visibleRect,d=c.x,c=c.y;this._panDx=d;this._panDy=c;I||w.set(this._surface.getEventSource(),z._css.names.transform,z._css.translate(d,c))},_onExtentChangeHandler:function(a,b,c,d){c&&(this._panDy=this._panDx=0,I||w.set(this._surface.getEventSource(),z._css.names.transform,z._css.translate(0,
0)))},_getTransform:function(){return{dx:this._panDx||0,dy:this._panDy||0}},_onResizeHandler:function(a,b,c){a=this._surface.getEventSource();var d=this._map,e;x&&w.set(a=a.parentNode,{width:b+"px",height:c+"px",clip:"rect(0px "+b+"px "+c+"px 0px)"});S.set(a,"width",b);S.set(a,"height",c);this._surface.declaredClass||r.forEach(a.childNodes,function(a){S.set(a,"width",b);S.set(a,"height",c)});d.loaded&&(d.graphics.suspended||(d.graphics._resized=!0),r.forEach(d.graphicsLayerIds,function(a){e=d.getLayer(a);
e.suspended||(e._resized=!0,e._childLayer&&(e._childLayer._resized=!0));e._updateSVGFilters(null,null,b,c)}),d.graphics._updateSVGFilters(null,null,b,c),d._labels&&d._labels._updateSVGFilters(null,null,b,c))},_cleanUp:function(){r.forEach(this._connects,q.disconnect,q);this._map=this._surface=null},_processEvent:function(a){var b=this._map;a.screenPoint=new U(a.pageX-b.position.x,a.pageY-b.position.y);a.mapPoint=b.toMap(a.screenPoint)},_canvasDownHandler:function(a){this._processEvent(a);this._downPt=
a.screenPoint.x+","+a.screenPoint.y},_canvasUpHandler:function(a){this._processEvent(a);this._upPt=a.screenPoint.x+","+a.screenPoint.y},_tolerance:15,_isPrimaryMatch:function(a,b,c,d){if(!a.visible||!b)return!1;var e=b.getTransformedBoundingBox(),f;return e?(f=new K(e[0].x,e[0].y,e[2].x,e[2].y),delete f.spatialReference,da?f.intersects(c):f.contains(d)):r.some(b.children||[],function(a){e=a.getTransformedBoundingBox();f=new K(e[0].x,e[0].y,e[2].x,e[2].y);delete f.spatialReference;return da?f.intersects(c):
f.contains(d)})},_canvasClickHandler:function(a){if(this._downPt&&this._upPt&&this._downPt===this._upPt){this._processEvent(a);var b=this._map,c=r.map(b.graphicsLayerIds,function(a){return b.getLayer(a)});c.push(b.graphics);c.reverse();var c=r.filter(c,function(a){return a.loaded&&!a.hasWebGLSurface()&&a._mouseEvents&&!a.suspended&&(!Y.isDefined(a.opacity)||0<a.opacity)}),d=a.screenPoint,e=this._tolerance,f=d.x-e,g=d.y+e,h=d.x+e,e=d.y-e,k=new K(f,e,h,g),f=b.toMap(new U(f,g)),h=b.toMap(new U(h,e)),
g=f.spatialReference._getInfo(),l=new K(K.prototype._normalizeX(f.x,g).x,f.y,K.prototype._normalizeX(h.x,g).x,h.y,f.spatialReference),m;delete k.spatialReference;r.some(c,function(a){a=r.filter(a.graphics,function(a){return this._isPrimaryMatch(a,a.getDojoShape(),k,d)||!(!a._bgShape||!this._isPrimaryMatch(a,a._bgShape,k,d))},this);a.reverse();if(0<a.length){var c;r.some(a,function(a){return a.geometry&&l.intersects(a.geometry)?(c=a,!0):!1});if(c)return m=c,!0}return!1},this);m&&(c=m.getLayer())&&
(a.graphic=m,c.onClick(a))}}});P=G(P,{declaredClass:"esri.layers._GraphicsLayer",managedSuspension:!0,surfaceType:W,webglEnabled:Q,renderer:null,_eventMap:{"graphic-add":["graphic"],"graphic-remove":["graphic"],"renderer-change":["renderer"]},_suspendGraphics:!1,constructor:function(a,b){a=a||{};if(u.isString(a)||u.isObject(a)&&(a.layerDefinition||a.query))a=b;this._params=u.mixin({displayOnPan:!0,drawMode:!0,styling:!0},a);var c=this._params.dataAttributes;"string"===typeof c&&(c=[c]);this.styling=
L?this._params.styling:!0;this.dataAttributes=c;this.infoTemplate=a&&a.infoTemplate;this.graphics=[];this._draw=u.hitch(this,this._draw);this._refresh=u.hitch(this,this._refresh);this._acquireSVGMarker=u.hitch(this,this._acquireSVGMarker);this._evalSurfaceType=u.hitch(this,this._evalSurfaceType);this._setSurfaceType=u.hitch(this,this._setSurfaceType);this.setWebGLEnabled(null!=this._params.webglEnabled?this._params.webglEnabled:this.webglEnabled);this.registerConnectEvents()},getNode:function(){return this._div&&
this._div.getEventSource()},setDrawMode:function(a){this._params.drawMode=a},suspendGraphics:function(a){this._suspendGraphics=a;r.forEach(this.graphics,function(b){b._suspended=a})},setWebGLEnabled:function(a){var b=this.webglEnabled;this.webglEnabled=(a||!1)&&Q;b!==this.webglEnabled&&(this._evalSurfaceType(),this.onWebGLEnabledChange())},hasWebGLSurface:function(){return"webgl"===this.surfaceType},_getSurfaceType:function(a){return a&&"webgl"===a.surfaceType?"webgl":W},_evalSurfaceType:function(a){Q&&
(a?this._setSurfaceType():null==this._evalSurfaceTimerHandle&&(this._evalSurfaceTimerHandle=setTimeout(this._setSurfaceType,0)))},_hasPendingSurfaceEval:function(){return!!this._evalSurfaceTimerHandle},_setSurfaceType:function(){clearTimeout(this._evalSurfaceTimerHandle);this._evalSurfaceTimerHandle=null;var a=this._canUseWebGLSurface()?"webgl":W;this.surfaceType!==a?(this.surfaceType=a,this._handleSurfaceChange(),this.onSurfaceChange()):this._pendingRedraw&&this._redraw()},_handleSurfaceChange:function(){this._cancelWebGLDepsLoad();
this._webglDepsPromise=this._prepareToAttach(this._map);this._webglDepsPromise.always(u.hitch(this,function(a){this._webglDepsPromise=null;a&&"cancel"===a.dojoType||this._evalSurface()}))},_cancelWebGLDepsLoad:function(){this._webglDepsPromise&&!this._webglDepsPromise.isFulfilled()&&this._webglDepsPromise.cancel();this._webglDepsPromise=null},_evalSurface:function(){var a=this._map,b=this._div;a&&b&&this._getSurfaceType(b)!==this.surfaceType&&(a._detachGraphicsLayer(this),a._attachGraphicsLayer(this))},
_canUseWebGLSurface:function(a){a=a||this._map;return this.webglEnabled&&(!a||a.webglEnabled&&(a.ownsWebGLContext(this)||a.isWebGLContextAvailable()))&&this._params.drawMode&&this._isWebGLCompatible()},_isWebGLCompatible:function(){return!1},_prepareToAttach:function(a){var b=new ha;!this.webglDeps&&this._canUseWebGLSurface(a)?ga(["./support/webglDeps"],u.hitch(this,function(a){this.webglDeps=a;b.isFulfilled()||b.resolve()})):b.resolve();return b.promise},_setMap:function(a,b){this.inherited(arguments);
this._map=a;this._evalSurfaceType(!0);this._webglChangeMapHandle=a.on("webgl-enabled-change",u.hitch(this,function(){this._evalSurfaceType()}));this._wrap=a.wrapAround180;this._srInfo=a.spatialReference._getInfo();this._svgFilters={};this._lineMarkers={};if(this.hasWebGLSurface())a.acquireWebGLContext(this),this._div=a._gc._webglSurface.createRenderer(this.webglDeps.WebGLRenderer,a.width,a.height,this);else{if("svg"===this.surfaceType)if(I){b=H.createSurface(b.getEventSource(),a.width,a.height);var c=
b.getEventSource();w.set(c,{position:"absolute",overflow:"visible",pointerEvents:"none"});this._map._gc._useWillChange&&w.set(c,"will-change","transform");this._div=b.createGroup();w.set(this._div.getEventSource(),"pointer-events","auto")}else this._div=b.createGroup();else b=H.createSurface(b.getEventSource(),a.width,a.height),w.set(b.rawNode,"position","absolute"),this._div=b.createGroup(),this._renderProto=this._div.constructor.prototype._render,this._div._render=u.hitch(this,this._canvasRender);
this._bgGroup=this._div.createGroup()}this._div.getEventSource().id=this.id+"_layer";this._initOpacity();return this._div},_unsetMap:function(a,b){a.releaseWebGLContext(this);"webgl"===this._div.surfaceType?a._gc._webglSurface.destroyRenderer(this._div):(r.forEach(this.graphics,function(a){a._shape=null}),"svg"===this.surfaceType?I?(b=this._div.parent,this._div.clear(),b.remove(this._div),N.destroy(this._div.getEventSource()),N.destroy(b.getEventSource())):(this._div.clear(),b.remove(this._div),N.destroy(this._div.getEventSource())):
(b=this._div.getParent(),b._parent={},N.destroy(b.rawNode),b.destroy()));this._map=this._div=this._svgFilters=this._lineMarkers=null;this._pendingRedraw=!1;clearTimeout(this._wakeTimer);this._wakeTimer=null;clearTimeout(this._evalSurfaceTimerHandle);this._evalSurfaceTimerHandle=null;this._webglChangeMapHandle&&this._webglChangeMapHandle.remove();this._cancelWebGLDepsLoad();this._disableDrawConnectors();this.inherited(arguments)},_initOpacity:function(){var a=this.opacity;Y.isDefined(a)&&1>a&&this.setOpacity(a,
!0)},_onZoomStartHandler:function(){this.hasWebGLSurface()||O.hide(this._div.getEventSource())},_onExtentChangeHandler:function(a,b,c,d){clearTimeout(this._wakeTimer);this._wakeTimer=null;c?(a=this._map.__visibleRect,b=this._div,this._evalSDRenderer(),this._refresh(!0),this._params._child||this._updateTransform(b,a.x,a.y,!0),this._renderProto&&b.surface.pendingRender?this._dirty=!0:this.suspended||O.show(b.getEventSource())):this._resized&&(this._resized=!1,this._refresh(!1));if(0<this.graphics.length)this.onUpdate()},
_canvasRender:function(){var a=this._div;this._dirty&&(delete this._dirty,this.suspended||O.show(a.getEventSource()));return this._renderProto.apply(a,arguments)},_refresh:function(a){if(!this.hasWebGLSurface()){var b=this.graphics,c=b.length,d,e=this._draw;for(d=0;d<c;d++)e(b[d],a)}},refresh:function(){this._refresh(!0)},_redraw:function(){this._pendingRedraw=!1;this.hasWebGLSurface()?this._div&&this._div.redraw():this._refresh(!0)},redraw:function(){this._hasPendingSurfaceEval()?this._pendingRedraw=
!0:this._redraw()},_getTransform:function(){var a={dx:0,dy:0};this._map&&(this._map._gc._useWillChange?a=this._map._gc._getTransform():this._div&&!this.hasWebGLSurface()&&(a=this._div.getTransform()));return a},_onPanHandler:function(a,b){this._panDx=b.x;this._panDy=b.y;var c=this._map.__visibleRect;this._updateTransform(this._div,c.x+b.x,c.y+b.y);ca&&this._updateSVGMarkers()},_onPanEndUpdateHandler:function(a,b){var c=this._map.__visibleRect;this._params._child||b.x===this._panDx&&b.y===this._panDy?
(this._updateSVGFilters(-c.x,-c.y),this._updateSVGMarkers()):this._updateTransform(this._div,c.x,c.y,!0);this._refresh(!1);if(this.graphics.length)this.onUpdate()},_onPanStartHandler:function(){O.hide(this._div.getEventSource())},_onPanEndHandler:function(){var a=this._map.__visibleRect,b=this._div;this._updateTransform(b,a.x,a.y,!0);this._refresh(!1);this._renderProto&&b.surface.pendingRender?this._dirty=!0:O.show(b.getEventSource());if(this.graphics.length)this.onUpdate()},_updateTransform:function(a,
b,c,d){this.hasWebGLSurface()||(this._map._gc._useWillChange?I&&w.set(this._div.parent.getEventSource(),z._css.names.transform,z._css.translate(b,c)):a.setTransform(J.translate({x:b,y:c})),d&&(this._updateSVGFilters(-b,-c),this._updateSVGMarkers()))},onSuspend:function(){this.inherited(arguments);O.hide(this._div.getEventSource());clearTimeout(this._wakeTimer);this._wakeTimer=null;this._disableDrawConnectors()},onResume:function(a){this.inherited(arguments);a.firstOccurrence&&this._evalSDRenderer();
this._enableDrawConnectors();this._wakeTimer=this._wakeTimer||setTimeout(u.hitch(this,function(){this.suspended||this._map.__zooming||this._onExtentChangeHandler(null,null,!0)}),0)},_enableDrawConnectors:function(){var a=this._map,b=q.connect;this._disableDrawConnectors();this._params.displayOnPan?(this._params._child||(this._onPanHandler_connect=b(a,"onPan",this,"_onPanHandler")),this._onPanEndHandler_connect=b(a,"onPanEnd",this,"_onPanEndUpdateHandler")):(this._onPanStartHandler_connect=b(a,"onPanStart",
this,"_onPanStartHandler"),this._onPanEndHandler_connect=b(a,"onPanEnd",this,"_onPanEndHandler"));this._onZoomStartHandler_connect=b(a,"onZoomStart",this,"_onZoomStartHandler");this._onExtentChangeHandler_connect=b(a,"onExtentChange",this,"_onExtentChangeHandler")},_disableDrawConnectors:function(){var a=q.disconnect;a(this._onExtentChangeHandler_connect);a(this._onZoomStartHandler_connect);a(this._onPanHandler_connect);a(this._onPanStartHandler_connect);a(this._onPanEndHandler_connect);this._onExtentChangeHandler_connect=
this._onZoomStartHandler_connect=this._onPanHandler_connect=this._onPanStartHandler_connect=this._onPanEndHandler_connect=null},_updateExtent:function(a){var b=a.geometry;if(!b)a._extent=null;else if(!(a._extent=b.getExtent())){var c,d;if("esri.geometry.Point"===b.declaredClass)c=b.x,d=b.y;else if("esri.geometry.Multipoint"===b.declaredClass)c=b.points[0][0],d=b.points[0][1];else{a._extent=null;return}a._extent=new K(c,d,c,d,b.spatialReference)}},_intersects:function(a,b,c){var d=a.spatialReference,
e=b.spatialReference,f=d&&e&&!d.equals(e)&&d._canProject(e)&&4326===e.wkid;if(this._wrap&&!c){c=[];var d=a._getFrameWidth(),g=this._srInfo,h=a._clip?a._getAvailExtent():a.extent,k,l,m,p,n=[];k=b._partwise;f&&(h=a.geographicExtent,g=e._getInfo());a=h._getParts(g);if(k&&k.length)for(b=[],e=0,f=k.length;e<f;e++)b=b.concat(k[e]._getParts(g));else b=b._getParts(g);e=0;for(f=b.length;e<f;e++)for(m=b[e],g=0,h=a.length;g<h;g++)if(p=a[g],p.extent.intersects(m.extent))for(k=0,l=m.frameIds.length;k<l;k++)c.push((p.frameIds[0]-
m.frameIds[k])*d);e=0;for(f=c.length;e<f;e++)k=c[e],r.indexOf(c,k)===e&&n.push(k);return n.length?n:null}return(f?a.geographicExtent:a.extent).intersects(b)?[0]:null},_defaultMarker:{type:"simplemarkersymbol",style:"square",size:1,xoffset:0,yoffset:0,angle:0},_draw:function(a,b){if(!this.hasWebGLSurface()&&this._params.drawMode&&this._map&&!this.suspended&&!this._map.__zooming&&!this._resized)try{var c=a._extent,d,e,f=!L||this.styling,g=L&&this.dataAttributes,h=a.getDojoShape(),k;if(!a._suspended&&
a.visible&&c&&(d=this._intersects(this._map,c,a.geometry._originOnly))&&(e=f?this._getSymbol(a):this._defaultMarker)){if(a._offsets&&a._offsets.join(",")===d.join(",")?k=!0:a._offsets=d,!h||b||!k){var l=a.geometry.type,c={graphic:a},m=a._bgShape,p=f&&!a.symbol?this._getRenderer(a):null,n=p&&p.backgroundFillSymbol;if("point"===l)this._isInvalidShape(e,h)&&this._removeShape(a),a._shape=this._drawPoint(this._div,a.geometry,e,a.getDojoShape(),d,p,a),f&&this._symbolizePoint(a.getDojoShape(),e,p,a);else if("multipoint"===
l)this._drawMarkers(a,e,d,p),f&&this._symbolizeMarkers(a,e,p);else{var t,l=e,D,B,R;f&&(l=(t="simplemarkersymbol"===e.type||"picturemarkersymbol"===e.type||"textsymbol"===e.type?e:null)?n:e);f&&l&&-1<l.type.indexOf("fillsymbol")&&(D=this._bgGroup,R=!(!D||!t));m&&!R&&this._removeBgShape(a);if(l){!R&&(this._isInvalidShape(l,a._shape)||a._shape&&a._shape._isCentroidMarker)&&this._removeShape(a,!1);if(B=this._drawShape(a,d,D||this._div,R?m:a.getDojoShape()))B._isCentroidMarker=!1;f&&this._symbolizeShape(B,
l,p,l===n,a);a[R?"_bgShape":"_shape"]=B}if(t){(this._isInvalidShape(t,a._shape)||a._shape&&!a._shape._isCentroidMarker)&&this._removeShape(a,!1);var fa=a.geometry.getCentroid();if(B=fa&&this._drawPoint(this._div,fa,t,a._shape,d,p,a))B._isCentroidMarker=!0,this._symbolizePoint(B,t,p,a);a._shape=B}}M||(a._bgShape&&this._initNode(a,a._bgShape,a._bgShape!==m,c,g),a._shape&&this._initNode(a,a._shape,a._shape!==h,c,g));a._applyDataAttrs();c.node=a.getNode();this.onGraphicDraw(c)}}else h&&this._removeShape(a)}catch(na){this._errorHandler(na,
a)}},_initNode:function(a,b,c,d,e){if(b=b&&b.getNode())b.e_graphic=a,this._addDataAttrs(a,e,b),c&&(d.node=b,this.onGraphicNodeAdd(d))},_removeShape:function(a,b,c){var d=a.getDojoShape(),e=d&&d.getNode();d&&!c&&(d.removeShape(),d.destroy());a._shape=a._offsets=null;!1!==b&&this._removeBgShape(a,c);if(e&&(e.e_graphic=null,!M))this.onGraphicNodeRemove({graphic:a,node:e})},_removeBgShape:function(a,b){var c=a._bgShape,d=c&&c.getNode();c&&!b&&(c.removeShape(),c.destroy());a._bgShape=null;if(d&&(d.e_graphic=
null,!M))this.onGraphicNodeRemove({graphic:a,node:d})},_addDataAttrs:function(a,b,c){var d=a.attributes,e,f=b?b.length:0,g=this._getRenderer(a);if(c&&d){for(e=0;e<f;e++)(c=b[e])&&a.attr("data-"+c,d[c]);!this.styling&&g&&(g.getBreakIndex?(b=g.getBreakIndex(a),a.attr("data-class-break",-1!==b?b:null)):g.getUniqueValueInfo&&(b=g.getUniqueValueInfo(a),a.attr("data-unique-value",b?b.value:null)))}},_drawShape:function(a,b,c,d){a=a.geometry;var e=a.type,f=this._map,g=f.extent,h=f.width,k=f.height,f=f.__visibleRect,
l=[],m,p;m="extent"===e;if("rect"===e||m)l={x:0,y:0,spatialReference:a.spatialReference},l.x=m?a.xmin:a.x,l.y=m?a.ymax:a.y,e=V.toScreenPoint(g,h,k,l),l.x=m?a.xmax:a.x+a.width,l.y=m?a.ymin:a.y+a.height,a=V.toScreenPoint(g,h,k,l),b={x:e.x-f.x+b[0],y:e.y-f.y,width:Math.abs(a.x-e.x),height:Math.abs(a.y-e.y)},0===b.width&&(b.width=1),0===b.height&&(b.height=1),d=this._drawRect(c,d,b);else if("polyline"===e||"polygon"===e){m=0;for(p=b.length;m<p;m++)l=l.concat(V._toScreenPath(g,h,k,a,-f.x+b[m],-f.y));d=
this._drawPath(c,d,l);this._rendererLimits&&("polyline"===e?this._clipPolyline(d,a):this._clipPolygon(d,a))}return d},_drawRect:function(a,b,c){return b?b.setShape(c):a.createRect(c)},_drawImage:function(a,b,c){return b?b.setShape(c):a.createImage(c)},_drawCircle:function(a,b,c){return b?b.setShape(c):a.createCircle(c)},_drawPath:function(){return x?function(a,b,c,d){c=d?c:c.join(" ");if(b)return b.setShape(c);b=a.createObject(d?H.Path:H.EsriPath,c);a._overrideSize(b.getEventSource());return b}:function(a,
b,c,d){c=d?c:c.join(" ");return b?b.setShape(c):a.createPath(c)}}(),_drawText:function(a,b,c){return b?b.setShape(c):a.createText(c)},_evalSDRenderer:function(a){var b=this._map,c=this.renderer,d,e=this._rndForScale;b&&b.loaded&&c&&c.getRendererInfo&&(d="zoom"===c.rangeType?c.getRendererInfoByZoom(b.getZoom()):c.getRendererInfoByScale(b.getScale()));this._rndForScale=d&&d.renderer;a||this._rndForScale==e||this.emit("renderer-change",{renderer:this._rndForScale})},_getRenderer:function(a){var b=this._rndForScale||
this.renderer;a&&b&&b.getObservationRenderer&&(b=b.getObservationRenderer(a));return b},_getSymbol:function(a){var b=this._getRenderer();return a.symbol||b&&b.getSymbol(a)},_getVariable:function(a,b,c){var d;a&&(d=(a=a.getVisualVariablesForType(b,c))&&a[0]);return d},_applyOpacity:function(a,b,c,d){b=b.getOpacity(d,{opacityInfo:c});null!=b&&(a=new ka(a),a.a=b);return a},_symbolizeShape:function(a,b,c,d,e){var f=b.getStroke(),g=b.getFill(),h=b.type,k,l,m=-1!==h.indexOf("linesymbol"),p=-1!==h.indexOf("fillsymbol")?
null:this._getVariable(c,"sizeInfo",!1),n=this._getVariable(c,"colorInfo",!1),t=this._getVariable(c,"opacityInfo",!1),D=m?"none"!==b.style:b.outline&&"none"!==b.outline.style,B=m?null:this._getVariable(c,"sizeInfo","outline"),p=(p=d?B:B||p)?c.getSize(e,{sizeInfo:p,resolution:this._map.getResolutionInMeters(),scale:this._map.getScale()}):null;d&&(n=t=null);(n||t)&&"picturefillsymbol"!==h&&(m?(k=f&&f.color,n&&(k=c.getColor(e,{colorInfo:n})||k),k&&t&&(k=this._applyOpacity(k,c,t,e))):g&&g.toCss&&(l=g,
n&&(l=c.getColor(e,{colorInfo:n})||l),l&&t&&(l=this._applyOpacity(l,c,t,e))));a.setStroke(!D||null==p&&!k?f:u.mixin({},f,null!=p?{width:p}:null,k&&{color:k})).setFill(l||g);m&&Z.applyLineMarker(a,b,k,this._acquireSVGMarker)},_smsToPath:function(){return x?function(a,b,c,d,e,f,g,h,k){switch(b){case a.STYLE_SQUARE:return["M",e+","+g,"L",f+","+g,f+","+h,e+","+h,"X","E"];case a.STYLE_CROSS:return["M",c+","+g,"L",c+","+h,"M",e+","+d,"L",f+","+d,"E"];case a.STYLE_X:return["M",e+","+g,"L",f+","+h,"M",e+
","+h,"L",f+","+g,"E"];case a.STYLE_DIAMOND:return["M",c+","+g,"L",f+","+d,c+","+h,e+","+d,"X","E"];case a.STYLE_TARGET:return["M",e+","+g,"L",f+","+g,f+","+h,e+","+h,e+","+g,"M",e-k+","+d,"L",e+","+d,"M",c+","+(g-k),"L",c+","+g,"M",f+k+","+d,"L",f+","+d,"M",c+","+(h+k),"L",c+","+h,"E"]}}:function(a,b,c,d,e,f,g,h,k){switch(b){case a.STYLE_SQUARE:return["M",e+","+g,f+","+g,f+","+h,e+","+h,"Z"];case a.STYLE_CROSS:return["M",c+","+g,c+","+h,"M",e+","+d,f+","+d];case a.STYLE_X:return["M",e+","+g,f+","+
h,"M",e+","+h,f+","+g];case a.STYLE_DIAMOND:return["M",c+","+g,f+","+d,c+","+h,e+","+d,"Z"];case a.STYLE_TARGET:return["M",e+","+g,f+","+g,f+","+h,e+","+h,e+","+g,"M",e-k+","+d,e+","+d,"M",c+","+(g-k),c+","+g,"M",f+k+","+d,f+","+d,"M",c+","+(h+k),c+","+h]}}}(),_pathStyles:{square:1,cross:1,x:1,diamond:1,target:1},_typeMaps:{picturemarkersymbol:"image",picturefillsymbol:"path",simplefillsymbol:"path",simplelinesymbol:"path",cartographiclinesymbol:"path",textsymbol:"text"},_isInvalidShape:function(a,
b){var c=b&&b.shape&&b.shape.type,d=a&&a.type,e=a&&a.style;"rect"===c&&(c="path");d&&(e=this._typeMaps[d]||e);this._pathStyles[e]&&(e="path");return"shieldlabelsymbol"===d?!0:!(!c||!e||c===e)},_reArialFont:/\s*(^|,)\s*arial\s*(,|$)\s*/i,_fallbackFont:"Arial",_drawPoint:function(a,b,c,d,e,f,g){var h=c.type,k=this._map,l=k.__visibleRect,m=V.toScreenPoint(k.extent,k.width,k.height,b).offset(-l.x+e[0],-l.y),l=m.x,p=m.y,n;b=[];var t,D=this._getVariable(f,"rotationInfo",!1),D=D?f.getRotationAngle(g,{rotationInfo:D}):
null,B=this._getVariable(f,"sizeInfo",!1),k=B?f.getSize(g,{sizeInfo:B,shape:c.style,resolution:k.getResolutionInMeters(),scale:k.getScale()}):g.size;D&&b.push(J.rotategAt(D,m));if(0!==c.xoffset||0!==c.yoffset)t=J.translate(c.xoffset,-c.yoffset),b.push(t);0!==c.angle&&b.push(J.rotategAt(c.angle,m));if("simplemarkersymbol"===h)switch(n=c.style,f=Math.round,k=null!=k?k:c.size,n){case F.STYLE_SQUARE:case F.STYLE_CROSS:case F.STYLE_X:case F.STYLE_DIAMOND:c=isNaN(k)?16:k/2;n=this._drawPath(a,d,this._smsToPath(F,
n,l,p,f(l-c),f(l+c),f(p-c),f(p+c)));break;case F.STYLE_TARGET:g=c._targetWidth/2;m=c._targetHeight/2;n=this._drawPath(a,d,this._smsToPath(F,n,l,p,f(l-g),f(l+g),f(p-m),f(p+m),c._spikeSize));break;case F.STYLE_PATH:n=this._drawPath(a,d,c.path,!0);c=n.getBoundingBox();a=this._getScaleMatrix(c,k);1===a.xx&&1===a.yy||b.push(J.scaleAt(a.xx,a.yy,m));b.push(J.translate(-(c.x+c.width/2)+l,-(c.y+c.height/2)+p));break;default:c=isNaN(k)?16:k/2,n=this._drawCircle(a,d,{cx:l,cy:p,r:c})}else if("shieldlabelsymbol"===
h)n=c.width,m=c.height,d=a.createGroup(),n=a.createImage({x:l-n/2,y:p-m/2,width:n,height:m,src:c.url}),d.add(n),null!=c.font&&(p+=.2*c.getHeight(),a=a.createText({type:"text",text:c.text,x:l,y:p,align:"middle",decoration:c.decoration,rotated:c.rotated,kerning:c.kerning}),a.setFont(c.font),a.setFill(c.color),d.add(a)),n=d;else if("picturemarkersymbol"===h){if(null==k?(n=c.width,m=c.height):(m=k,n=c.width/c.height*m,t&&(null!=t.dx&&(t.dx=t.dx/c.width*n),null!=t.dy&&(t.dy=t.dy/c.height*m))),n=this._drawImage(a,
d,{x:l-n/2,y:p-m/2,width:n,height:m,src:c.url}),L&&(a=n.getNode()))c=(c=this._getVariable(f,"opacityInfo",!1))?f.getOpacity(g,{opacityInfo:c}):null,null!=c?a.setAttribute("opacity",c):a.setAttribute("opacity",1)}else if("textsymbol"===h){if(f=c.font){n=null!=k;g=f.family&&!this._reArialFont.test(f.family);if(n||g)f=new f.constructor(f.toJson());n&&f.setSize(k);g&&f.setFamily(f.family+","+this._fallbackFont)}n=this._drawText(a,d,{type:"text",text:c.text,x:l,y:p,align:c.getSVGAlign(),decoration:c.decoration||
f&&f.decoration,rotated:c.rotated,kerning:c.kerning});f&&n.setFont(f);L&&(a=n.getNode(),l=c.getSVGBaseline(),p=c.getSVGBaselineShift(),a&&(a.setAttribute("dominant-baseline",l),p&&a.setAttribute("baseline-shift",p),this._applyHalo(n,c.haloColor,c.haloSize)))}n.setTransform(J.multiply(b));n._wrapOffsets=e;return n},_acquireSVGMarker:function(a,b,c,d){a=this._getSVGMarkerId(b,d);var e=this._getSVGMarker(a);e||(e=Z.createSVGMarker(b,a,c,d),this._div.getParent().defNode.appendChild(e),this._lineMarkers[a]=
e);return e},_getSVGMarkerId:function(a,b){return"marker_"+this._map.id+"_"+a.r+"_"+a.g+"_"+a.b+"_"+b},_getSVGMarker:function(a){return this._lineMarkers[a]},_updateSVGMarkers:function(){if(L&&ma){var a=this._lineMarkers,b;for(b in a){var c=a[b];c.setAttribute("id",b+"_temp");c.setAttribute("id",b)}}},_applyHalo:function(a,b,c){var d=b&&c?this._getHaloId(b,c):null;a.setFilter(b&&c?A("webkit")||A("ff")?this._getDilateFilter(b,c,d):this._getOffsetFilter(b,c,d):null)},_getDilateFilter:function(a,b,c){var d=
this._getSVGFilter(c);d||(d=this._createSVGFilter({id:c},[E.feMorphology({operator:"dilate",radius:b,result:"dilated"}),E.feFlood({"flood-color":a.toCss(!0)}),E.feComposite({in2:"dilated",operator:"in",result:"composite"}),E.feMerge("composite","SourceGraphic")]));return d},_getOffsetFilter:function(a,b,c){var d=this._getSVGFilter(c);if(!d){a=a.toCss(!0);var d=this._offsetPrimitives,e,f=d.length,g=[],h=[];for(e=0;e<f;e++){var k=d[e],l="offset"+k.dir,m="composite"+k.dir;h.push(m);g.push(E.feOffset({dx:k.dx*
b,dy:k.dy*b,"in":"SourceAlpha",result:l}),E.feFlood({"flood-color":a}),E.feComposite({in2:l,operator:"in",result:m}))}h.push("SourceGraphic");g.push(E.feMerge.apply(E.feMerge,h));d=this._createSVGFilter({id:c},g)}return d},_offsetPrimitives:[{dir:"L",dx:-1,dy:0},{dir:"TL",dx:-1,dy:-1},{dir:"T",dx:0,dy:-1},{dir:"TR",dx:1,dy:-1},{dir:"R",dx:1,dy:0},{dir:"BR",dx:1,dy:1},{dir:"B",dx:0,dy:1},{dir:"BL",dx:-1,dy:1}],_getHaloId:function(a,b){return"halo_"+this._map.id+"_"+this.id+"_"+a.r+"_"+a.g+"_"+a.b+
"_"+a.a+"_"+b},_getSVGFilter:function(a){return this._svgFilters[a]},_createSVGFilter:function(a,b){var c=E.createFilter(a,b),d=this._map,e=d.__visibleRect;c.x=-e.x;c.y=-e.y;c.width=d.width;c.height=d.height;return this._svgFilters[a.id]=c},_updateSVGFilters:function(a,b,c,d){var e=this._svgFilters,f,g,h;for(g in e)if(f=e[g]){if(h=ia.byId(g))null!=a&&h.setAttribute("x",a),null!=b&&h.setAttribute("y",b),null!=c&&h.setAttribute("width",c),null!=d&&h.setAttribute("height",d);null!=a&&(f.x=a);null!=b&&
(f.y=b);null!=c&&(f.width=c);null!=d&&(f.height=d)}},_getScaleMatrix:function(a,b){var c=a.width/a.height,d=1,e=1;isNaN(b)||(1<c?(d=b/a.width,e=b/c/a.height):(e=b/a.height,d=b*c/a.width));return{xx:d,yy:e}},_symbolizePoint:function(a,b,c,d){var e=b.type,f=b.style;if("shieldlabelsymbol"!==e&&"picturemarkersymbol"!==e){var g=b.getStroke();b=b.getFill();var f=f===F.STYLE_X||f===F.STYLE_CROSS,h=g&&g.color,k=f?h:b;if(c){var l=this._getVariable(c,"colorInfo",!1),m=this._getVariable(c,"opacityInfo",!1);
l&&(k=c.getColor(d,{colorInfo:l})||k);k&&m&&(k=this._applyOpacity(k,c,m,d));k&&(f?k!==h&&(g=g?u.mixin({},g):{},g.color=k):k!==b&&(b=k))}"textsymbol"===e?a.setFill(b):"simplemarkersymbol"===e&&a.setFill(b).setStroke(g)}},_drawMarkers:function(a,b,c,d){var e=a.geometry,f=e.points,g=a.getDojoShape()||this._div.createGroup(),h,k,l=f.length,m=[],p=0,n,t=c?c.length:0;g.children[0]&&this._isInvalidShape(b,g.children[0])&&g.clear();for(k=0;k<l;k++)for(h=f[k],n=0;n<t;n++)m[0]=c[n],this._drawPoint(g,{x:h[0],
y:h[1],spatialReference:e.spatialReference},b,g.children[p++],m,d,a);b=g.children.length;if(l*c.length<b)for(k=b-1;k>=l*c.length;k--)g.children[k].removeShape();a._shape=g},_symbolizeMarkers:function(a,b,c){var d=a.getDojoShape().children,e,f=d.length;for(e=0;e<f;e++)this._symbolizePoint(d[e],b,c,a)},_errorHandler:function(a,b){a.message=b?"Unable to draw graphic (geometry:"+(b.geometry?b.geometry.declaredClass:null)+", symbol:"+(b.symbol?b.symbol.declaredClass:null)+"): "+a.message:"Unable to draw graphic (null): "+
a.message;this.inherited(arguments)},_rendererLimits:function(){var a,b,c;x?(a=1E5,b=-1E5,c=1E5):A("chrome")&&6>A("chrome")&&(a=8150,b=-1E4,c=1E4);if(a)return{clipLimit:a,rangeMin:b,rangeMax:c,clipBBox:[-a,-a,a,a],clipSegments:[[[-a,-a],[a,-a]],[[a,-a],[a,a]],[[a,a],[-a,a]],[[-a,a],[-a,-a]]]}}(),_clipPolyline:function(a,b){var c=this._getCorners(a,b),d=c.br,e=this._rendererLimits,f=e.rangeMin,g=e.rangeMax,h=e.clipBBox,k=e.clipSegments,e=this._isPointWithinRange,l=this._isPointWithinBBox,m=this._getClipperIntersection,
p=this._getPlaneIndex;if(!e(c.tl,f,g)||!e(d,f,g)){x&&this._createSegments(a);var n=[];r.forEach(a.segments,function(a){a=a.args;var c=a.length,b=[],d;for(d=0;d<c;d+=2){var e=[a[d],a[d+1]],f=[a[d+2],a[d+3]],g=l(e,h),C=l(f,h);if(g^C){if(C=m([e,f],k))g?(d?b.push(C[1]):b.push(e,C[1]),n.push(b),b=[]):b.push(C[1],f)}else g?d?b.push(f):b.push(e,f):(C=p(e,h),g=p(f,h),-1!==C&&-1!==g&&C!==g&&(e=m([e,f],k,!0),0<e.length&&(e[C]||(C=e[C[0]]?C[0]:C[1]),e[g]||(g=e[g[0]]?g[0]:g[1]),f=e[C],e=e[g],f&&b.push(f),e&&
(b.push(e),n.push(b),b=[]))))}n.push(b)});a.setShape(this._getPathStringFromPaths(n))}},_clipPolygon:function(a,b){var c=this._getCorners(a,b),d=c.br,e=this._rendererLimits,f=e.clipLimit,g=e.rangeMin,h=e.rangeMax,k=e.clipBBox,l=e.clipSegments,e=this._isPointWithinRange,m=this._isPointWithinBBox,p=this._getClipperIntersection,n=this._getPlaneIndex,t=ba._pointLineDistance;e(c.tl,g,h)&&e(d,g,h)||(x&&this._createSegments(a),c=r.filter(a.segments,function(a){return a.args&&a.args.length}),c=r.map(c,function(a){var b=
a.args,c=b.length,d=[];a=[];var e;for(e=0;e<c;e+=2){var g=[b[e],b[e+1]],h=[b[e+2],b[e+3]];if(e===c-2){d.push(g);break}var y=m(g,k),v=m(h,k);d.push(g);if(y^v){if(v=p([g,h],l))g=v[1],g[y?"inOut":"outIn"]=!0,d.push(g),a.push([y?"INOUT":"OUTIN",d.length-1,v[0]])}else if(!y){var y=n(g,k),q=n(h,k);-1!==y&&-1!==q&&y!==q&&(v=p([g,h],l,!0),0<v.length?(v[y]||(y=v[y[0]]?y[0]:y[1]),v[q]||(q=v[q[0]]?q[0]:q[1]),g=v[y],h=v[q],g&&(g.outIn=!0,d.push(g),a.push(["OUTIN",d.length-1,y])),h&&(h.inOut=!0,d.push(h),a.push(["INOUT",
d.length-1,q]))):u.isArray(y)&&u.isArray(q)&&(v=y.concat(q),v.sort(),"0123"===v.join("")&&(v=[],3===y[0]+y[1]?v.push([f,-f],[-f,f]):v.push([-f,-f],[f,f]),y=t(v[0],[g,h]),g=t(v[1],[g,h]),d.push(y<g?v[0]:v[1]))))}}var w=k[0],x=k[1],z=k[2],A=k[3];r.forEach(d,function(a){a[0]<w&&(a[1]>=x&&a[1]<=A?a[0]=w:(a[0]=w,a[1]=a[1]<x?x:A))});r.forEach(d,function(a){a[1]<x&&(a[0]>=w&&a[0]<=z?a[1]=x:(a[1]=x,a[0]=a[0]<w?w:z))});r.forEach(d,function(a){a[0]>z&&(a[1]>=x&&a[1]<=A?a[0]=z:(a[0]=z,a[1]=a[1]<x?x:A))});r.forEach(d,
function(a){a[1]>A&&(a[0]>=w&&a[0]<=z?a[1]=A:(a[1]=A,a[0]=a[0]<w?w:z))});b=0;c=a.length;if(0<c){do{h=a[b];e=a[(b+1)%c];if(h[2]===e[2]&&"INOUT"===h[0]&&"OUTIN"===e[0])if(g=h[1],e=e[1],g<e)for(g+=1;g<e;g++)d[g][2]=!0;else if(g>e){for(g+=1;g<d.length;g++)d[g][2]=!0;for(g=0;g<e;g++)d[g][2]=!0}b=(b+1)%c}while(0!==b)}c=d[0];b=d[d.length-1];c[2]&&(b[2]=!0,r.some(a,function(a){return 1===a[1]?(d.splice(d.length-1,0,u.clone(d[1])),!0):!1}));d=r.filter(d,function(a){return a[2]?!1:!0});for(b=0;b<d.length-1;b++)c=
d[b],(e=d[b+1])&&c[0]===e[0]&&c[1]===e[1]&&(e.outIn?c.outIn=!0:e.inOut&&(c.inOut=!0),d.splice(b+1,1));c=Math.abs;a=[];for(b=0;b<d.length-1;b++){h=d[b];g=h[0];h=h[1];y=c(g)===f;v=c(h)===f;e=d[b+1];q=e[0];e=e[1];var D=c(q)===f,E=c(e)===f;y&&E?a.push([b+1,[g,e]]):v&&D&&a.push([b+1,[q,h]])}for(b=a.length-1;0<=b;b--)e=a[b],g=d[e[0]-1],c=d[e[0]],g.outIn||g.inOut||c.outIn||c.inOut||d.splice(e[0],0,e[1]);c=d[0];b=d[d.length-1];c[0]===b[0]&&c[1]===b[1]||d.push(c);return d}),a.setShape(this._getPathStringFromPaths(c)))},
_getCorners:function(a,b){if(x){var c=this._map,d=b.getExtent(),e=d.spatialReference,f=c.toScreen(new aa(d.xmin,d.ymax,e)),c=c.toScreen(new aa(d.xmax,d.ymin,e));return{tl:f,br:c}}f=a.getTransformedBoundingBox();return{tl:f[0],br:f[2]}},_createSegments:function(a){a.shape.path=a.vmlPath;a.segmented=!1;a._confirmSegmented();var b=a.segments;1<b.length&&(a.segments=r.filter(b,function(a,b,e){b=e[b+1];return"M"===a.action&&b&&"L"===b.action?(a.args=a.args.concat(b.args),!0):!1}))},_getPathStringFromPaths:function(a){x?
(a=r.map(a,function(a){return"m "+r.map(a,function(a,b){return(1===b?"l ":"")+a.join(",")}).join(" ")}),a.push("e")):a=r.map(a,function(a){return"M "+r.map(a,function(a){return a.join(",")}).join(" ")});return a.join(" ")},_isPointWithinBBox:function(a,b){var c=b[1],d=b[2],e=b[3],f=a[0],g=a[1];return f>b[0]&&f<d&&g>c&&g<e?!0:!1},_isPointWithinRange:function(a,b,c){var d=a.x;a=a.y;return d<b||a<b||d>c||a>c?!1:!0},_getClipperIntersection:function(a,b,c){var d,e=ba._getLineIntersection2,f=Math.round,
g={length:0};for(d=0;4>d;d++){var h=e(a,b[d]);if(h)if(h[0]=f(h[0]),h[1]=f(h[1]),c)g[d]=h,g.length++;else return[d,h]}return c?g:null},_getPlaneIndex:function(a,b){var c=a[0],d=a[1],e=b[0],f=b[1],g=b[2],h=b[3];return c<=e?d>=f&&d<=h?3:d<f?[0,3]:[2,3]:d<=f?c>=e&&c<=g?0:c<e?[3,0]:[1,0]:c>=g?d>=f&&d<=h?1:d<f?[0,1]:[2,1]:d>=h?c>=e&&c<=g?2:c<e?[3,2]:[1,2]:-1},onGraphicAdd:function(){},onGraphicRemove:function(){},onGraphicNodeAdd:function(){},onGraphicNodeRemove:function(){},onGraphicDraw:function(){},
onGraphicsClear:function(){},onRendererChange:function(){},onOpacityChange:function(){},onInfoTemplateChange:function(){},onSurfaceChange:function(){},onWebGLEnabledChange:function(){},setInfoTemplate:function(a){this.infoTemplate=a;this._evalSurfaceType();this.onInfoTemplateChange()},add:function(a,b){if(a._graphicsLayer===this)return a;a._suspended=this._suspendGraphics;b||this.graphics.push(a);a._graphicsLayer=this;a._sourceLayer||(a._layer&&"esri.layers.GraphicsLayer"!==a._layer.declaredClass?
a._sourceLayer=a._layer:"esri.layers.GraphicsLayer"!==this.declaredClass&&(a._sourceLayer=this));a._layer=this;this.hasWebGLSurface()||(this._updateExtent(a),this._draw(a));if(!b)this.onGraphicAdd(a);return a},remove:function(a,b,c){if(!b&&!c){b=this.graphics;var d;if(-1===(d=r.indexOf(b,a)))return null;if(!ea||64<=ea)b.splice(d,1);else{var e=b.length;if(e){for(;d<e;)b[d]=b[d+1],d++;b.length--}}}this.hasWebGLSurface()||a.getDojoShape()&&this._removeShape(a,null,c);a._shape=a._graphicsLayer=null;this.onGraphicRemove(a);
return a},clear:function(a,b){var c=this.graphics,d,e=!x;for(d=c.length-1;0<=d;d--)this.remove(c[d],null,e);this.graphics=[];this.hasWebGLSurface()||this._destroyAllNodes();if(!b)this.onGraphicsClear()},_destroyAllNodes:function(){if(!x&&this._div){var a;this._childLayer&&(a=this._childLayer.getNode())&&a.parentNode&&a.parentNode.removeChild(a);this._bgGroup.clear();this._div.clear();this._bgGroup=this._div.createGroup();a&&this._div.getEventSource().appendChild(a);this._initOpacity()}},clearNodes:function(){if(!this.hasWebGLSurface()){var a=
this.graphics,b=a.length,c;for(c=0;c<b;c++)this._removeShape(a[c],!0,!0);this._destroyAllNodes()}},_setIEOpacity:function(a,b){var c=a&&a.getNode();if(c){var d=a.strokeStyle,e=c.stroke;d&&e&&(e.opacity=d.color.a*b);d=a.fillStyle;e=c.fill;d&&e&&("tile"===e.type?w.set(c,"opacity",b):e.opacity=d.a*b)}},setOpacity:function(a,b){if(b||this.opacity!=a){var c=this._div;c&&!this.hasWebGLSurface()&&(x?(r.forEach(this.graphics,function(b){this._setIEOpacity(b._shape,a);this._setIEOpacity(b._bgShape,a)},this),
c._esriIeOpacity=a,this._bgGroup._esriIeOpacity=a):"canvas-2d"===this.surfaceType?w.set(c.getEventSource(),"opacity",a):c.getEventSource().setAttribute("opacity",a));this.opacity=a;if(!b)this.onOpacityChange(a)}},setRenderer:function(a){this.renderer=a;this._evalSDRenderer(!0);this._evalSurfaceType();this.emit("renderer-change",{renderer:this._rndForScale||a})}});G=G([P,la],{declaredClass:"esri.layers.GraphicsLayer",constructor:function(){this.enableMouseEvents=u.hitch(this,this.enableMouseEvents);
this.disableMouseEvents=u.hitch(this,this.disableMouseEvents);this._processEvent=u.hitch(this,this._processEvent);this._initLayer()},_initLayer:function(){this.loaded=!0;this.onLoad(this)},_setMap:function(){var a=this.inherited("_setMap",arguments);this.enableMouseEvents();return a},_unsetMap:function(){this.disableMouseEvents();this.inherited("_unsetMap",arguments)},_processEvent:function(a){var b=this._map,c=a.target,d;a.screenPoint=new U(a.pageX-b.position.x,a.pageY-b.position.y);for(a.mapPoint=
b.toMap(a.screenPoint);c&&!(d=c.e_graphic);)c=c.parentNode;if(d)return a.graphic=d,a},_onMouseOverHandler:function(a){if(this._processEvent(a))this.onMouseOver(a)},_onMouseMoveHandler:function(a){if(this._processEvent(a))this.onMouseMove(a)},_onMouseDragHandler:function(a){if(this._processEvent(a))this.onMouseDrag(a)},_onMouseOutHandler:function(a){if(this._processEvent(a))this.onMouseOut(a)},_onMouseDownHandler:function(a){this._downGr=this._downPt=null;this._processEvent(a)&&(q.disconnect(this._onmousemove_connect),
q.disconnect(this._onmousedrag_connect),this._onmousedrag_connect=q.connect(this._div.getEventSource(),"onmousemove",this,"_onMouseDragHandler"),this._downGr=a.graphic,this._downPt=a.screenPoint.x+","+a.screenPoint.y,this.onMouseDown(a))},_onMouseUpHandler:function(a){this._upGr=this._upPt=null;this._processEvent(a)&&(q.disconnect(this._onmousedrag_connect),q.disconnect(this._onmousemove_connect),this._onmousemove_connect=q.connect(this._div.getEventSource(),"onmousemove",this,"_onMouseMoveHandler"),
this._upGr=a.graphic,this._upPt=a.screenPoint.x+","+a.screenPoint.y,this.onMouseUp(a))},_onClickHandler:function(a){if(this._processEvent(a)){var b=this._downGr,c=this._upGr;b&&c&&b===c&&this._downPt===this._upPt&&(x&&(z._ieGraphic=a.graphic),this.onClick(a))}},_onDblClickHandler:function(a){if(this._processEvent(a))this.onDblClick(a)},onMouseOver:function(){},onMouseMove:function(){},onMouseDrag:function(){},onMouseOut:function(){},onMouseDown:function(){},onMouseUp:function(){},onClick:function(){},
onDblClick:function(){},enableMouseEvents:function(){if(!this._mouseEvents){var a=q.connect,b=this._div.getEventSource();M||(this._onmouseover_connect=a(b,"onmouseover",this,"_onMouseOverHandler"),this._onmousemove_connect=a(b,"onmousemove",this,"_onMouseMoveHandler"),this._onmouseout_connect=a(b,"onmouseout",this,"_onMouseOutHandler"),this._onmousedown_connect=a(b,"onmousedown",this,"_onMouseDownHandler"),this._onmouseup_connect=a(b,"onmouseup",this,"_onMouseUpHandler"),this._onclick_connect=a(b,
"onclick",this,"_onClickHandler"),this._ondblclick_connect=a(b,"ondblclick",this,"_onDblClickHandler"));this._mouseEvents=!0}},disableMouseEvents:function(){if(this._mouseEvents){var a=q.disconnect;a(this._onmouseover_connect);a(this._onmousemove_connect);a(this._onmousedrag_connect);a(this._onmouseout_connect);a(this._onmousedown_connect);a(this._onmouseup_connect);a(this._onclick_connect);a(this._ondblclick_connect);this._mouseEvents=!1}}});G._GraphicsContainer=T;G._GraphicsLayer=P;A("extend-esri")&&
(u.setObject("layers.GraphicsLayer",G,z),u.setObject("layers._GraphicsContainer",T,z),u.setObject("layers._GraphicsLayer",P,z));return G});