// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/OnDemandMode","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/has ../kernel ../geometry/Point ../tasks/query ./RenderMode ./GridLayout".split(" "),function(p,n,t,q,v,w,x,u,y,z){p=p([y],{declaredClass:"esri.layers._OnDemandMode",constructor:function(a){this.featureLayer=a;this._featureMap={}},initialize:function(a){this.inherited(arguments);var b=this.featureLayer,c=b._srInfo;this._gridLayer=new z(new x(c?c.valid[0]:a.extent.xmin,c?c.valid[1]:a.extent.ymax,
a.spatialReference),{width:b._tileWidth,height:b._tileHeight},{width:a.width,height:a.height},c);this._cellMap={};this._gridLayer.setResolution(a.extent)},startup:function(){if(!this._started||this._isSuspendedAtStartup)this.inherited(arguments),this._ioQueue=[],this._isSuspendedAtStartup=this.featureLayer.suspended,this.featureLayer.suspended||(this._zoomHandler(),this._enableConnectors())},propertyChangeHandler:function(a){this._init&&(2>a?this._zoomHandler():console.log("FeatureLayer: layer in on-demand mode does not support time definitions. Layer id \x3d "+
this.featureLayer.id+", Layer URL \x3d "+this.featureLayer.url))},destroy:function(){this._disableConnectors();this._processIOQueue(!0);this.inherited(arguments)},drawFeature:function(a){var b=a.geometry,c=[];if(b){var c=this._gridLayer.getCellsInExtent("point"===b.type?{xmin:b.x,ymin:b.y,xmax:b.x,ymax:b.y}:b.getExtent(),!1).cells,b=this._cellMap,d,e,h=a.attributes[this.featureLayer.objectIdField],f,l,g;for(d=0;d<c.length;d++)e=c[d],f=e.latticeID,l=e.row,g=e.col,f?e=b[f]=b[f]||e:(b[l]=b[l]||{},e=
b[l][g]=b[l][g]||e),e.features=e.features||[],e.features.push(a),this._addFeatureIIf(h,a),this._incRefCount(h)}},suspend:function(){this._init&&this._disableConnectors()},resume:function(){this._init&&(this._enableConnectors(),this._zoomHandler())},refresh:function(){this._zoomHandler()},hasAllFeatures:function(){var a=!1,b=this._getCurrentCells(),c;for(c=0;c<b.length;c++)if(b[c].hasPartialFeatures){a=!0;break}return!a},hasUpdateError:function(){var a=!1,b=this._getCurrentCells(),c;for(c=0;c<b.length;c++)if(b[c].hasUpdateError){a=
!0;break}return a},_enableConnectors:function(){var a=this.map;this._zoomConnect=n.connect(a,"onZoomEnd",this,this._zoomHandler);this._panConnect=n.connect(a,"onPanEnd",this,this._panHandler);this._resizeConnect=n.connect(a,"onResize",this,this._panHandler)},_disableConnectors:function(){n.disconnect(this._zoomConnect);n.disconnect(this._panConnect);n.disconnect(this._resizeConnect)},_zoomHandler:function(){this._processIOQueue(!0);var a=this.featureLayer,b=this.map;!a.suspended&&a.isQueryable()&&
(a._fireUpdateStart(),this._clearIIf(),(a=a._trackManager)&&a.clearTracks(),this._cellMap={},this._gridLayer.setResolution(b.extent),this._sendRequest())},_panHandler:function(a){if(this.featureLayer.isQueryable()){this.featureLayer._fireUpdateStart();var b=this.featureLayer._resized;a=b?a:null;b&&this._gridLayer.setMapState(a,this.map.width,this.map.height);this._sendRequest(a)}},_sendRequest:function(a){this._exceeds=!1;var b=this.featureLayer,c=this.map;a=a||c.extent;c=this._gridLayer.getCellsInExtent(a,
b.latticeTiling).cells;if(!b.isEditable())var d=this._cellMap,c=q.filter(c,function(a){if(a.lattice){if(d[a.latticeID])return!1}else if(d[a.row]&&d[a.row][a.col])return!1;return!0});var e=b.getOutFields(),h=b.getDefinitionExpression(),f=b._getOffsettedTE(b._mapTimeExtent),l=b.supportsAdvancedQueries?b.getOrderByFields():null,g=this._ioQueue,r,m,k;this._pending=this._pending||0;for(r=0;r<c.length;r++){m=c[r];k=new u;k.geometry=m.extent||m.lattice;k.outFields=e;k.where=h;b.latticeTiling&&m.extent&&
(k.spatialRelationship=u.SPATIAL_REL_CONTAINS);k.returnGeometry=!0;k.timeExtent=f;b._ts&&(k._ts=(new Date).getTime());k.orderByFields=l;k.multipatchOption=b.multipatchOption;k.maxAllowableOffset=b._maxOffset;k.quantizationParameters=b._quantizationParameters;var n=b.advancedQueryCapabilities;n&&n.supportsQueryWithResultType&&(k.resultType="tile");this._pending++;g.push(b._task.execute(k,t.hitch(this,this._drawFeatures,m),t.hitch(this,this._queryErrorHandler,m)))}this._removeOldCells(a);this._endCheck()},
_drawFeatures:function(a,b){a.hasPartialFeatures=!!b.exceededTransferLimit;a.hasUpdateError=!1;this._exceeds=this._exceeds||b.exceededTransferLimit;this._finalizeIO();var c=this.featureLayer,d=this.map.extent,e=a.extent,h=a.row,f=a.col,l=c.objectIdField,g=b.features,n=this._gridLayer,m=this._cellMap,k=a.latticeID,m=k?m[k]:m[h]&&m[h][f];if(a.resolution==n._resolution&&(k?k===n.getLatticeID(d):n.intersects(e,d)))if(m)c._sortFeatures(g),this._updateCell(m,g);else for(c._sortFeatures(g),a.features=g,
this._addCellToCellMap(a),d=g.length,c=0;c<d;c++)e=g[c],h=e.attributes[l],this._addFeatureIIf(h,e),this._incRefCount(h);else m&&this._removeCell(h,f,k);this._endCheck()},_queryErrorHandler:function(a,b){this._finalizeIO();a.hasPartialFeatures=!0;a.hasUpdateError=!0;this._addCellToCellMap(a);this.featureLayer._errorHandler(b);this._endCheck(!0)},_finalizeIO:function(){this._pending--},_endCheck:function(a){if(0===this._pending){this._processIOQueue();var b=this.featureLayer,c=b._trackManager;c&&(c.clearTracks(),
c.addFeatures(b.graphics),b._ager&&q.forEach(b.graphics,function(a){a._shape&&b._repaint(a)}),c.moveLatestToFront(),c.drawTracks());this.featureLayer._fireUpdateEnd(a&&Error("FeatureLayer: an error occurred while updating the layer"),this._exceeds?{queryLimitExceeded:!0}:null);if(this._exceeds)b.onQueryLimitExceeded()}},_processIOQueue:function(a){this._ioQueue=q.filter(this._ioQueue,function(a){return-1<a.fired?!1:!0});a&&q.forEach(this._ioQueue,this._cancelPendingRequest)},_getCurrentCells:function(a){var b=
[];a=a||this._cellMap;for(var c in a)if(a.hasOwnProperty(c)){var d=a[c];d&&(d.hasOwnProperty("row")||d.hasOwnProperty("latticeID")?b.push(d):"object"===typeof d&&b.push.apply(b,this._getCurrentCells(d)))}return b},_addCellToCellMap:function(a){var b=this._cellMap;if(a.latticeID)b[a.latticeID]=a;else{var c=a.row,d=a.col;b[c]=b[c]||{};b[c][d]=a}},_removeOldCells:function(a){var b=this._cellMap,c=this._gridLayer,d,e;for(d in b)if(b[d]){var h=b[d],f=h.latticeID,l=0,g=0;if(f)l++,f!==c.getLatticeID(a)&&
(this._removeCell(null,null,f),g++);else for(e in h)h[e]&&(l++,c.intersects(h[e].extent,a)||(this._removeCell(d,e),g++));g===l&&delete b[d]}},_updateCell:function(a,b){var c=this.featureLayer,d=c.objectIdField,c=c._selectedFeatures,e,h=b.length;a.features=a.features||[];for(e=0;e<h;e++){var f=b[e],l=f.attributes[d],g=this._addFeatureIIf(l,f);g===f?(this._incRefCount(l),a.features.push(g)):l in c||(g.setGeometry(f.geometry),g.setAttributes(f.attributes))}},_removeCell:function(a,b,c){var d=this._cellMap,
e=this.featureLayer,h=e.objectIdField,f=c?d[c]:d[a]&&d[a][b];if(f&&(c?delete d[c]:delete d[a][b],a=f.features))for(b=0;b<a.length;b++)c=a[b].attributes[h],this._decRefCount(c),c in e._selectedFeatures||this._removeFeatureIIf(c)}});v("extend-esri")&&t.setObject("layers._OnDemandMode",p,w);return p});