// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/OnDemandDrillMode","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/has ../kernel ../promiseList ./RenderMode ../geometry/Extent ../geometry/jsonUtils ../tasks/query ../tasks/FeatureSet ./vectorTiles/core/promiseUtils ./vectorTiles/core/SetPool ./vectorTiles/layers/support/TileInfo ./vectorTiles/views/2d/tiling/TileInfoView ./vectorTiles/views/2d/tiling/TileQueue ./vectorTiles/views/2d/tiling/TileStrategy ./vectorTiles/views/2d/tiling/TileKey ./vectorTiles/geometry/SpatialReference".split(" "),
function(l,u,v,n,w,x,y,q,z,A,r,B,p,C,D,E,F,g,G){g=n("esri-featurelayer-webgl");var t=n("esri-mobile");l=l([y],{declaredClass:"esri.layers._OnDemandDrillMode",featureLayer:null,graphics:null,maxDrillLevel:g&&null!=g.maxDrillLevel?g.maxDrillLevel:t?1:2,maxRecordCountFactor:g&&null!=g.maxRecordCountFactor?g.maxRecordCountFactor:t?1:3,_graphicsVal:null,_reEvalGraphics:!1,_featureMap:null,_defaultTileSize:512,_quantizationFactor:1,_tileInfo:null,_tileInfoView:null,_tileFetchQueue:null,_tileStrategy:null,
_tileRequests:null,_wglRenderer:null,_wglView:null,_wglContainer:null,constructor:function(a){this._isTileFulfilled=this._isTileFulfilled.bind(this);this._graphicsVal=[];this._featureMap={};this.featureLayer=a},initialize:function(a){this.inherited(arguments);var c=new G(a.spatialReference.toJson());this._tileInfo=C.create({spatialReference:c,size:this._defaultTileSize});this._tileInfoView=new D(this._tileInfo);this._tileFetchQueue=new E({tileInfoView:this._tileInfoView,process:this._getFeatureSet.bind(this)});
this._tileStrategy=new F({cachePolicy:"purge",acquireTile:this._acquireTile.bind(this),releaseTile:this._releaseTile.bind(this),tileInfoView:this._tileInfoView});this._tileRequests=new Map},startup:function(){if(!this._started||this._isSuspendedAtStartup){this.inherited(arguments);var a=this.featureLayer;this._wglRenderer=a._div;this._wglView=this._wglRenderer._wglView;this._wglContainer=this._wglRenderer._wglContainer;this._wglView.initialize(this._tileInfoView);this._isSuspendedAtStartup=a.suspended;
this.start()}},propertyChangeHandler:function(a){this._init&&(2>a?this.start():console.log("FeatureLayer: layer in on-demand mode does not support time definitions. Layer id \x3d "+this.featureLayer.id+", Layer URL \x3d "+this.featureLayer.url))},destroy:function(){this._tileFetchQueue.clear();this._tileStrategy.destroy();this._tileRequests.clear();this.inherited(arguments)},update:function(a){this._tileFetchQueue.pause();this._tileFetchQueue.state=a.state;this._tileStrategy.update(a);this._tileFetchQueue.resume();
this._evalUpdateStatus()},suspend:function(){this._init&&this.stop()},resume:function(){this._init&&this.start()},refresh:function(){this.start()},hasAllFeatures:function(){var a=!1;this._tileRequests.forEach(function(c){c.hasPartialFeatures&&(a=!0)});return!a},hasUpdateError:function(){var a=!1;this._tileRequests.forEach(function(c){c.hasUpdateError&&(a=!0)});return a},start:function(){var a=this.featureLayer;!a.suspended&&a.isQueryable()&&(this._clearIIf(),this._tileFetchQueue.pause(),this._tileFetchQueue.clear(),
this._tileStrategy.clear(),this._wglRenderer.start())},stop:function(){this._wglRenderer.stop()},_evalUpdateStatus:function(){this._getCurrentTiles().every(this._isTileFulfilled)?this.featureLayer._fireUpdateEnd():this.featureLayer._fireUpdateStart()},_getCurrentTiles:function(){var a=[];this._tileStrategy.tileIndex.forEach(function(c,d,b){a.push(d)});return a},_isTileFulfilled:function(a){a=this._tileRequests.get(a);return!(!a||!a.isFulfilled)},_acquireTile:function(a){this.featureLayer._fireUpdateStart();
var c=this._wglView.acquireTile(a);a=this._tileFetchQueue.push(c.key).then(function(a){return this._wglRenderer._symbolProcessor.getTileData(c.key,a.featureSet).then(function(b){return{tileData:b.data,featureSet:a.featureSet,errors:a.errors}})}.bind(this)).then(function(a){c.setData(a.tileData,this._wglRenderer._hasVV,!1);this._addTile(c,a)}.bind(this)).otherwise(function(a){this._tileError(c);return B.reject(a)}.bind(this));this._tileRequests.set(c.key.id,{request:a,isFulfilled:!1,hasUpdateError:null,
hasPartialFeatures:null,featureSet:null,graphics:[]});return c},_releaseTile:function(a){this.featureLayer._fireUpdateStart();this._tileRequests.get(a.key.id)&&(this._removeTile(a),this._wglRenderer._scheduleUpdate())},_addTile:function(a,c){this._reEvalGraphics=!0;this._wglView.addChild(a);var d=this._createGraphics(c.featureSet);this._registerGraphics(d);var b=this._tileRequests.get(a.key.id);b&&(b.isFulfilled=!0,b.hasUpdateError=!!c.errors.length,b.hasPartialFeatures=b.hasUpdateError,b.featureSet=
c.featureSet,b.graphics=d)},_tileError:function(a){if(a=this._tileRequests.get(a.key.id))a.isFulfilled=!0,a.hasUpdateError=!0,a.hasPartialFeatures=!0,a.graphics=[];this._wglRenderer._scheduleUpdate()},_removeTile:function(a){var c=a.key.id,d=this._tileRequests.get(c);d.request.isFulfilled()||d.request.cancel();this._tileRequests["delete"](c);this._wglRenderer._cancelRedraw(c);this._reEvalGraphics=!0;this._wglView.releaseTile(a);this._unregisterGraphics(d.graphics)},_getFeatureSet:function(a){var c=
{hashes:new Set,drill:[],featureSet:{features:[],geometryType:this.featureLayer.geometryType,spatialReference:this.map.spatialReference.toJson(),transform:null},errors:[]},d=this.featureLayer._task,b=this._getResolutionParams(a),e=this._tileInfoView.getTileBounds([0,0,0,0],a),e=this._expandTileBounds(e,b),h=p.acquire();return this._drillQuery(c,h,d,e,b,null,a).then(function(a){p.release(h);this._calculateCentroid(a);return a}.bind(this)).otherwise(function(a){p.release(h);throw a;})},_getResolutionParams:function(a){this._tileInfo.updateTileInfo(a);
var c=this._tileInfo.lodAt(a.level);return{mode:"view",originPosition:"upperLeft",tolerance:this._quantizationFactor*c.resolution,extent:new q(a.extent[0],a.extent[1],a.extent[2],a.extent[3],this.map.spatialReference)}},_expandTileBounds:function(a,c){var d=this.featureLayer.geometryType,d=("esriGeometryPoint"===d||"esriGeometryMultipoint"===d||this._wglRenderer._returnCentroid?20:0)*c.tolerance;a[0]-=d;a[1]-=d;a[2]+=d;a[3]+=d;return a},_calculateCentroid:function(a){var c;if("esriGeometryPolygon"===
a.featureSet.geometryType&&this._wglRenderer._returnCentroid){c=0;var d=a.featureSet.spatialReference,b=a.featureSet.transform,e={geometry:{x:null,y:null}},h=[e];a.featureSet.features.forEach(function(a){if(!a.centroid){var f=a.geometry;f&&(f=r.createPolygon(f,d,b),f=f.getCentroid())&&(e.geometry.x=f.x,e.geometry.y=f.y,z.quantize(h,"esriGeometryPoint",b),a.centroid={x:e.geometry.x,y:e.geometry.y},c++)}})}return c},_drillQuery:function(a,c,d,b,e,h,m,f){f=null!=f?f:0;a.drill.push(b);return this._query(d,
b,e,h,m,f).then(function(k){this._appendFeatures(a.featureSet.features,c,k.features);k.transform&&(a.featureSet.transform=k.transform);if(k.exceededTransferLimit){if(f<this.maxDrillLevel){f++;k=(b[2]-b[0])/2;var g=(b[3]-b[1])/2,l=[b[0]+k,b[1]+g,b[2],b[3]],n=[b[0],b[1],b[2]-k,b[3]-g],p=[b[0]+k,b[1],b[2],b[3]-g];return x([this._drillQuery(a,c,d,[b[0],b[1]+g,b[2]-k,b[3]],e,h,m,f),this._drillQuery(a,c,d,l,e,h,m,f),this._drillQuery(a,c,d,n,e,h,m,f),this._drillQuery(a,c,d,p,e,h,m,f)]).then(function(){return a})}a.errors.push(Error("Max drill level reached! tileId: "+
m.id+", level: "+f))}return a}.bind(this)).otherwise(function(b){if(0<f)a.errors.push(b);else throw b;}.bind(this))},_appendFeatures:function(a,c,d){var b=a.length,e=d?d.length:0;a.length=b+e;var h=0,g,f,k,l=this.featureLayer.objectIdField;for(g=0;g<e;g++)f=d[g],k=f.attributes[l],c.has(k)||(a[b+h]=f,c.add(k),h++);a.length-=e-h},_query:function(a,c,d,b,e,g){e=this.featureLayer;b=new A;b.geometry=new q(c[0],c[1],c[2],c[3],this.map.spatialReference);b.outFields=e.getOutFields();b.where=e.getDefinitionExpression();
b.returnGeometry=!0;b.returnCentroid=this._wglRenderer._returnCentroid;b.timeExtent=e._getOffsettedTE(e._mapTimeExtent);e._ts&&(b._ts=Date.now());b.orderByFields=e.supportsAdvancedQueries?e.getOrderByFields():null;b.multipatchOption=e.multipatchOption;b.maxAllowableOffset="esriGeometryPolyline"===e.geometryType?d.tolerance:null;b.quantizationParameters=d;(c=e.advancedQueryCapabilities)&&c.supportsQueryWithResultType&&(b.resultType="tile");b.returnExceededLimitFeatures=g===this.maxDrillLevel;b.maxRecordCountFactor=
this.maxRecordCountFactor;return this._wrapInNewDeferred(a.rawExecute(b))},_wrapInNewDeferred:function(a){var c=new v(function(){a.isFulfilled()||a.cancel()});a.then(function(a){c.resolve(a)}).otherwise(function(a){c.reject(a)});return c.promise},_collectGraphics:function(){var a=this._featureMap,c=[],d;for(d in a)c.push(a[d]);return c},_createGraphics:function(a){return r.createGraphics(a)},_registerGraphics:function(a){var c=this.featureLayer.objectIdField;a.forEach(function(a){var b=a.attributes&&
a.attributes[c];this._registerFeature(b,a);this._incRefCount(b)}.bind(this))},_unregisterGraphics:function(a){var c=this.featureLayer.objectIdField;a.forEach(function(a){a=a.attributes&&a.attributes[c];this._decRefCount(a);this._unregisterFeature(a)}.bind(this))}});Object.defineProperty(l.prototype,"graphics",{get:function(){this._reEvalGraphics&&(this._reEvalGraphics=!1,this._graphicsVal=this._collectGraphics());return this._graphicsVal}});n("extend-esri")&&u.setObject("layers._OnDemandDrillMode",
l,w);return l});