// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/webgl/ShaderTranspiler",["require","exports","./reservedWordsGLSL3","./lib/glsl-tokenizer/string"],function(w,q,r,t){function u(c){return c.map(function(g){return"eof"!==g.type?g.data:""}).join("")}function n(c,g,f,b){b=b||f;for(var a=0;a<c.length;a++){var d=c[a];if("ident"===d.type&&d.data===f)return b in g?g[b]++:g[b]=0,n(c,g,b+"_"+g[b],b)}return f}function v(c,g,f){void 0===f&&(f="afterVersion");var b={data:"\n",type:"whitespace"},a=function(a){return a<c.length?
/[^\r\n]$/.test(c[a].data):!1},d=function(a){for(var b=-1,e=0,d=-1,g=0;g<a.length;g++){var c=a[g];"preprocessor"===c.type&&(c.data.match(/\#(if|ifdef|ifndef)\s+.+/)?++e:c.data.match(/\#endif\s*.*/)&&--e);("afterVersion"===f||"afterPrecision"===f)&&"preprocessor"===c.type&&/^#version/.test(c.data)&&(d=Math.max(d,g));if("afterPrecision"===f&&"keyword"===c.type&&"precision"===c.data){a:{for(c=g;c<a.length;c++){var h=a[c];if("operator"===h.type&&";"===h.data)break a}c=null}if(null===c)throw Error("precision statement not followed by any semicolons!");
d=Math.max(d,c)}b<d&&0===e&&(b=g)}return b+1}(c);a(d-1)&&c.splice(d++,0,b);for(var h=0;h<g.length;h++){var e=g[h];c.splice(d++,0,e)}a(d-1)&&a(d)&&c.splice(d,0,b)}Object.defineProperty(q,"__esModule",{value:!0});var p=["GL_OES_standard_derivatives","GL_EXT_frag_depth","GL_EXT_draw_buffers","GL_EXT_shader_texture_lod"];q.transpileShader=function(c,g){var f=t(c),b;a:{b="100";var a="300 es";void 0===b&&(b="100");void 0===a&&(a="300 es");for(var d=/^\s*\#version\s+([0-9]+(\s+[a-zA-Z]+)?)\s*/,h=0;h<f.length;h++){var e=
f[h];if("preprocessor"===e.type){var l=d.exec(e.data);if(l)if(d=l[1].replace(/\s\s+/g," "),d===a){b=d;break a}else if(d===b){e.data="#version "+a;break a}else throw Error("unknown glsl version: "+d);}}f.splice(0,0,{type:"preprocessor",data:"#version "+a},{type:"whitespace",data:"\n"});b=null}if("300 es"===b)throw Error("shader is already glsl 300 es");d=e=null;h={};l={};for(b=0;b<f.length;++b)switch(a=f[b],a.type){case "keyword":"vertex"===g&&"attribute"===a.data?a.data="in":"varying"===a.data&&(a.data=
"vertex"===g?"out":"in");break;case "builtin":/^texture(2D|Cube)(Proj)?(Lod|Grad)?(EXT)?$/.test(a.data.trim())&&(a.data=a.data.replace(/(2D|Cube|EXT)/g,""));if("fragment"===g&&"gl_FragColor"===a.data){if(!e){var e=n(f,h,"fragColor"),k=void 0;void 0===k&&(k="lowp");v(f,[{type:"keyword",data:"out"},{type:"whitespace",data:" "},{type:"keyword",data:k},{type:"whitespace",data:" "},{type:"keyword",data:"vec4"},{type:"whitespace",data:" "},{type:"ident",data:e},{type:"operator",data:";"}],"afterPrecision")}a.data=
e}else"fragment"===g&&"gl_FragDepthEXT"===a.data&&(d||(d=n(f,h,"gl_FragDepth")),a.data=d);break;case "ident":if(0<=r.indexOf(a.data)){if(k="vertex"===g)a:{for(k=b-1;0<=k;k--){var m=f[k];if("whitespace"!==m.type&&"block-comment"!==m.type)if("keyword"===m.type){if("attribute"===m.data||"in"===m.data){k=!0;break a}}else break}k=!1}if(k)throw Error("attribute in vertex shader uses a name that is a reserved word in glsl 300 es");a.data in l||(l[a.data]=n(f,h,a.data));a.data=l[a.data]}}for(b=f.length-1;0<=
b;--b)a=f[b],"preprocessor"===a.type&&((e=a.data.match(/\#extension\s+(.*)\:/))&&e[1]&&0<=p.indexOf(e[1].trim())&&(e=f[b+1],f.splice(b,e&&"whitespace"===e.type?2:1)),(e=a.data.match(/\#ifdef\s+(.*)/))&&e[1]&&0<=p.indexOf(e[1].trim())&&(a.data="#if 1"),(e=a.data.match(/\#ifndef\s+(.*)/))&&e[1]&&0<=p.indexOf(e[1].trim())&&(a.data="#if 0"));return u(f)}});