// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/chartUtils/builder/columnBarLine/_LineChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartTypes ../../ChartLineStyles ../../ChartLineMarkers ../../AxisUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder ../ChartPlots ../../../../themes/ReportThemes ./_AxisBuilder ./_PointLabelUtil".split(" "),function(C,t,y,v,D,E,A,F,G,H,I,z){var J={calcLineStyle:function(a,k,h,b){var e=b.comparisonInfo,g=b.visualProperties;k=t.calcColorForPoint(null,
a,0,k,h.length,y.LINE,b.themeSettings,a.isComparisonSeries,e);g=g.lineThickness||1;h=v.SOLID;b=void 0;a.isComparisonSeries&&e&&(e.lineThickness&&(g=e.lineThickness),e.lineStyle&&(h=e.lineStyle),b=e.lineMarker?D.getMarkerPath(e.lineMarker):t.getComparisonSymbol());return{color:k,width:g,style:v.toGFXValue(h),marker:b}}};return{calcSeriesLine:function(a){var k=a.chart,h=a.visualProperties,b=a.seriesItems,e=a.seriesItemsWithComparison||b,g=a.isSecondaryPlot,w=a.reverseXY,K=a.comparisonInfo,b=a.themeSettings,
r=a.viewModel,m=[],c={minYValue:Infinity,maxYValue:-Infinity,stackedValues:h.isStacked?[]:null},x=a.primaryPlotStat&&a.primaryPlotStat.pointIndexToTooltipsHash||{};e.forEach(function(b,p){if(b.points.length){var n=g?2*p+1:p,u=J.calcLineStyle(b,n,e,a),B={name:b.label,data:[],isComparisonSeries:b.isComparisonSeries,params:{plot:g?G.SECONDARY:void 0,stroke:{color:u.color,width:u.width,style:u.style}}},d=this._collectStatisticsForSeries(a,b,n,c);b.points.forEach(function(c,e){function n(){return g&&!a.oppositeDirections&&
2===a.primarySeries.length?0===p?-.15:.15:0}var f=d.values[e],m=f||0,l=e+1;z.updatePointIndexToLabelMap(k,l,c,r);var q=F.getTooltipInfo(f,z.getPointLabel(c,r),b.label,d.minInSeries,d.maxInSeries,d.valuesSum,d.absValuesSum,d.avgInSeries,h,y.LINE,u.color,null,c.fieldInfo,K?!b.isComparisonSeries:void 0),t=x[l]=x[l]||[];t.push(q);q.getGroup=function(){return t};f={originalValue:f,isUnavailableData:isNaN(f),unsortedIndex:e,name:z.getPointLabel(c,r),_valuesSumsInSeries:d.absValuesSum,point:c,fill:"#FFFFFF",
stroke:{color:u.color,width:1,style:v.toGFXValue(v.SOLID)},tooltip:q};r.reportStyle===H.CLASSIC?f.marker=void 0:u.marker&&(f.marker=u.marker);w?(f.x=m*(g&&a.oppositeDirections&&1===p?-1:1),f.y=l+n(),f.valueProp="x"):(f.x=l+n(),f.y=m*(g&&a.oppositeDirections&&1===p?-1:1),f.valueProp="y");h.yAxis.showValuesAsWeightsInSeries&&(f[w?"x":"y"]/=d.absValuesSum/100);B.data.push(f)});m.push(B)}},this);c.stackedValues&&(c.stackedValues.sort(function(a,b){return b-a}),c.minYValue=c.stackedValues[c.stackedValues.length-
1],c.maxYValue=c.stackedValues[0]);if(g){if(a.primaryPlotStat&&(b=E.getPrettifyYAxisParameters(Math.min(c.minYValue,a.primaryPlotStat.minYValue),Math.max(c.maxYValue,a.primaryPlotStat.maxYValue),{baseLineValue:h.yAxis.baseLineValue,renderColumnBarsInOppositeDirections:a.oppositeDirections,previewBelowZero:!r.dynamicReportInfo}),C.mixin(k.axes.y.opt,{majorTickStep:b.majorTickStep,minorTickStep:b.minorTickStep,min:b.min,max:b.max})),1===a.primarySeries.length){var q=w?"y":"x",l=[];a.primarySeries[0].data.forEach(function(a){var b=
m[0].data[a.unsortedIndex];b[q]=a.x;l.push(b)});m[0].data=l}}else I.prettifyYAxis(c.minYValue,c.maxYValue,h.yAxis.baseLineValue,k,h,y.LINE,b,r);return m},_collectStatisticsForSeries:function(a,k,h,b){var e=a.viewModel,g=a.visualProperties,w=a.previewFeatureIndex,t=a.isMultiFeatureChart,r=a.selectedComparisonIndex,m=a.isSecondaryPlot,c=a.ge,x=[],q=0,l=0,n=1E6,p=-1E6,v=2===a.seriesItems.length&&a.oppositeDirections&&m?A.CHART_DATA_SMOOTH:null;k.points.forEach(function(a,b){var d=A.getPreviewValue(a,
b,h,!1,y.LINE,g,e,t?b:w,v,k.isComparisonSeries,r,c,!1),d=(x[b]=d)||0;q+=d;l+=Math.abs(d);n=Math.min(n,d);p=Math.max(p,d)});k.points.forEach(function(a,c){var d=x[c],d=g.yAxis.showValuesAsWeightsInSeries?d/l*100:d;b.stackedValues?(b.stackedValues[c]=b.stackedValues[c]||0,b.stackedValues[c]+=d):(b.minYValue=Math.min(d,b.minYValue),b.maxYValue=Math.max(d,b.maxYValue))});return{values:x,valuesSum:q,absValuesSum:l,minInSeries:n,maxInSeries:p,avgInSeries:q/k.points.length}}}});