// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/layers/support/vectorTileLayerLoader","require exports dojo/has dojo/_base/lang ../../config ../../request ../../core/promiseUtils ../../core/urlUtils".split(" "),function(A,p,v,w,l,m,n,e){function k(a){if(a){var b=e.getOrigin(a);e.canUseXhr(b)||-1!==q.indexOf(b)||q.push(b);return a}}function r(a,b){var d=a.parsedUrl;if(null!=b.sources){var c=null;d&&(c=d.path.substring(0,d.path.lastIndexOf("/")),a.styleUrl=d.path);c||(c=(c=t(b,d))&&c.url);b.jsonUrl&&(a.styleUrl=b.jsonUrl);
var d=b.sprite||null,f=b.glyphs||null;c&&(d&&!e.isAbsolute(d)&&(d=e.normalize(e.join(c,d))),f&&!e.isAbsolute(f)&&(f=e.normalize(e.join(c,f))));a.style=b;a.spriteUrl=d;a.glyphsUrl=f;return x(a,b)}if(b.hasOwnProperty("tileInfo"))return a.layerDefinition=b,a.serviceUrl=d.path,y(a,b)}function y(a,b){var d=a.parsedUrl;if(z&&!b.hasOwnProperty("defaultStyles"))throw Error("Service definition must have 'defaultStyles' element!");var c=b.defaultStyles;e.isAbsolute(c)?a.styleUrl=e.normalize(c):a.styleUrl=e.normalize(e.join(d.path,
c,"root.json"));k(a.styleUrl);return m(a.styleUrl,{responseType:"json"}).then(function(c){var b=c.data.sprite||null,d=c.data.glyphs||null,f=e.removeFile(a.styleUrl);b&&!e.isAbsolute(b)&&(b=e.normalize(e.join(f,b)));d&&!e.isAbsolute(d)&&(d=e.normalize(e.join(f,d)));a.spriteUrl=b;a.glyphsUrl=d;return a.style=c.data})}function x(a,b){var d=a.parsedUrl,c=t(b,d);c||n.reject("Source isn't available in the style object!");if(c.url)return a.serviceUrl=c.url,e.isAbsolute(a.serviceUrl)||(a.serviceUrl=e.join(d.path,
a.serviceUrl)),k(a.serviceUrl),m(a.serviceUrl,{query:{f:"json"},responseType:"json"}).then(function(b){a.layerDefinition=u(b.data);return a});a.layerDefinition=u(c);return n.resolve(a)}function t(a,b){if(!a.sources)return null;var d=a.sources,c=null;if(d.esri)c=d.esri,b&&c.url&&!e.isAbsolute(c.url)&&(d=b.path.substring(0,b.path.lastIndexOf("/")),c.url=e.join(d,c.url));else{for(var f=0,g=Object.keys(d);f<g.length;f++){var h=g[f];if(-1!==h.toLocaleLowerCase().indexOf("street")&&"vector"===c.type){c=
d[h];break}}if(!c)for(f=0,g=Object.keys(d);f<g.length&&(h=g[f],c=d[h],"vector"!==c.type);f++);}return c}function u(a){if(a.hasOwnProperty("tileInfo"))return a;for(var b={xmin:-2.0037507067161843E7,ymin:-2.0037507067161843E7,xmax:2.0037507067161843E7,ymax:2.0037507067161843E7,spatialReference:{wkid:102100}},d=(b.xmax-b.xmin)/512,c=[],e=a.hasOwnProperty("minzoom")?parseFloat(a.minzoom):0,g=a.hasOwnProperty("maxzoom")?parseFloat(a.maxzoom):16;e<g;e++){var h=d/Math.pow(2,e);c.push({level:e,scale:Math.floor(3779.527559055118*
h),resolution:h})}a.tiles.forEach(k);return{capabilities:"TilesOnly",initialExtent:b,fullExtent:b,minScale:c[0].scale,maxScale:c[c.length-1].scale,tiles:a.tiles,tileInfo:{rows:512,cols:512,dpi:96,format:"pbf",origin:{x:-2.0037508342787E7,y:2.0037508342787E7},lods:c,spatialReference:{wkid:102100}}}}Object.defineProperty(p,"__esModule",{value:!0});var z=v("dojo-debug-messages"),q=l.defaults&&l.defaults.io.corsEnabledServers||l.request.corsEnabledServers;p.loadMetadata=function(a){if(!a)return n.reject("invalid input URL!");
var b={layerDefinition:null,parsedUrl:null,serviceUrl:null,style:null,styleUrl:null,url:null,spriteUrl:null,glyphsUrl:null};if("string"!==typeof a)return r(b,a).then(function(){return b});a=b.url=e.normalize(a);var d=b.parsedUrl=e.urlToObject(a);k(a);return m(d.path,{responseType:"json",query:w.mixin({f:"json"},d.query)}).then(function(a){return r(b,a.data)}).then(function(){return b})}});