// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/request","require dojo/_base/array dojo/_base/config dojo/_base/Deferred dojo/_base/lang dojo/_base/url dojo/_base/xhr ./core/request/script dojo/request/iframe dojo/dom-construct dojo/io-query ./kernel ./config ./sniff ./lang ./urlUtils ./deferredUtils".split(" "),function(T,E,K,q,t,U,z,fa,ga,aa,V,g,ha,r,F,w,B){function A(a){a=new U(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function ia(a){return this._xhr?this._xhr.getResponseHeader(a):null}function ja(a,e){var b=V.objectToQuery(a.content);
b&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+b);if(2E3<a.url.length){if("data:"!==a.url.toLowerCase().slice(0,5))return b=new q,b.reject(t.mixin(Error(),{message:"When using responseType 'image', URL length cannot exceed 2000 characters."})),b;if(3E6<a.url.length)return b=new q,b.reject(t.mixin(Error(),{message:"When using responseType 'image', data URL length cannot exceed 3000000 characters."})),b}var d=new Image;e.allowImageDataAccess&&(d.crossOrigin=a.withCredentials?"use-credentials":"anonymous");
var g=!1,m=new q(function(a){g=!0;d.onload=d.onerror=d.onabort=null;d.src=""}),b=function(a){d.onload=d.onerror=d.onabort=null;g||m.reject(Error("Unable to load the resource"))};d.onload=function(){d.onload=d.onerror=d.onabort=null;g||m.resolve(this)};d.onerror=b;d.onabort=b;d.alt="";d.src=a.url;return m}function H(a,e,b,d){var W=!1,m=!1,G,h;F.isDefined(e)&&(t.isObject(e)?(W=!!e.useProxy,m=!!e.usePost,G=e.crossOrigin):W=!!e);a=t.mixin({},a);a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));10>r("ie")&&
!ka.test(a.url)&&(a.url=encodeURI(a.url));var n=a.content,f=a.url,k=b&&a.form,I=p;G=F.isDefined(G)?G:I.useCors;a.load=function(b){var c;b&&(b.error?(c=t.mixin(Error(),b.error),c.log=!!K.isDebug):"error"===b.status&&(c=t.mixin(Error(),b),c.log=!!K.isDebug),c&&(a.failOk=!c.log,F.isDefined(c.httpCode)||(c.httpCode=c.code)));return c||b};a.error=function(b,c){c&&c.xhr&&c.xhr.abort();b instanceof Error||(b=t.mixin(Error(),b));b.log=!!K.isDebug;a.failOk=!b.log;I.errorHandler(b,c);return b};a._token&&(a.content=
a.content||{},a.content.token=a._token);var v=0,l;n&&f&&(l=V.objectToQuery(n),v=l.length+f.length+1,r("esri-url-encodes-apostrophe")&&(v=l.replace(/'/g,"%27").length+f.length+1));a.timeout=F.isDefined(a.timeout)?a.timeout:I.timeout;a.handleAs=a.handleAs||"json";try{var C,c,x=G&&w.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),ba=w.hasSameOrigin(a.url,window.location.href)||x,J=m||b||v>I.postLength?!0:!1,ca=ba||-1===a.handleAs.indexOf("json")||!a.callbackParamName||b?
!1:!0,D=w.getProxyRule(a.url)||I.alwaysUseProxy||W||!("image"===a.handleAs&&!e.allowImageDataAccess||ca&&!J||ba)?!0:!1;b&&!r("esri-file-upload")&&!D&&x&&(D=!0);if(D)if(C=w.getProxyUrl(f,G),c=C.path,C._xo&&(x=!0),!J&&c.length+1+v>I.postLength&&(J=!0),a.url=c+"?"+f,J)a.content=t.mixin(C.query||{},n);else{var da=V.objectToQuery(t.mixin(C.query||{},n));da&&(a.url+="?"+da);a.content=null}if(!ca||J||D){var u=a.headers;!x||u&&u.hasOwnProperty("X-Requested-With")||(u=a.headers=u||{},u["X-Requested-With"]=
null);if(b){var A=a.callbackParamName||"callback.html",H=a.callbackElementName||"textarea",L,R,M,S,P=k.elements?k.elements.length:0,y;if(n=a.content)for(L in n.token&&-1<f.toLowerCase().indexOf("/sharing/servers/")&&(f+=(-1===f.indexOf("?")?"?":"\x26")+"token\x3d"+n.token,a.url=D?c+"?"+f:f,delete n.token),n)if(M=n[L],F.isDefined(M)){R=null;for(S=0;S<P;S++)if(y=k.elements[S],y.name===L){R=y;break}R?R.value=M:d?k.append(L,M):k.appendChild(aa.create("input",{type:"hidden",name:L,value:M}))}if(r("esri-file-upload")){E.forEach(k.elements,
function(a){a.name===A&&k.removeChild(a)});var N=d?k:new FormData(k);if(11<r("safari")&&"entries"in N&&"delete"in N){d=[];for(var B=N.entries(),X=B.next();!X.done;){var Y=X.value;Y[1]instanceof File&&""===Y[1].name&&d.push(Y[0]);X=B.next()}d.forEach(function(a){N["delete"](a)})}a.contentType=!1;a.postData=N;delete a.form}else{k.enctype="multipart/form-data";9>r("ie")&&(k.encoding="multipart/form-data");k.method="post";E.some(k.elements,function(a){return a.name===A})||k.appendChild(aa.create("input",
{type:"hidden",name:A,value:H}));if(-1!==f.toLowerCase().indexOf("addattachment")||-1!==f.toLowerCase().indexOf("updateattachment"))f+=(-1===f.indexOf("?")?"?":"\x26")+A+"\x3d"+H,a.url=D?c+"?"+f:f;delete a.content}}if(x&&!a.hasOwnProperty("withCredentials")&&"with-credentials"===p.useCors){var f=D?c:f,Q=w.canUseXhr(f,!0),Z=-1<Q?p.corsEnabledServers[Q]:null;if(Z&&Z.hasOwnProperty("withCredentials"))Z.withCredentials&&(a.withCredentials=!0);else if(g.id){var ea=g.id.findServerInfo(f);ea&&ea.webTierAuth&&
(a.withCredentials=!0)}}a=O?O(a):a;if("image"===a.handleAs)return ja(a,e);if(J){if(b&&!r("esri-file-upload")){h=new q(function(){T.cancel()});var T=ga.post(a.url,a).then(function(a){h.resolve(a)}).otherwise(function(a){h.reject(a)});h.addCallback(function(b){return a.load(b)});h.addErrback(function(b){return a.error(b)});return h}!D&&r("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+ma++);return z.post(a)}return z.get(a)}a=O?O(a):a;a.jsonp=a.callbackParamName;
a.query=a.content;h=new q(function(){U.cancel()});var U=fa.get(a.url,a).then(function(a){h.resolve(a)}).otherwise(function(a){h.reject(a)});h.addCallback(function(b){return a.load(b)});h.addErrback(function(b){return a.error(b)});return h}catch(la){return h=new q,h.errback(a.error(la)),h}}function P(a){var e=p.corsStatus,b=w.canUseXhr(a,!0);-1<b&&p.corsEnabledServers.splice(b,1);var d=new q;d.reject({log:!!K.isDebug});e[A(a)]=d.promise;return b}function y(a){var e=p.corsStatus;try{var b=A(a);if(p.corsDetection&&
p.useCors&&r("esri-cors")&&a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!w.hasSameOrigin(a,window.location.href)&&!w.canUseXhr(a)){if(e[b]&&!e[b].isCanceled())return e[b];var d=new q(B._dfdCanceller);e[b]=d.promise;var g=z.get({url:a.substring(0,a.toLowerCase().indexOf("/rest/")+6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null},timeout:1E3*p.corsDetectionTimeout});d._pendingDfd=g;g.then(function(e){e?(w.canUseXhr(a)||p.corsEnabledServers.push(b),d.resolve()):
d.reject()},function(a){d.reject(a)});return d.promise}}catch(m){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}return na}function Q(a){O=a}function u(a,e,b,d){function l(a){a._pendingDfd=H(b,d,t,k);if(!a._pendingDfd){a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;var c=Error("Deferred object is missing");c.log=!!K.isDebug;a.errback(c);a._pendingDfd=null;return a}a._pendingDfd.addCallback(function(b){a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;d.returnFullResponse&&
(b={data:b,_xhr:a.ioArgs&&a.ioArgs.xhr,getHeader:ia});a.callback(b);a._pendingDfd=null}).addErrback(function(c){var x,e,f;c&&(x=c.code,e=c.subcode,f=(f=c.messageCode)&&f.toUpperCase());if(c&&403==x&&(4==e||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!b._ssl){b._ssl=b._sslFromServer=!0;u(a,!0,b,d);return}}else if(c&&415==c.status){if(P(b.url),!b._err415){b._err415=1;u(a,!0,b,d);return}}else if(g.id&&-1!==E.indexOf(g.id._errorCodes,x)&&
!g.id._isPublic(b.url)&&!q&&(403!=x||-1===E.indexOf(oa,f)&&(!F.isDefined(e)||2==e&&b._token))){a._pendingDfd=g.id.getCredential(b.url,{token:b._token,error:c});a._pendingDfd.addCallback(function(c){b._token=c.token;b._credential=c;b._ssl=b._sslFromServer||c.ssl;u(a,!0,b,d)}).addErrback(function(b){a.errback(b);a._pendingDfd=null});return}a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;a.isFulfilled()||a.errback(c);a._pendingDfd=null})}var m=b.form,q=d.disableIdentityLookup,h=d._preLookup,n=!1;if(r("esri-workers")&&
!1!==p.useWorkers)if(!0===d.useWorkers||!0===p.useWorkers)n=!0;else if(d.workerOptions){var f=d.workerOptions;if(f.callback||f.worker&&f.worker.worker instanceof Worker)n=!0}var k=m&&r("esri-file-upload")&&m instanceof FormData,t=m&&(m.elements?E.some(m.elements,function(a){return"file"===a.type}):k),y=-1!==b.url.toLowerCase().indexOf("token\x3d")||b.content&&b.content.token||t&&E.some(m.elements,function(a){return"token"===a.name})?1:0;if(!e){a.addCallback(function(a){if((/\/sharing\/rest\/accounts\/self/i.test(b.url)||
/\/sharing\/rest\/portals\/self/i.test(b.url))&&!y&&!b._token&&a.user&&a.user.username){p.webTierAuthServers.push(A(b.url));a=p.corsEnabledServers;var c=w.canUseXhr(b.url,!0),d={host:A(b.url),withCredentials:!0};if(-1===c)a.push(d);else{var e=a[c];"object"===typeof e?e.withCredentials=!0:a.splice(c,1,d)}}if(a=b._credential)if(c=(c=g.id.findServerInfo(a.server))&&c.owningSystemUrl)c=c.replace(/\/?$/,"/sharing"),(a=g.id.findCredential(c,a.userId))&&-1===g.id._getIdenticalSvcIdx(c,a)&&a.resources.splice(0,
0,c)});a.addBoth(function(a){delete b._credential;!a||r("ie")&&a.nodeType||(a._ssl=b._ssl)});var B=b.load,C=b.error;B&&a.addCallback(function(b){var c=a._pendingDfd,c=c&&c.ioArgs;return B.call(c&&c.args,b,c)});C&&a.addErrback(function(b){var c=a._pendingDfd,c=c&&c.ioArgs;return C.call(c&&c.args,b,c)})}!g.id||y||b._token||g.id._isPublic(b.url)||q&&!h||!(e=g.id.findCredential(b.url))||(b._token=e.token,b._ssl=e.ssl);n?d.workerOptions&&d.workerOptions.worker?(v||(v=z),z=d.workerOptions.worker,l(a)):
T(["./workers/RequestClient"],function(b){v||(v=z);if(d.workerOptions){var c=d.workerOptions;z=b.getClient(c.callback,c.cbFunction)}else z=b.getClient();l(a)}):(v&&(z=v,v=null),l(a));return a}function l(a,e){a.url=w.fixUrl(a.url);e=e||{};var b=new q(B._dfdCanceller),d=y(a.url);b._pendingDfd=d;d.always(function(d){d&&"cancel"===d.dojoType?b.reject(d):u(b,!1,a,e)});return b}var v=null,O,p=ha.defaults.io,oa=["COM_0056","COM_0057"],ma=0,ka=/%[0-9A-F]{2}/i,na=function(){var a=new q;a.resolve();return a.promise}();
l._makeRequest=H;l._processRequest=u;l._disableCors=P;l._detectCors=y;l.setRequestPreCallback=Q;r("extend-esri")&&(g.request=l,g._makeRequest=H,g._processRequest=u,g._disableCors=P,g._detectCors=y,g.setRequestPreCallback=Q);return l});