// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/core/workers/RemoteClient","require exports dojo/Deferred ../Error ../promiseUtils ./utils".split(" "),function(A,B,r,w,x,e){function l(b,a){b["delete"](a)}var t=e.MessageType.CLOSE,k=e.MessageType.CANCEL,u=e.MessageType.INVOKE,m=e.MessageType.RESPONSE,v=e.MessageType.OPEN_PORT,y=function(){function b(a){this._timer=null;this._cancelledJobIds=new Set;this._invokeMessages=[];this._invoke=a;this._timer=null;this._process=this._process.bind(this)}b.prototype.push=function(a){a.type===
e.MessageType.CANCEL?this._cancelledJobIds.add(a.jobId):(this._invokeMessages.push(a),null===this._timer&&(this._timer=setTimeout(this._process,0)))};b.prototype._process=function(){this._timer=null;for(var a=0,c=this._invokeMessages;a<c.length;a++){var g=c[a];this._cancelledJobIds.has(g.jobId)||this._invoke(g)}this._cancelledJobIds.clear();this._invokeMessages.length=0};return b}();return function(){function b(a,c,g){this._outJobs=new Map;this._inJobs=new Map;this._queue=new y(this._onInvoke.bind(this));
this._onMessage=this._onMessage.bind(this);this._client=c;this._port=a;this._port.addEventListener("message",this._onMessage);this._port.start();this._channel=g}b.connect=function(a){var c=new MessageChannel;a="function"===typeof a?new a:"default"in a&&"function"===typeof a.default?new a.default:a;a.remoteClient=new b(c.port1,a,c);return c.port2};b.prototype.close=function(){this._post({type:t});this._close()};b.prototype.isBusy=function(){return 0<this._outJobs.size};b.prototype.invoke=function(a,
c,g){var b=this,f=e.newJobId(),h=new r(function(){l(b._outJobs,f);b._post({type:k,jobId:f})});this._outJobs.set(f,h);this._post({type:u,jobId:f,methodName:a},c,g);return h.promise};b.prototype.openPort=function(){var a=this,c=e.newJobId(),b=new r(function(){l(a._outJobs,c);a._post({type:k,jobId:c})});this._outJobs.set(c,b);this._post({type:v,jobId:c});return b.promise};b.prototype._close=function(){this._channel&&(this._channel=null);this._port.removeEventListener("message",this._onMessage);this._port.close();
this._outJobs.forEach(function(a){a.cancel()});this._inJobs.clear();this._outJobs.clear();this._port=this._client=null};b.prototype._onMessage=function(a){if(a=e.receiveMessage(a))switch(a.type){case m:this._onResponse(a);break;case u:this._queue.push(a);break;case k:this._onCancel(a);break;case t:this._close();break;case v:this._onOpenPort(a)}};b.prototype._onCancel=function(a){var c=this._inJobs,b=a.jobId,d=c.get(b);this._queue.push(a);d&&(l(c,b),d.cancel())};b.prototype._onInvoke=function(a){var c=
this,b=a.methodName,d=a.jobId;a=a.data;var f=this._inJobs,h=this._client,p=h[b],n;try{if(!p&&b&&-1!==b.indexOf("."))for(var k=b.split("."),q=0;q<k.length-1;q++)h=h[k[q]],p=h[k[q+1]];if("function"!==typeof p)throw new TypeError(b+" is not a function");n=p.call(h,a,this)}catch(z){this._post({type:m,jobId:d,error:e.toInvokeError(z)});return}x.isThenable(n)?(f.set(d,n),n.then(function(a){f.has(d)&&(l(f,d),c._post({type:m,jobId:d},a))}).catch(function(a){f.has(d)&&(l(f,d),a&&"cancel"===a.dojoType||c._post({type:m,
jobId:d,error:e.toInvokeError(a||{message:"Error encountered at method "+b})}))})):this._post({type:m,jobId:d},n)};b.prototype._onOpenPort=function(a){var c=new MessageChannel;new b(c.port1,this._client);this._post({type:m,jobId:a.jobId},c.port2,[c.port2])};b.prototype._onResponse=function(a){var b=a.jobId,e=a.error;a=a.data;var d=this._outJobs;if(d.has(b)){var f=d.get(b);l(d,b);e?f.reject(w.fromJSON(JSON.parse(e))):f.resolve(a)}};b.prototype._post=function(a,b,g){return e.postMessage(this._port,
a,b,g)};return b}()});