// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder",["./utils","dojo/i18n!../../../../../../../nls/jsapi"],function(e,m){m=m.geoenrichment.dijit.ReportPlayer.ReportPlayer;var l={NUMBER:"n/",createFieldInfoFromCalculator:function(a,h,d,g){if(!a)return null;h=d&&d.format;var f=d&&d.autoformatCurrency;d=d&&d.additionalText;var b={};b.alias=a.getDescriptionWithType()||a.getAliasWithType();var c=a.variable;b.hasVariable=!0;b.variableID=c.id;b.fullName=
c.fullName;b.fieldCategory=c.fieldCategory;b.vintage=c.vintage;b.type=c.type;var k=a.getToggleGroup&&a.getToggleGroup();b.statefulName=k?k.value:"n/"+c.fullName;k=a.getCalcType().charAt(0);b.name=e.name.createFieldNameFromVariable(c,k);h?e.format.setFieldInfoFormat(b,h):(b.decimals=a.getDecimals(),b.showCurrency=!(!f||"n"!==k||!c.units||"CURRENCY"!==c.units.toUpperCase()),b.showPercent=!b.showCurrency&&("p"===k||"n"===k&&c.units&&"PCT"===c.units.toUpperCase()),b.useThousandsSeparator=!0);"string"===
typeof d&&(b.additionalText=d);c.isWebMap?(b.isWebMap=!0,b.webMapFieldName=c.fieldName,b.webMapField=c.field,b.webMapId=c.webMapId,!h&&c.field&&c.field.format&&(b.decimals=c.field.format.places,b.useThousandsSeparator=!1!==c.field.format.digitSeparator)):c.customDataCollection?(b.isCustomDataCollection=!0,b.customDataCollectionId=c.customDataCollection.id,b.customDataCollectionUrl=c.customDataCollection.url,b.customDataCollectionPortalUrl=c.customDataCollection.portalUrl):c.isSiteAttribute?(b.isSiteAttribute=
!0,b.attribute=c.attribute,0<c.attribute.places&&(b.decimals=c.attribute.places)):c.isDataLayerAttribute&&(b.isDataLayerAttribute=!0,b.layerID=c.layerID,b.attribute=c.attribute,b.type=c.attribute.type,0<c.attribute.decimals&&(b.decimals=c.attribute.decimals),"DISTANCE"===c.attribute.name&&(b.units=c.attribute.units||"esriMiles"));c.usedFields&&(b.usedFields=c.usedFields);e.name.provideQualifiedFieldInfoTemplateName(b,g);return b},createFieldInfoFromScript:function(a,h,d,g){h=d&&d.format;d=d&&d.additionalText;
a=a||{};a.name=a.name||e.name.DEFAULT_SCRIPT_NAME;a.alias=a.alias||m.scriptNameDefault;a.decimals=Number(a.decimals)||0;var f={};f.name=e.name.createFieldNameFromScript(a);e.name.provideQualifiedFieldInfoTemplateName(f,g);f.script=a;h?e.format.setFieldInfoFormat(f,h):(f.decimals=Number(a.decimals),f.showCurrency=!1,f.showPercent=!1,f.useThousandsSeparator=!0);"string"===typeof d&&(f.additionalText=d);return f},createFieldInfoFromChart:function(a){return{isChart:!0,chartJson:a}},createFieldInfoFromImage:function(a,
e){return{isImage:!0,imageJson:a,triggerJson:e}},createFieldInfoFromShape:function(a){return{isShape:!0,shapeJson:a}},createFieldInfoFromSection:function(a){return{isReportSection:!0,sectionJson:a}},createFieldInfoFromInfographic:function(a){return{isInfographic:!0,infographicJson:a}},createFieldInfoFromMissingVariable:function(a){return{isMissing:!0,variable:a,alias:a.alias}}},n=/^\[\w+\]$/,p=/\[\w+\]/;l.createFieldInfoFromLabel=function(a,h){if("string"!==typeof a)return null;a=a.trim();var d=n.test(a);
if(!h||d){if(!d)return null;a=a.replace(/\[|\]/g,"").toUpperCase();return l.createFieldInfoFromSpecialFieldName(e.fields.uiToTemplate(a))}return p.test(a)?(d=e.richText.collectFieldInfosFromRenderedXMLString(a))&&e.richText.createFieldInfoFromRichText(d.xmlString,d.fieldInfos,d.specialFieldInfos):null};l.createFieldInfoFromSpecialFieldName=function(a,h){if("string"!==typeof a)return null;var d;a=a.substr(a.indexOf(".")+1);var g=a.toUpperCase();"CURRDATE"===g?d={name:e.fields.DATE_FIELD_NAME,alias:e.fields.DATE_FIELD_ALIAS,
format:h||e.fields.DATE_FIELD_DEFAULT_FORMAT}:"SITENOTE"===g?d={name:e.fields.SITENOTE_FIELD_NAME,alias:e.fields.SITENOTE_FIELD_ALIAS}:"SITENOTES"===g&&(d={name:e.fields.SITENOTES_FIELD_NAME,alias:e.fields.SITENOTES_FIELD_ALIAS});if(d)return d;var f=e.fields.templateToUIHeader(g);f?d={name:e.fields.qualifyTemplateHeaderName(g),alias:f}:(g=e.fields.templateToUIReportVar(g))&&(d={name:g,alias:g});return d};var q=/_P$/i;l.isFieldInfoInPercentState=function(a){return a&&a.statefulName&&("p"===a.statefulName.charAt(0)||
q.test(a.statefulName))};return l});