// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/dataDrilling/EnrichUtil",["../../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil","../infographicUtils/InfographicJsonUtil"],function(l,m){var e={processChartJson:function(a,b){var d=[];a.seriesItems.forEach(function(a){a.points.forEach(function(a){d.push({fieldName:a.fieldInfo.name,mapTo:b?b(a.fieldInfo.fullName):a.fieldInfo.fullName})})});var c=a.comparisonInfo;return this.createChartInfo(d,c&&c.levels,e.buildCalculatorNameForChart(a))},
createChartInfo:function(a,b,d){a=a||[];var c={isChart:!0,fields:[],levels:b,calculatorName:d,_cache:{}};a.forEach(function(a){e.addField(c,a)});return c},buildCalculatorNameForChart:function(a){if((a=a.comparisonInfo)&&a.calculatorName)return a.calculatorName;var b=a&&a.levels&&a.levels.length?a.levels.join("_"):null;b&&(a.calculatorName=b);return b},processEsriInfographic:function(a){return{isInfographic:!0,variables:a.variables&&a.variables.slice(),fieldInfos:a.fieldInfos&&a.fieldInfos,levels:m.getLevels(a)}},
createGeneralInfo:function(a){a=a||[];var b={isGeneral:!0,fields:[],_cache:{}};a.forEach(function(a){e.addField(b,a)});return b},addGeneralFieldInfo:function(a,b){b&&b.fullName&&!a._cache[b.name]&&(a._cache[b.name]=!0,a.fields.push({fieldName:b.name,mapTo:b.fullName}))},addField:function(a,b){b&&b.fieldName&&!a._cache[b.fieldName]&&(a._cache[b.fieldName]=!0,a.fields.push(b))},optimizeInfos:function(a){var b=[],d=[],c=[];a.forEach(function(a){a.isGeneral?b.push(a):a.isChart?d.push(a):a.isInfographic&&
c.push(a)});var f=e.createGeneralInfo();b.forEach(function(a){a.fields.forEach(function(a){e.addField(f,a)})});var h={};d.forEach(function(a){if(a.calculatorName){var b=h[a.calculatorName]=h[a.calculatorName]||a;b!==a&&a.fields.forEach(function(a){e.addField(b,a)})}else a.fields.forEach(function(a){e.addField(f,a)})});var g={};c.forEach(function(a){var b=(a.fieldInfos&&a.fieldInfos.map(function(a){return a.fullName}).join("_")||a.variables.join("_"))+"_"+a.levels.join("_");g[b]=a});a=[];f.fields.length&&
a.push(f);for(var k in h)a.push(h[k]);for(k in g)a.push(g[k]);return a}},g={ddLibrary:null,_getStandardEnrichInfos:function(a,b,d){var c=[];a=g.ddLibrary.getDrillingOptions(a,b,d);if(!a)return c;a.forEach(function(a){c=c.concat(g._getStandardEnrichInfosForTableInfo(a,!1))});return c},_getStandardEnrichInfosForTableInfo:function(a,b){var d=[],c;for(c in a.stateData){var f=a.stateData[c];f.fieldInfo.isChart?d.push(e.processChartJson(f.fieldInfo.chartJson,function(a){var b="n"===c?"":"_"+c.toUpperCase();
return a+b})):!b&&f.fieldInfo.isInfographic&&(f.fieldInfo.infographicJson.variables||f.fieldInfo.infographicJson.fieldInfos)&&d.push(e.processEsriInfographic(f.fieldInfo.infographicJson))}return d},_getCustomEnrichInfos:function(a){var b=[];l.processSectionFieldInfos(a,function(a){a.isInfographic&&(a.infographicJson.variables||a.infographicJson.fieldInfos)&&b.push(e.processEsriInfographic(a.infographicJson))});return b},getEnrichInfosForTemplateJson:function(a,b){var d=[];l.processTemplateFieldInfos(b,
function(b){b.isInfographic&&b.infographicJson.variableTables&&b.infographicJson.variableTables.forEach(function(c){if(c.variable&&c.variable.fieldInfo){var e=b.infographicJson.dataDrilling&&b.infographicJson.dataDrilling[c.variable.fieldInfo.templateName];d=e&&e.sectionJson?d.concat(g._getCustomEnrichInfos(e.sectionJson)):d.concat(g._getStandardEnrichInfos(a,c.variable.fieldInfo))}})});return e.optimizeInfos(d)}};g.buildCalculatorNameForChart=e.buildCalculatorNameForChart;g.optimizeInfos=e.optimizeInfos;
return g});