// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.24/esri/copyright.txt for details.
//>>built
define("esri/geometry/pe",["require","exports","../core/tsSupport/extendsHelper","dojo/Deferred","../core/sniff"],function(u,a,B,C,D){function v(b){function c(a,b,c){a[b]=c(a[b])}a._pe=b;h.init();w.init();x.init();y.init();z.init();a.PeGCSExtent=function(e){function b(){return null!==e&&e.apply(this,arguments)||this}B(b,e);b.prototype.destroy=function(){a._pe.destroy(this)};return b}(a._pe.PeGCSExtent);for(var f=0,d=[a._pe.PeDatum,a._pe.PeGeogcs,a._pe.PeGeogtran,a._pe.PeObject,a._pe.PeParameter,a._pe.PePrimem,
a._pe.PeProjcs,a._pe.PeSpheroid,a._pe.PeUnit];f<d.length;f++)b=d[f],c(b.prototype,"getName",function(a){return function(){return a.call(this,Array(h.PE_NAME_MAX))}});f=0;for(d=[a._pe.PeGeogtran,a._pe.PeProjcs];f<d.length;f++)b=d[f],c(b.prototype,"getParameters",function(b){return function(){for(var e=Array(h.PE_PARM_MAX),c=b.call(this),d=0;d<e.length;d++){var g=a._pe.getValue(c,"*");e[d]=g?a._pe.wrapPointer(g,a._pe.PeParameter):null;c+=Int32Array.BYTES_PER_ELEMENT}return e}});c(a._pe.PeHorizon.prototype,
"getCoord",function(a){return function(){var b=this.getSize();if(!b)return null;var e=[],c=a.call(this);n(e,b,c);return e}});c(a._pe.PeGTlistExtendedEntry.prototype,"getEntries",function(b){var e=a._pe._pe_getPeGTlistExtendedGTsSize();return function(){var c=null,d=b.call(this);if(!a._pe.compare(d,a._pe.NULL)){var c=[d],g=this.getSteps();if(1<g)for(var d=a._pe.getPointer(d),k=1;k<g;k++)c.push(a._pe.wrapPointer(d+e*k,a._pe.PeGTlistExtendedGTs))}return c}});var g=a._pe._pe_getPeHorizonSize();b=function(b){return function(){var e=
this._cache;e||(this._cache=e=new Map);if(e.has(b))return e.get(b);var c=null,d=b.call(this);if(!a._pe.compare(d,a._pe.NULL)){var c=[d],f=d.getNump();if(1<f)for(var d=a._pe.getPointer(d),h=1;h<f;h++)c.push(a._pe.wrapPointer(d+g*h,a._pe.PeHorizon))}e.set(b,c);return c}};c(a._pe.PeProjcs.prototype,"horizonGcsGenerate",b);c(a._pe.PeProjcs.prototype,"horizonPcsGenerate",b);a._pe.PeObject.prototype.toString=function(b){void 0===b&&(b=h.PE_STR_OPTS_NONE);a._pe.ensureCache.prepare();var e=a._pe.getPointer(this),
c=a._pe.ensureInt8(Array(h.PE_BUFFER_MAX));return a._pe.Pointer_stringify(a._pe._pe_object_to_string_ext(e,b,c))}}function m(b){if(b){var c=a._pe.getClass(b);c&&(c=a._pe.getCache(c))&&(b=a._pe.getPointer(b))&&delete c[b]}}function t(b,c){for(var f=[],d=Array(c),g=0;g<b;g++)f.push(a._pe.ensureInt8(d));return f}function p(a){var b;Array.isArray(a[0])?(b=[],a.forEach(function(a){b.push(a[0],a[1])})):b=a;return b}function n(b,c,f,d){void 0===d&&(d=!1);if(d)for(d=0;d<2*c;d++)b[d]=a._pe.getValue(f+d*Float64Array.BYTES_PER_ELEMENT,
"double");else{var g=0===b.length;for(d=0;d<c;d++)g&&(b[d]=Array(2)),b[d][0]=a._pe.getValue(f,"double"),b[d][1]=a._pe.getValue(f+Float64Array.BYTES_PER_ELEMENT,"double"),f+=2*Float64Array.BYTES_PER_ELEMENT}}Object.defineProperty(a,"__esModule",{value:!0});var q;a._pe=null;a.isLoaded=function(){return!!a._pe};a.isSupported=function(){return!!D("esri-wasm")};a.load=function(){if(q)return q.promise;q=new C;u(["./support/pe-wasm"],function(a){a({locateFile:function(a){return u.toUrl("./support/"+a)},
onAbort:function(a){q.reject(Error(a))}}).then(function(a){v(a);q.resolve()})});return q.promise};(function(b){function c(b,e,c){a._pe.ensureCache.prepare();var d=p(c),g=c===d,d=a._pe.ensureFloat64(d);(b=a._pe._pe_geog_to_proj(a._pe.getPointer(b),e,d))&&n(c,e,d,g);return b}function f(a,b,c){return d(a,b,c,0)}function d(b,e,c,d){a._pe.ensureCache.prepare();var g=p(c),k=c===g,g=a._pe.ensureFloat64(g);(b=a._pe._pe_proj_to_geog_center(a._pe.getPointer(b),e,g,d))&&n(c,e,g,k);return b}b.geogToProj=c;b.projGeog=
function(a,b,d,l){switch(l){case h.PE_TRANSFORM_P_TO_G:return f(a,b,d);case h.PE_TRANSFORM_G_TO_P:return c(a,b,d)}return 0};b.projToGeog=f;b.projToGeogCenter=d})(a.PeCSTransformations||(a.PeCSTransformations={}));var h;(function(b){b.init=function(){b.PE_BUFFER_MAX=a._pe.PeDefs.prototype.get_PE_BUFFER_MAX();b.PE_NAME_MAX=a._pe.PeDefs.prototype.get_PE_NAME_MAX();b.PE_MGRS_MAX=a._pe.PeDefs.prototype.get_PE_MGRS_MAX();b.PE_USNG_MAX=a._pe.PeDefs.prototype.get_PE_USNG_MAX();b.PE_DD_MAX=a._pe.PeDefs.prototype.get_PE_DD_MAX();
b.PE_DDM_MAX=a._pe.PeDefs.prototype.get_PE_DDM_MAX();b.PE_DMS_MAX=a._pe.PeDefs.prototype.get_PE_DMS_MAX();b.PE_UTM_MAX=a._pe.PeDefs.prototype.get_PE_UTM_MAX();b.PE_PARM_MAX=a._pe.PeDefs.prototype.get_PE_PARM_MAX();b.PE_TYPE_NONE=a._pe.PeDefs.prototype.get_PE_TYPE_NONE();b.PE_TYPE_GEOGCS=a._pe.PeDefs.prototype.get_PE_TYPE_GEOGCS();b.PE_TYPE_PROJCS=a._pe.PeDefs.prototype.get_PE_TYPE_PROJCS();b.PE_TYPE_GEOGTRAN=a._pe.PeDefs.prototype.get_PE_TYPE_GEOGTRAN();b.PE_TYPE_COORDSYS=a._pe.PeDefs.prototype.get_PE_TYPE_COORDSYS();
b.PE_TYPE_UNIT=a._pe.PeDefs.prototype.get_PE_TYPE_UNIT();b.PE_STR_OPTS_NONE=a._pe.PeDefs.prototype.get_PE_STR_OPTS_NONE();b.PE_STR_AUTH_NONE=a._pe.PeDefs.prototype.get_PE_STR_AUTH_NONE();b.PE_STR_AUTH_TOP=a._pe.PeDefs.prototype.get_PE_STR_AUTH_TOP();b.PE_STR_NAME_CANON=a._pe.PeDefs.prototype.get_PE_STR_NAME_CANON();b.PE_PARM_X0=a._pe.PeDefs.prototype.get_PE_PARM_X0();b.PE_PARM_ND=a._pe.PeDefs.prototype.get_PE_PARM_ND();b.PE_TRANSFORM_1_TO_2=a._pe.PeDefs.prototype.get_PE_TRANSFORM_1_TO_2();b.PE_TRANSFORM_2_TO_1=
a._pe.PeDefs.prototype.get_PE_TRANSFORM_2_TO_1();b.PE_TRANSFORM_P_TO_G=a._pe.PeDefs.prototype.get_PE_TRANSFORM_P_TO_G();b.PE_TRANSFORM_G_TO_P=a._pe.PeDefs.prototype.get_PE_TRANSFORM_G_TO_P();b.PE_HORIZON_RECT=a._pe.PeDefs.prototype.get_PE_HORIZON_RECT();b.PE_HORIZON_POLY=a._pe.PeDefs.prototype.get_PE_HORIZON_POLY();b.PE_HORIZON_LINE=a._pe.PeDefs.prototype.get_PE_HORIZON_LINE();b.PE_HORIZON_DELTA=a._pe.PeDefs.prototype.get_PE_HORIZON_DELTA()}})(h=a.PeDefs||(a.PeDefs={}));(function(b){function c(b,
c){var e=null,g=d[b];g||(g={},d[b]=g);if(g.hasOwnProperty(String(c)))e=g[c];else{var k=a._pe.PeFactory.prototype.factoryByType(b,c);a._pe.compare(k,a._pe.NULL)||(e=k,g[c]=e)}return e=f(e)}function f(b){if(b){var c=b.getType();switch(c){case h.PE_TYPE_GEOGCS:b=a._pe.castObject(b,a._pe.PeGeogcs);break;case h.PE_TYPE_PROJCS:b=a._pe.castObject(b,a._pe.PeProjcs);break;case h.PE_TYPE_GEOGTRAN:b=a._pe.castObject(b,a._pe.PeGeogtran);break;default:c&h.PE_TYPE_UNIT&&(b=a._pe.castObject(b,a._pe.PeUnit))}}return b}
var d={},g={};b.initialize=function(){a._pe.PeFactory.prototype.initialize(null)};b.coordsys=function(a){return c(h.PE_TYPE_COORDSYS,a)};b.factoryByType=c;b.fromString=function(b,c){var d=null,e=g[b];e||(e={},g[b]=e);if(e.hasOwnProperty(c))d=e[c];else{var k=a._pe.PeFactory.prototype.fromString(b,c);a._pe.compare(k,a._pe.NULL)||(d=k,e[c]=d)}return d=f(d)};b.geogcs=function(a){return c(h.PE_TYPE_GEOGCS,a)};b.geogtran=function(a){return c(h.PE_TYPE_GEOGTRAN,a)};b.getCode=function(b){return a._pe.PeFactory.prototype.getCode(b)};
b.projcs=function(a){return c(h.PE_TYPE_PROJCS,a)};b.unit=function(a){return c(h.PE_TYPE_UNIT,a)}})(a.PeFactory||(a.PeFactory={}));a.PeGCSExtent=null;var w;(function(b){var c;b.init=function(){b.PE_GTLIST_OPTS_COMMON=a._pe.PeGTlistExtended.prototype.get_PE_GTLIST_OPTS_COMMON();c=a._pe._pe_getPeGTlistExtendedEntrySize()};b.getGTlist=function(b,d,g,e,k,l){var f=null,h=new a._pe.PeInteger(l);try{var A=a._pe.PeGTlistExtended.prototype.getGTlist(b,d,g,e,k,h);if(l=h.get_val())if(f=[A],1<l){var m=a._pe.getPointer(A);
for(b=1;b<l;b++)f.push(a._pe.wrapPointer(m+c*b,a._pe.PeGTlistExtendedEntry))}}finally{a._pe.destroy(h)}return f}})(w=a.PeGTlistExtended||(a.PeGTlistExtended={}));(function(b){b.destroy=function(b){if(b&&b.length){for(var c=0;c<b.length;c++){var d=b[c];m(d);d.getEntries().forEach(function(a){m(a);a=a.getGeogtran();m(a);a.getParameters().forEach(m);[a.getGeogcs1(),a.getGeogcs2()].forEach(function(a){m(a);var b=a.getDatum();m(b);m(b.getSpheroid());m(a.getPrimem());m(a.getUnit())})})}a._pe.PeGTlistExtendedEntry.prototype.Delete(b[0])}}})(a.PeGTlistExtendedEntry||
(a.PeGTlistExtendedEntry={}));(function(b){b.geogToGeog=function(b,f,d,g,e){a._pe.ensureCache.prepare();var c=p(d),h=d===c,c=a._pe.ensureFloat64(c),r=0;g&&(r=a._pe.ensureFloat64(g));(b=a._pe._pe_geog_to_geog(a._pe.getPointer(b),f,c,r,e))&&n(d,f,c,h);return b}})(a.PeGTTransformations||(a.PeGTTransformations={}));(function(b){function c(b,c,e,f,l,r){a._pe.ensureCache.prepare();var d,g;switch(b){case "dd":d=a._pe._pe_geog_to_dd;g=h.PE_DD_MAX;break;case "ddm":d=a._pe._pe_geog_to_ddm;g=h.PE_DDM_MAX;break;
case "dms":d=a._pe._pe_geog_to_dms,g=h.PE_DMS_MAX}b=0;c&&(b=a._pe.getPointer(c));c=p(f);c=a._pe.ensureFloat64(c);g=t(e,g);f=a._pe.ensureInt32(g);if(l=d(b,e,c,l,f))for(d=0;d<e;d++)r[d]=a._pe.Pointer_stringify(g[d]);return l}function f(b,c,e,f,h){a._pe.ensureCache.prepare();var d;switch(b){case "dd":d=a._pe._pe_dd_to_geog;break;case "ddm":d=a._pe._pe_ddm_to_geog;break;case "dms":d=a._pe._pe_dms_to_geog}b=0;c&&(b=a._pe.getPointer(c));c=f.map(function(b){return a._pe.ensureString(b)});f=a._pe.ensureInt32(c);
c=a._pe.ensureFloat64(Array(2*e));(d=d(b,e,f,c))&&n(h,e,c);return d}b.geog_to_dms=function(a,b,e,f,h){return c("dms",a,b,e,f,h)};b.dms_to_geog=function(a,b,c,k){return f("dms",a,b,c,k)};b.geog_to_ddm=function(a,b,e,f,h){return c("ddm",a,b,e,f,h)};b.ddm_to_geog=function(a,b,c,k){return f("ddm",a,b,c,k)};b.geog_to_dd=function(a,b,e,f,h){return c("dd",a,b,e,f,h)};b.dd_to_geog=function(a,b,c,h){return f("dd",a,b,c,h)}})(a.PeNotationDms||(a.PeNotationDms={}));var x;(function(b){b.init=function(){b.PE_MGRS_STYLE_NEW=
a._pe.PeNotationMgrs.prototype.get_PE_MGRS_STYLE_NEW();b.PE_MGRS_STYLE_OLD=a._pe.PeNotationMgrs.prototype.get_PE_MGRS_STYLE_OLD();b.PE_MGRS_STYLE_AUTO=a._pe.PeNotationMgrs.prototype.get_PE_MGRS_STYLE_AUTO();b.PE_MGRS_180_ZONE_1_PLUS=a._pe.PeNotationMgrs.prototype.get_PE_MGRS_180_ZONE_1_PLUS();b.PE_MGRS_ADD_SPACES=a._pe.PeNotationMgrs.prototype.get_PE_MGRS_ADD_SPACES()};b.geog_to_mgrs_extended=function(b,f,d,g,e,k,l){a._pe.ensureCache.prepare();var c=0;b&&(c=a._pe.getPointer(b));b=p(d);d=a._pe.ensureFloat64(b);
b=t(f,h.PE_MGRS_MAX);var m=a._pe.ensureInt32(b);if(g=a._pe._pe_geog_to_mgrs_extended(c,f,d,g,e,k,m))for(e=0;e<f;e++)l[e]=a._pe.Pointer_stringify(b[e]);return g};b.mgrs_to_geog_extended=function(b,f,d,g,e){a._pe.ensureCache.prepare();var c=0;b&&(c=a._pe.getPointer(b));b=d.map(function(b){return a._pe.ensureString(b)});d=a._pe.ensureInt32(b);b=a._pe.ensureFloat64(Array(2*f));(g=a._pe._pe_mgrs_to_geog_extended(c,f,d,g,b))&&n(e,f,b);return g}})(x=a.PeNotationMgrs||(a.PeNotationMgrs={}));(function(b){b.geog_to_usng=
function(b,f,d,g,e,k,l){a._pe.ensureCache.prepare();var c=0;b&&(c=a._pe.getPointer(b));b=p(d);d=a._pe.ensureFloat64(b);b=t(f,h.PE_MGRS_MAX);var m=a._pe.ensureInt32(b);if(g=a._pe._pe_geog_to_usng(c,f,d,g,e,k,m))for(e=0;e<f;e++)l[e]=a._pe.Pointer_stringify(b[e]);return g};b.usng_to_geog=function(b,f,d,g){a._pe.ensureCache.prepare();var c=0;b&&(c=a._pe.getPointer(b));b=d.map(function(b){return a._pe.ensureString(b)});d=a._pe.ensureInt32(b);b=a._pe.ensureFloat64(Array(2*f));(c=a._pe._pe_usng_to_geog(c,
f,d,b))&&n(g,f,b);return c}})(a.PeNotationUsng||(a.PeNotationUsng={}));var y;(function(b){b.init=function(){b.PE_UTM_OPTS_NONE=a._pe.PeNotationUtm.prototype.get_PE_UTM_OPTS_NONE();b.PE_UTM_OPTS_ADD_SPACES=a._pe.PeNotationUtm.prototype.get_PE_UTM_OPTS_ADD_SPACES();b.PE_UTM_OPTS_NS=a._pe.PeNotationUtm.prototype.get_PE_UTM_OPTS_NS()};b.geog_to_utm=function(b,f,d,g,e){a._pe.ensureCache.prepare();var c=0;b&&(c=a._pe.getPointer(b));b=p(d);d=a._pe.ensureFloat64(b);b=t(f,h.PE_UTM_MAX);var l=a._pe.ensureInt32(b);
if(g=a._pe._pe_geog_to_utm(c,f,d,g,l))for(c=0;c<f;c++)e[c]=a._pe.Pointer_stringify(b[c]);return g};b.utm_to_geog=function(b,f,d,g,e){a._pe.ensureCache.prepare();var c=0;b&&(c=a._pe.getPointer(b));b=d.map(function(b){return a._pe.ensureString(b)});d=a._pe.ensureInt32(b);b=a._pe.ensureFloat64(Array(2*f));(g=a._pe._pe_utm_to_geog(c,f,d,g,b))&&n(e,f,b);return g}})(y=a.PeNotationUtm||(a.PeNotationUtm={}));var z;(function(b){var c=new Map;b.init=function(){b.PE_PCSINFO_OPTION_NONE=a._pe.PePCSInfo.prototype.get_PE_PCSINFO_OPTION_NONE();
b.PE_PCSINFO_OPTION_DOMAIN=a._pe.PePCSInfo.prototype.get_PE_PCSINFO_OPTION_DOMAIN();b.PE_POLE_OUTSIDE_BOUNDARY=a._pe.PePCSInfo.prototype.get_PE_POLE_OUTSIDE_BOUNDARY();b.PE_POLE_POINT=a._pe.PePCSInfo.prototype.get_PE_POLE_POINT()};b.generate=function(f,d){void 0===d&&(d=b.PE_PCSINFO_OPTION_DOMAIN);var g,e;c.has(f)&&(e=c.get(f),e[d]&&(g=e[d]));g||(g=a._pe.PePCSInfo.prototype.generate(f,d),e||(e=[],c.set(f,e)),e[d]=g);return g}})(z=a.PePCSInfo||(a.PePCSInfo={}));(function(b){b.version_string=function(){return a._pe.PeVersion.prototype.version_string()}})(a.PeVersion||
(a.PeVersion={}));a._init=v});